### ISSUE TITLE
Display Commit Hash and semver on UI 

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#290]
The `main` branch needs to be manually updated on occasion. This shouldn't be automated because we (especially me) should review all the code changes to look for rugs before hosting on our main website. 

To serve as a reminder, it will probably be wise to display a version number, which can be clicked to see the commit that's deployed. It will be easy to see how far the code is out of date for with this feature.

Just expose the commit hash for now, and eventually we should follow a semantic versioning system and show that with the hash or instead (decision for a later date.)

***
> I just realized that `production` is just out of date. @ubiquity/bounty-masters we should figure a process to make sure stuff like this doesn't happen again.

> https://531ffccd.ubiquity-dollar-development.pages.dev/ from https://github.com/ubiquity/ubiquity-dollar/runs/8485554679

> <img width="1218" alt="image" src="https://user-images.githubusercontent.com/4975670/195695687-368c68de-83d1-4661-bdf6-b72480e94597.png">

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/283#issuecomment-1278109550_

**Comment by cuddle-dev** [comment]
> The `main` branch needs to be manually updated on occasion. This shouldn't be automated because we (especially me) should review all the code changes to look for rugs before hosting on our main website.
> 
> To serve as a reminder, it will probably be wise to display a version number, which can be clicked to see the commit that's deployed. It will be easy to see how far the code is out of date for with this feature.
> 
> Just expose the commit hash for now, and eventually we should follow a semantic versioning system and show that with the hash or instead (decision for a later date.)
> 
> I just realized that `production` is just out of date. @ubiquity/bounty-masters we should figure a process to make sure stuff like this doesn't happen again.
> 
> https://531ffccd.ubiquity-dollar-development.pages.dev/ from https://github.com/ubiquity/ubiquity-dollar/runs/8485554679
> 
> <img alt="image" width="1218" src="https://user-images.githubusercontent.com/4975670/195695687-368c68de-83d1-4661-bdf6-b72480e94597.png">
> 
> _Originally posted by @pavlovcik in [#283 (comment)](https://github.com/ubiquity/ubiquity-dollar/issues/283#issuecomment-1278109550)_

we should actually do versioning system so once we released a new version it needs to get merged into main.  but agree with exposing commit hash right now. To do that, need to update ci/cd.

**Comment by 0x4007** [comment]
Perhaps it's not the best example of Actions for this but I decided to post this here while randomly browsing another GitHub project. 

https://github.com/m1guelpf/chatgpt-telegram/tree/main/.github/workflows

**Comment by rndquu** [comment]
the task is to display a `dapp` package version from here https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/package.json#L3 in the bottom right corner which on click opens currently deployed commit hash from github, right?

<img width="1440" alt="Screenshot 2022-12-05 at 16 46 36" src="https://user-images.githubusercontent.com/119500907/205653256-2b880966-6942-417c-b32b-6176afe5bace.png">

**Comment by 0x4007** [comment]
I think commit hash will be simpler and uniquely identifiable. At least until we figure out a GitHub Action to semver every merge into `production` automatically.

But yes, technically speaking the semver should be written/read to/from `package.json`

**Comment by 0x4007** [comment]
@rndquu can you post your DAI wallet address here?

**Comment by rndquu** [comment]
ethereum wallet: 0x336C033842FA316d470e820c81b742e62A0765DC

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0x9d53f08ec3a77178faaddabeac1d83a807007d141dea597a9dc7acf320d673bf
https://etherscan.io/tx/0x37b1e188d8acf3be3a5c533ce8e1e5b270bf0797b29d71824c8ae5217da247c1
