### ISSUE TITLE
Renaming Contracts to Reflect Current Product Names

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#292]
TODO: need to make a proper checklist but this is a placeholder issue that I will fill out at a later date.

We updated the branding on several products, including Bonding -> Staking; Ubiquity Auto Redeem -> Ubiquity Credit; and more. Currently they are only reflected in the UI but we should update the contracts to reflect the updated names.

***

        I understand your concern about renaming. If we create a new issue for renaming and resolve them on it, we will never miss any renaming stuff. we can also have checklist on the issue which gives clear steps to do.

_Originally posted by @0xcodercrane in https://github.com/ubiquity/ubiquity-dollar/pull/261#discussion_r997389498_

**Comment by cuddle-dev** [comment]
Would you make a todo list for renaming contracts?

**Comment by 0x4007** [comment]
- [ ] BondingFormulas.sol ⮕ StakingFormulas.sol
- [ ] BondingShareV2.sol ⮕ StakingShare.sol
- [ ] BondingV2.sol ⮕ Staking.sol
- [ ] CouponsForDollarsCalculator.sol ⮕ CreditNFTRedemptionCalculator.sol
- [ ] CurveUADIncentive.sol ⮕ transfer-hooks/dollar3pool.sol
- [ ] DebtCoupon.sol ⮕ CreditNFT.sol
- [ ] DebtCouponManager.sol ⮕  CreditNFTManager.sol
- [ ] DollarMintingCalculator.sol ⮕ DollarMintCalculator.sol
- [ ] ERC20Ubiquity.sol
- [ ] ERC1155Ubiquity.sol
- [ ] ExcessDollarsDistributor.sol ⮕ DollarMintExcess.sol
- [ ] MasterChefV2.sol ⮕ UbiquityChef.sol
- [ ] ProxyYieldAggregator.sol ⮕ (we should delete this from the codebase, as it was more of an alpha test)
- [ ] SushiSwapPool.sol 
- [ ] TWAPOracle.sol ⮕ TWAPOracleDollar3pool.sol
- [ ] UARForDollarsCalculator.sol ⮕ CreditRedemptionCalculator.sol
- [ ] UbiquityAlgorithmicDollar.sol ⮕ UbiquityDollarToken.sol
- [ ] UbiquityAlgorithmicDollarManager.sol ⮕ UbiquityDollarManager.sol
- [ ] UbiquityAutoRedeem.sol ⮕ UbiquityCreditToken.sol
- [ ] UbiquityFormulas.sol 
- [ ] UbiquityGovernance.sol ⮕ UbiquityGovernanceToken.sol

Some patterns to follow when renaming variables and comments in the code:

- [ ] Do not refer to the token symbols directly (e.g. uAD, UBQ, uCR, uCR-NFT) anywhere in the codebase because we have the ability to update the symbols on the token smart contracts. Instead refer to them as "Dollar" "Governance" "Credit" and "Credit NFT" respectively (e.g. UbiquityDollarToken.sol) 
    - [ ] I feel like thats also more clear for future developers if they know the purpose of the token (e.g. Dollar, Credit, Governance) vs them having to remember the token symbols.
- [ ] We should separate core Dollar protocol smart contracts from not core contracts. For example, transfer hooks are extensions; the vaults/proxy-yield-aggregator is also not core.
- [ ] We rebranded "Bonding" to "Staking" to disambiguate our bonds (e.g. Chicken Bonds) branding.
- [ ] We rebranded "Debts" to "Credits" because it has a positive connotation for the users.
- [ ] We rebranded "Ubiquity Algorithmic Dollar" to "Ubiquity Dollar" because the term "algorithmic" is contentious in this context after Luna.

**Comment by 0x4007** [comment]
> UbiquityFormulas.sol

This is off topic and I just wanted to put it here to not forget to briefly discuss, but I believe that upgrading this contract to the Diamond Standard might be appropriate for the same reason I proposed #300

**Comment by ryzhak** [comment]
I can take this one

So basically the following should be done:
1. Contract renaming
2. Variables and comments renaming

A few questions:
1. Should I also update this wiki page after the renaming: https://github.com/ubiquity/ubiquity-dollar/wiki/18.-Smart-Contracts ?
2. Could you provide a list of contracts which are considered "core"? I will move them to the `core` directory.

There should also be the task to update frontend because after these changes it will be completely broken due to contract and variable renaming

**Comment by 0x4007** [comment]
Sorry for the slow response I've been feeling unwell the last couple days.

> Should I also update this wiki page after the renaming: https://github.com/ubiquity/ubiquity-dollar/wiki/18.-Smart-Contracts ?

Technically this is out of scope of the bounty but yes this would be much appreciated if you wish to.

> Could you provide a list of contracts which are considered "core"? I will move them to the core directory.

I'll add this to my todo list cause right now I'm prioritizing responding to all the blockers. To give you a high level answer, the Dollar, the Credits and the Governance token systems are considered "core" Ubiquity Dollar contracts. 

Proxy Yield Aggregator/vaults; cashback rewards and UbiquiStick NFT are not core.

**Comment by 0x4007** [comment]
@ryzhak you can request a review from @0xcodercrane and I on your PR when its ready!

**Comment by ryzhak** [comment]
> Do not refer to the token symbols directly (e.g. uAD, UBQ, uCR, uCR-NFT) anywhere in the codebase

just to clarify, should I also update method signatures and variable names?

Examples:
1. https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/BondingV2.sol#L169: `uADPriceReset => dollarPriceReset`
2. https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/UARForDollarsCalculator.sol#L44: `getUARAmount => getCreditAmount`

**Comment by 0x4007** [comment]
Yes

**Comment by 0x4007** [comment]
As per my review https://github.com/ubiquity/ubiquity-dollar/pull/351#pullrequestreview-1207364625 I am ok to release the bounty before merging because I have a feeling we may have some internal delays due to potential merge conflicts of other open PRs to accommodate (which isn't your problem.) There is a possibility that @0xcodercrane comes in with some requested changes but I imagine that they would be minor if it even happens. Can you confirm your wallet address?

**Comment by ryzhak** [comment]
@pavlovcik 

wallet: 0x165343c045a00770b61DbCa01956590cC6005666

**Comment by 0x4007** [comment]
> 0x165343c045a00770b61DbCa01956590cC6005666

https://etherscan.io/tx/0xe591458b63e4802a829205abf2e2e5ad95c3ac25e7fb093069317782f6b6b8d4
https://etherscan.io/tx/0x1a0f4a77e1f8845417a48b69f40e3c4dfd98aadc34ba4b7cb35bb39e20a93fde
