### ISSUE TITLE
Deploy Scripts Refactoring

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#294]
I see a lot of repetitive logic, I would consider making a utility function to handle every instance. For example, I imagine you could generate the `contractInstance` value by passing in `__filename` into this utility function. To clarify, this isn't a blocker; we can definitely merge without clean deploy scripts but its just something that I personally would have done.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/pull/261#discussion_r997309360_

**Comment by 0x4007** [comment]
Consider this a really low priority issue. I was on the fence about creating the bounty at all but decided why not just leave it here for a rainy day.

**Comment by nevermind0825** [comment]
Hi, hope you are doing great.
If you assign to me this task, I will solve this issue.

**Comment by sergfeldman** [comment]
@pavlovcik Please check whether this issue is actual

**Comment by cuddle-dev** [comment]
> @pavlovcik Please check whether this issue is actual

Yeah I can update you with this. This issue is still available but low priority. @pavlovcik  would you give more context for @nevermind0825  to take over?

**Comment by sergfeldman** [comment]
@nevermind0825 You are assigned to this issue.
If you have questions, please post them in the comments.

**Comment by 0x4007** [comment]
> > @pavlovcik Please check whether this issue is actual
> 
> Yeah I can update you with this. This issue is still available but low priority. @pavlovcik would you give more context for @nevermind0825 to take over?

This was originally intended for a core dev to handle as its quite subjective on making a pass to optimize the code to make it less repetitive. The original vision was to have you @0xcodercrane handle it.

Let's scope this to the deployment scripts. Bounty hunter should clean those up. Try and modularize the deployment logic into reusable functions.

**Comment by nevermind0825** [comment]
Thank you for assigned to me.
What should I do next?
Should I clone ubiquity-dollar project?

**Comment by 0x4007** [comment]
https://dao.ubq.fi/devpool-flow

**Comment by Steveantor** [comment]
would give it a go

**Comment by sergfeldman** [comment]
> would give it a go

@Steveantor You are assigned

**Comment by Steveantor** [comment]
PR #431

**Comment by 0x4007** [comment]
Hey @Steveantor would you mind posting your address here to collect your bounty?

**Comment by Steveantor** [comment]
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by 0x4007** [comment]
> Here's my address: `0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE` @pavlovcik

https://etherscan.io/tx/0x1188bd850d41f5d45c6723db2999b7381c9da7f70ff6ce521ce80a470381ec16
https://etherscan.io/tx/0x7b87545b8ad28000c38f017fdc2d0c425913413f6159b2c142c6eaea0f0f532a
