### ISSUE TITLE
Upgrade `UbiquityAlgorithmicDollarManager.sol` to ERC2535 Diamond Standard

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#300]
We have limited slots to associate contracts with our protocol on the current Manager implementation. The Diamond Standard seems to be a useful architecture for our protocol as we continue to plan to build an ecosystem around our dollar.

This project would require the smart contract implementation, associated tests, and finally a redeployment. 

As of this moment it is not clear if we must redeploy everything, or if we can simply redeploy the Manager and use the new Manager instead.

**Comment by 0xautohub** [comment]
Hey @pavlovcik @sergfeldman I'm really interested in ERC-2535 standard implementation
So I would like to work on this issue

**Comment by 0x4007** [comment]
Okay great you're authorized to proceed!

**Comment by sergfeldman** [comment]
@sunny0714 This task has not yet been offered for the Bounty System and the amount of payment has not yet been determined.
Before you start this task, please bid - suggest the amount of payment and the timeframe for which you want to complete it.
After that, we will approve or negotiate the amount of payment.

**Comment by pavlovcik** [comment]
> @sunny0714 This task has not yet been offered for the Bounty System and the amount of payment has not yet been determined. Before you start this task, please bid - suggest the amount of payment and the timeframe for which you want to complete it. After that, we will approve or negotiate the amount of payment.

The parameters are set I just didn't look up the prices.

**Comment by 0x4007** [comment]
> @sunny0714 This task has not yet been offered for the Bounty System and the amount of payment has not yet been determined. Before you start this task, please bid - suggest the amount of payment and the timeframe for which you want to complete it. After that, we will approve or negotiate the amount of payment.

All set @sergfeldman 

# Specification

- [ ] smart contract implementation 
- [ ] unit tests
- [ ] redeployment script
- [ ] redeployment

Please be mindful of our access control system (the minter/burner roles) I believe that they are managed by the old manager! @zgorizzo69 if you have any remarks please feel free to add here.

**Comment by zgorizzo69** [comment]
@sunny0714 which diamond implementation have you selected for the manager?

**Comment by zgorizzo69** [comment]
We should consider 
- adding script to upgrade facet
- having a test that will run all the existing tests with an upgraded facet. This is to ensure that we didn't mess with the storage
Also here is a convenient way to explore facet implementation https://louper.dev/

**Comment by 0xautohub** [comment]
> @sunny0714 which diamond implementation have you selected for the manager?

@zgorizzo69 I have selected diamond-3, which uses less gas to call the diamond loupe functions which are expected to be called frequently after implementation
Please update me with your opinion

**Comment by zgorizzo69** [comment]
> > @sunny0714 which diamond implementation have you selected for the manager?
> 
> @zgorizzo69 I have selected diamond-3, which uses less gas to call the diamond loupe functions which are expected to be called frequently after implementation Please update me with your opinion, if I was wrong

Ideally we will not call loupe onchain but rather directly access the facet storage except if the logic to access the data is complex and so we want to avoid duplicate code

**Comment by cuddle-dev** [comment]
> As of this moment it is not clear if we must redeploy everything, or if we can simply redeploy the Manager and use the new  Manager instead.

we should redeploy everything.  but UADManager contract is currently responsible for managing contract addresses, not contract instances.  What I was thinking is why we selected diamond pattern to upgrade manager contract. 
If I summarize the concept and benefit of EIP2535 diamond proxy, this is sort of a upgradable proxy contract which has different architecture from other proxy contracts like OpenzeppelinProxy, TransparentUpgradableProxy, UUPSUpgradableProxy, etc. The weakness of previous proxy contracts was just we couldn't extend contract(implementation) size up to 24KB (in terms of size, if i remember correctly). Diamond resolved this by creating a new architecture design with facet, loupe facet, mapping, etc. 

In our case, what we want is to have a new manager contract to manage external contracts, not implementations used by proxy. 

**1/ Without EIP-2535.**
We can also update `UbiquityAlgorithmicDollarManager.sol` properly without using EIP-2535. This will absolutely manage all the contract addresses which would get deployed in the future without upgrading. I am leaning towards this way actually.

**2/ With EIP-2535**
If we have to use EIP-2535 for `UbiquityAlgorithmicDollarManager` improvement, we should decide how many facets are needed, what does each facet do, loupeFacet functions, storage architecture design with diamond-3. (I agree with @sunny0714 's selection), @sunny0714  please provide us the architecture for the first if this case confirmed before you start working because this is a little bit different from other proxy standards, so that would be good to confirm the architecture for the first.

**Comment by 0xautohub** [comment]
> In our case, what we want is to have a new manager contract to manage external contracts, not implementations used by proxy.

@0xcodercrane Great comments, And thanks for your comment and research
I'm thinking that the purpose of this issue is to make the contract fully upgradable to be able to build an ecosystem, rather than  to improve `UbiquityAlgorithmicDollarManager` with EIP-2535

According to my research so far, EIP-2535 diamonds enable us to upgrade and extend the already deployed smart contract without redeployment by building efficient and modular contract systems
As for the architecture, I hate to tell again EIP-2535 doc. I recommend reading [this](https://eips.ethereum.org/EIPS/eip-2535) once

**Comment by cuddle-dev** [comment]
No. this is to upgrade `UbiquityAlgorithmicDollarManager.sol` to ERC2535 diamond standard.  Look at the issue title again. Lol
Thanks for attaching EIP-2535 doc link @sunny0714 . Fortunately I went through most docs regarding to EIP-2535 maybe 4 ~ 5 months ago.

**Comment by 0xautohub** [comment]
@pavlovcik Seems to need your checking now

**Comment by cuddle-dev** [comment]
> @pavlovcik Seems to need your checking now

Yeah for sure. will wait for his confirmation here. By the way, could we look at any codebase you did with EIP-2535 if you have any?

**Comment by 0xautohub** [comment]
> Thanks for attaching EIP-2535 doc link @sunny0714 . Fortunately I went through most docs regarding to EIP-2535 maybe 4 ~ 5 months ago.

Cool, sounds great

**Comment by 0xautohub** [comment]
> > @pavlovcik Seems to need your checking now
> 
> Yeah for sure. will wait for his confirmation here. By the way, could we look at any codebase you did with EIP-2535 if you have any?

No, I can't. I don't have any codebase. Coding was not important for me. I focused on research on diamond implementation so far

**Comment by 0xautohub** [comment]
> Thanks for attaching EIP-2535 doc link @sunny0714 . Fortunately I went through most docs regarding to EIP-2535 maybe 4 ~ 5 months ago.

I felt that from your comment. Awesome. My intention is not to disagree with your opinion, just want to check the direction for development

**Comment by cuddle-dev** [comment]
> No, I don't have any codebase. Coding was not important for me. I focused on research on diamond implementation so far

Ok. I was asking that question cause architecture design is sort of important for Diamond pattern.  but don't worry about that at all.

**Comment by 0xautohub** [comment]
>@sunny0714 please provide us the architecture for the first if this case confirmed before you start working because this is a little bit different from other proxy standards, so that would be good to confirm the architecture for the first.

@0xcodercrane I misunderstood the architecture you mentioned here as the new architecture of Diamond

I'm feeling you've already tried to design the storage architecture depending on any diamond implementation approach
So I guess that your tries for storage architecture design might help to implement EIP-2535 at a fast pace

**Comment by zgorizzo69** [comment]
- Ideally to identify what belongs to each facet we should try to separate what can work with his own storage without relying on other facets storage. In reality that is not that simple and we often relies on a global storage
- An important undervalued advantage of diamond is that all calls are internal and so we will save quite some gas

**Comment by cuddle-dev** [comment]
> * Ideally to identify what belongs to each facet we should try to separate what can work with his own storage without relying on other facets storage. In reality that is not that simple and we often relies on a global storage
> * An important undervalued advantage of diamond is that all calls are internal and so we will save quite some gas
Awesome!!!

Btw, can I also get your opinion why we wanted EIP-2535 for `UbiquityAlgorithmicDollarManager.sol` upgrade? This contract just has getters/setters functions for deployed contract addresses. We can definitely do that without upgradable standard. I just want to make things clear.

**Comment by zgorizzo69** [comment]
> > * Ideally to identify what belongs to each facet we should try to separate what can work with his own storage without relying on other facets storage. In reality that is not that simple and we often relies on a global storage
> > * An important undervalued advantage of diamond is that all calls are internal and so we will save quite some gas
> >   Awesome!!!
> 
> Btw, can I also get your opinion why we wanted EIP-2535 for `UbiquityAlgorithmicDollarManager.sol` upgrade? This contract just has getters/setters functions for deployed contract addresses. We can definitely do that without upgradable standard. I just want to make things clear.

This is convenient when you have a lot of features/ SC graviting around a core cos then you simply add/update facet and you can access all the storage easily. Like we want to add a proxy yield manager as it is not part of the manager already we can link it directly like the bonding manager so we will have to push the manager address in the proxy yield manager one way or another. And tomorrow I am sure we will have other brilliant idea to implement and we will want to link it to the manager again

**Comment by 0x4007** [comment]
> @pavlovcik Seems to need your checking now

I'm not sure I'm fully understanding the misinterpretation here, but my expectation is that we create a brand new Diamond Standard compliant manager contract to replace our manager that we are using now in production. 

My naive take would be that it's cleaner to start fresh, instead of trying to make the old stuff work.

**Comment by cuddle-dev** [comment]
I love your brilliant idea.

**Comment by cuddle-dev** [comment]
> I'm not sure I'm fully understanding the misinterpretation here, but my expectation is that we create a brand new Diamond Standard compliant manager contract to replace our manager that we are using now in production.

hmm, If Diamond is a new brand in terms of marketing, engineers/hunters just need to follow up. sometimes engineers focus on only tech side regardless of marketing side.

**Comment by 0x4007** [comment]
> I love your brilliant idea. 

You mean redeployment? 😂 yes, thank you. It's big brain time.

**Comment by cuddle-dev** [comment]
> You mean redeployment? 😂 yes, thank you. It's big brain time.

I couldn't guess @zgorizzo69 's idea. I'd love to listen his brilliant idea soon :dancer:

**Comment by 0x4007** [comment]
> > You mean redeployment? 😂 yes, thank you. It's big brain time.
> 
> I couldn't guess @zgorizzo69 's idea. I'd love to listen his brilliant idea soon 💃

@zgorizzo69 is solidity sensei. Heed his word 

![AgADEwMAAtlxBFM](https://user-images.githubusercontent.com/4975670/199143510-b31ddf8b-80bf-4c8b-8bf8-3a13e6b83aa1.gif)

**Comment by 0x4007** [comment]
@sunny0714 sent me a DM confirming that he is not making an ERC2535 Diamond Standard manager contract because you guys said its a bad idea. 

I understand its a good idea so I think that we should proceed with making an ERC2535 Diamond Standard manager contract.

Thumbs up if you agree. Thumbs down if you do not agree.

**Comment by 0xautohub** [comment]
> @sunny0714 sent me a DM confirming that he is not making an ERC2535 Diamond Standard manager contract because you guys said its a bad idea.
> 
> I understand its a good idea so I think that we should proceed with making an ERC2535 Diamond Standard manager contract.
> 
> Thumbs up if you agree. Thumbs down if you do not agree.

Just wanted to check that I should keep implementing Diamond, or not. All comments helped me a lot to confirm the development direction. And hope you guys to continue to update me with your ideas. Thanks @pavlovcik and all

**Comment by 0xautohub** [comment]
Fyi (according to the development so far):
1. We can generate EIP-2535 compliant Manager from already deployed UbiquityAlgorithmicDollarManager. Simply can we add the functions on it to Diamond
2. And if do not want to use any function(ex: setuARTokenAddress), we can exclude that function selector when adding to Diamond, or if included it, can remove it at any time
3.  if want to add more functions(ex: setuCRtokenAddress), we can create a new Facet which includes new function and add it to Diamond
4. if want to upgrade an existing function, after creating a new Facet which includes an upgraded function with the same name, and replace the old function with new one(existing on new Facet) on Diamond

**Comment by 0x4007** [comment]
That all lines up with my relatively naive understanding of the standard. Sounds good.

**Comment by 0xautohub** [comment]
@pavlovcik @0xcodercrane 
Please check [this comment](https://github.com/ubiquity/ubiquity-dollar/pull/313#issuecomment-1309432889)

**Comment by sergfeldman** [comment]
**The description of the situation with the Diamond implementation:**
- The execution of the bounty has already taken significantly more time than expected.
- There were a lot of points in comments, some of them are resolved but for a number of points an optimal resolution was not found.
- There is progress on this bounty, but the movement is not effective enough.

**The decision:**
- Merge the PR #380 with minimal required updates mentioned in the comments.
- Pay @sunny0714 60% of the bounty price.
- To continue the Diamond implementation in a separate bounty with another assignee.

@sunny0714 thanks for starting this movement!
You are welcome to take a new bounty.

**Comment by sunny0714** [comment]
Okay, thanks

**Comment by 0xautohub** [comment]
@sergfeldman okay, thanks
This is really shock for me because I thought that I could deliver diamond implementation at last through long journey of development, but I'm feeling okay now

Well, I still didn't get paid about the work of [UCR Cash out UI issue](https://github.com/ubiquity/ubiquity-dollar/issues/225) yet

Hope to get paid together this time
Thanks

**Comment by 0xautohub** [comment]
Here is my address
0xfe1c4a93a97be87b3e45ef573c936a89eb5b61f1

**Comment by sergfeldman** [comment]
> Here is my address 0xfe1c4a93a97be87b3e45ef573c936a89eb5b61f1

@sunny0714 Is it ok to send USDC to this wallet?

**Comment by 0xautohub** [comment]
Yeah, okay

**Comment by sergfeldman** [comment]
@sunny0714 Thank you! https://etherscan.io/tx/0x87be4c2ba978a576db667438d956ff35554b4bfa6778d21a07b58d94e9f0e923

**Comment by 0xautohub** [comment]
> Well, I still didn't get paid about the work of [UCR Cash out UI issue](https://github.com/ubiquity/ubiquity-dollar/issues/225) yet

@sergfeldman What about this? How is the team going to do with this payment?

**Comment by sergfeldman** [comment]
> > Well, I still didn't get paid about the work of [UCR Cash out UI issue](https://github.com/ubiquity/ubiquity-dollar/issues/225) yet
> 
> @sergfeldman What about this?

@sunny0714 Checking it at the moment. 
As I see 
https://github.com/ubiquity/ubiquity-dollar/issues/225 is dependent on https://github.com/ubiquity/ubiquity-dollar/issues/282

@pavlovcik @sunny0714 
https://github.com/ubiquity/ubiquity-dollar/issues/282 is done and completely paid 

https://github.com/ubiquity/ubiquity-dollar/issues/225 - is it considered as done?
I see the partial payment, but this is probably for testing purposes 
https://etherscan.io/tx/0x7ff0e5fa2faf4770bcfc220a19a5927ee016eaf8970ce5e63ebffb3d0eb7f156

**Comment by sergfeldman** [comment]
@sunny0714 FYI @pavlovcik is busy with the conference this week, so the delays of responses are expected
