### ISSUE TITLE
Setup Docker (Foundry Image) for CI

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#308]
# Background

I believe that we shouldn't be committing all of this metadata. Otherwise it makes PR reviews very tedious, having to sift through hundreds of changed files every time theres a small update.

A proposed solution is to install Foundry on CI so that this metadata can be generated locally on the runner, instead of reading from the repository.

> I would look to other Foundry repos to see how they solved this problem. I'm sure if we can copy a script, we could solve the issue. 

> The reason why I bring this up is because this makes PR reviews very tedious. You already changed like 250 files and only were working on this for a little bit.

> Why not just install Foundry during the CI process?

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/pull/302#discussion_r1004857028_
      

# Spec

1. Upgrade our CI to use the Docker Foundry image. 
2. After this is set up, we should remove all artifacts generated from build from the codebase, e.g. `packages/contracts/out/CollectableDust.sol/CollectableDust.json`

**Comment by 0x4007** [comment]
You can setup a GitHub Action to use a Docker container (vs a Javascript action) 

https://docs.github.com/en/actions/creating-actions/about-custom-actions#docker-container-actions

Here's Foundry's Docker container, from https://github.com/gakonst/foundry/pkgs/container/foundry

```sh
docker pull ghcr.io/gakonst/foundry:nightly-90617a52e4873f0137aa05fd68624437db146b3f
```

**Comment by 0x4007** [comment]
@sergfeldman I understand that you're filling in the gap between now and what the Ubiquity Bounty Bot will eventually handle. The label should have been calculated to be valued at $1000, and the $1000 should have been paid out to Liu with the transaction hash being posted here.

I suppose we don't always need bounty hunters to post their address every time to claim, because we could save it in the Ubiquity Bounty Bot database.

**Comment by sergfeldman** [comment]
> @sergfeldman I understand that you're filling in the gap between now and what the Ubiquity Bounty Bot will eventually handle. The label should have been calculated to be valued at $1000, and the $1000 should have been paid out to Liu with the transaction hash being posted here.
> 
> I suppose we don't always need bounty hunters to post their address every time to claim, because we could save it in the Ubiquity Bounty Bot database.

@0xcodercrane Please, check :)
https://etherscan.io/tx/0x6bb1cca3670f6e0127688b60fd9825a1bc2c072eb58a6f8e12c420d8235f30e7

**Comment by cuddle-dev** [comment]
@sergfeldman  @pavlovcik  received!!! thanks all
