### ISSUE TITLE
Update CI to Node 16

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#311]
[receive-pr-and-deploy](https://github.com/ubiquity/ubiquity-dollar/actions/runs/3366042114/jobs/5582129072)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/github-script, actions/checkout

**Comment by cuddle-dev** [comment]
> [receive-pr-and-deploy](https://github.com/ubiquity/ubiquity-dollar/actions/runs/3366042114/jobs/5582129072) Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/github-script, actions/checkout

I think we should upgrade to 18.x because 16.x went into maintenance. 
https://github.com/nodejs/release#release-schedule

**Comment by 0x4007** [comment]
[build-and-test](https://github.com/ubiquity/ubiquity-dollar/actions/runs/3669413906/jobs/6203227245)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2, actions/upload-artifact@v2

**Comment by pavlovcik** [comment]
[Install and Build Workflow: .github#L1](https://github.com/ubiquity/ubiquity-dollar/commit/3610440ebe6e4c541a52ed3b9704c78e75f680b5#annotation_6951835664)
ubuntu-latest workflows will use ubuntu-22.04 soon. For more details, see https://github.com/actions/runner-images/issues/6399

**Comment by zgorizzo69** [comment]
I found the problem will take care of that

**Comment by zgorizzo69** [comment]
done https://github.com/ubiquity/ubiquity-dollar/actions/runs/3679952590
https://github.com/ubiquity/ubiquity-dollar/actions/runs/3679951103
there is only a warning for new latest ubuntu version that will be v22 and we should be fine as it impacts ruby, php and python version.

**Comment by zgorizzo69** [comment]
on a precautionary basis I tried it with ubuntu 22.04 and it works great :+1:  https://github.com/ubiquity/ubiquity-dollar/actions/runs/3680087591 https://github.com/ubiquity/ubiquity-dollar/actions/runs/3680087453

**Comment by cuddle-dev** [comment]
Lets just replace it with ubuntu-22.04 and merge your [PR](https://github.com/ubiquity/ubiquity-dollar/pull/390). by the way, replace should be happening in both yml files in .github/workflows

**Comment by zgorizzo69** [comment]
> Lets just replace it with ubuntu-22.04 and merge your [PR](https://github.com/ubiquity/ubiquity-dollar/pull/390). by the way, replace should be happening in both yml files in .github/workflows

done !

**Comment by sergfeldman** [comment]
@zgorizzo69 https://etherscan.io/tx/0x36a4c9a4cd8debc539e2bf2a229149612fd284d6861374c56dff40172454db9e

**Comment by 0x4007** [comment]
I just merged zgo's #311
