### ISSUE TITLE
Update to use Environment Files in CI

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#312]
[receive-pr-and-deploy](https://github.com/ubiquity/ubiquity-dollar/actions/runs/3366042114/jobs/5582129072#step:3:664)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by cuddle-dev** [comment]
This is not completed yet!!!

**Comment by 0x4007** [comment]
> This is not completed yet!!!

Looks tumultuous with all the issue opens and closes hope that you have this under control. 👀

**Comment by cuddle-dev** [comment]
> > This is not completed yet!!!
> 
> Looks tumultuous with all the issue opens and closes hope that you have this under control. 👀

I will do my best to have this under control. For this bounty, we need to keep our eyes on this issue not the pull request. Because we can test his pull request after merging. I will let you know once it gets completed

**Comment by 0x4007** [comment]
This one has been quite complicated to follow with the references to multiple issues/PRs. For future reference @0xcodercrane I've been trying to keep the payment proofs on the actual issues/bounties instead of the [PRs](https://github.com/ubiquity/ubiquity-dollar/pull/337#issuecomment-1324041256).

I presume that this is all finished according to the spec. 

@kfukue what is your Ethereum wallet address? We will send DAI and UBQ. Thanks.

**Comment by 0x4007** [comment]
Another idea is to have a separate fork of Ubiquity Dollar on @0xcodercrane personal GitHub where you could have CI disabled except for the CI that is being scrutinized/tested in order to save time on reviewing (instead of trying to merge into development, revert, repeat etc)

**Comment by kfukue** [comment]
@pavlovcik  @0xcodercrane Thanks, yea sorry I wasn't too familiar with github's CI/CDs but I'll use the forked version going forward. 
@pavlovcik My eth address is 0xB33aC2640b814145F76c1ba3B5D6aAB2216098aD. I'll look into more tasks going forward!

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0xb7b64a41e7085d7b05b60b4dabe2fafc997d69977a57f66038c29d47867a4836
https://etherscan.io/tx/0x0b01b9d9f3c3a510fb786f0b1efa3936561d1b55b4b695a51392bfc780b9d426

**Comment by kfukue** [comment]
@pavlovcik Thanks!
