### ISSUE TITLE
Update TheUbiquityStick nft contract to follow up opensea enforcement

### ISSUE THREAD

**Issue by cuddle-dev** [pavlovcik/uad-ui#315]
### Reference 
https://twitter.com/opensea/status/1589058770646491136

We need to upgrade UbiquiStick.sol to follow up opensea's enforcement to receive royalty fee.
Implementation should be straightforward. Here is the acceptance criteria

- [ ] Integrate opensea-filter-registry into UbiquiStick.sol
- [ ] Deploy new UbiquiStick on goerli network
- [ ] Setup royalty fee and address & make sure if royalty works properly.

**Comment by mul1sh** [comment]
Hi, i'm an experienced bounty hunter from [gitcoin](https://gitcoin.co/mul1sh) where I've been working on bounties for OS projects for more than 3 years now.

I'd like to take this issue.

**Approach**

1. Install the `opensea-filter-registry` project using [foundry](https://github.com/ProjectOpenSea/operator-filter-registry#getting-started-with-foundry)
2. Update the `UbiquiStick` nft contract to work with the registry as shown in the [default usage](https://github.com/ProjectOpenSea/operator-filter-registry#default-usage)

I'm confident i'll finish this in a day as required :)

**Comment by 0x4007** [comment]
@0xcodercrane @sergfeldman I see that technically this wasn't assigned to @ubiquity-bounties but I'm interested to have @mul1sh participate. Is this bounty ready? Can you finish the spec @0xcodercrane ?

**Comment by cuddle-dev** [comment]
> @0xcodercrane @sergfeldman I see that technically this wasn't assigned to @ubiquity-bounties but I'm interested to have @mul1sh participate. Is this bounty ready? Can you finish the spec @0xcodercrane ?

Yes, this is sort of straight forward. its just to integrate `opensea-filter-registry` into [UbiquiStick](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/ubiquistick/UbiquiStick.sol).

**Comment by mul1sh** [comment]
> > @0xcodercrane @sergfeldman I see that technically this wasn't assigned to @ubiquity-bounties but I'm interested to have @mul1sh participate. Is this bounty ready? Can you finish the spec @0xcodercrane ?
> 
> Yes, this is sort of straight forward. its just to integrate opensea-filter-registry into [UbiquiStick](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/ubiquistick/UbiquiStick.sol).

On it, thanks 🙂

**Comment by mul1sh** [comment]
My addy is 0x2d18BA0fcF0052E26Fc7b378dFBaF62D319E5D89

Thanks 🙂

**Comment by 0x4007** [comment]
> My addy is 0x2d18BA0fcF0052E26Fc7b378dFBaF62D319E5D89
> 
> Thanks 🙂

https://etherscan.io/tx/0xe3c0818fa3646048bbf433b8e777783420ecde07da3a65230eb1ccdd08827025

Congratulations!

**Comment by cuddle-dev** [comment]
> > My addy is 0x2d18BA0fcF0052E26Fc7b378dFBaF62D319E5D89
> > Thanks 🙂
> 
> https://etherscan.io/tx/0xe3c0818fa3646048bbf433b8e777783420ecde07da3a65230eb1ccdd08827025
> 
> Congratulations!

Good job @mul1sh
