### ISSUE TITLE
Code Review of Tiny Bond to ensure it meets spec

### ISSUE THREAD

**Issue by hashedMae** [pavlovcik/uad-ui#316]
[CONTRACTS](https://github.com/0xClandestine/tiny-bonds)

[SPEC](https://docs.google.com/document/d/1_qWL9kVyt6nX696yzGgy3T-zi3aXg9JeQfmFAxjAURY/edit)

Generalized bonds created by Concave for UBQ. Spec doc details what we need the bonds to do. Contracts need to be reviewed to ensure they fulfill spec.

**Comment by hashedMae** [comment]
This project was built in Foundry and includes testing. I believe a review of the tests should be part of this to ensure nothing was missed.

**Comment by hashedMae** [comment]
I can have this finished by end of next week for 1250 USDC

**Comment by 0x4007** [comment]
If you ever wanna chat about the specification regarding clarifications well, I know it like the back of my hand. Feel free to drop me some direct messages or hop on a call with me anytime.

**Comment by 0x4007** [comment]
Hey @hashedMae I'm following up on this

**Comment by hashedMae** [comment]
@pavlovcik 

sorry, thought I'd posted the doc a few days ago
https://docs.google.com/document/d/1dpHHhJLQGlZCWOaHiDxnwGaTdl6OE192h4gDy--2lgQ/edit?usp=sharing

**Comment by 0x4007** [comment]
Thank you! So is the verdict that everything checks out to accommodate our spec?

**Comment by hashedMae** [comment]
It'll work but I don't think it's the best fit

**Comment by 0x4007** [comment]
Thanks a ton for the research. You think perhaps it makes more sense to archive on Discussions and then link from here?

Just in case if you unshare or delete the google doc?

Also if you can post your DAI address I will send. I'll take a deeper look at your report later and might drop some comments for some questions in the doc.

**Comment by 0x4007** [comment]
Hey @hashedMae can you elaborate on 

> It'll work but I don't think it's the best fit

I want to share the issues with their team for why it is not the best fit.

**Comment by hashedMae** [comment]
We're wanting to buy LP tokens but these are made more so to buy stable coins. So it can work for our use case but it wasn't designed for it.

**Comment by hashedMae** [comment]
0x7fe65D99a0998Cdba8e1f749303a467dcf87e815

**Comment by hashedMae** [comment]
> Thanks a ton for the research. You think perhaps it makes more sense to archive on Discussions and then link from here?
> 
> Just in case if you unshare or delete the google doc?
>

done https://github.com/ubiquity/ubiquity-dollar/discussions/345

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0x7671e749c475bb476515bbac8aecdc60b5356ec9db7cdab44509b34f58c4540a
