### ISSUE TITLE
Add a bot to post updates to topic in telegram

### ISSUE THREAD

**Issue by 3commascapital** [pavlovcik/uad-ui#320]
there should be a topic or channel that can receive updates whenever an issue is created or a pull request is created or updated to allow devs to only have to go to one place to get all the updates they need

**Comment by 0x4007** [comment]
Suggestions to improve the Bounty Program can be recorded in the below discussion. I prefer not to use "issues" for these.

I also recently suggested something similar:

https://github.com/ubiquity/ubiquity-dollar/discussions/184#discussioncomment-3831628
