### ISSUE TITLE
Tether Balance Not Rendering Correctly in Inventory

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#323]
For once I have a Tether balance and noticed that its rendering as `0 USDT` in the Inventory even though I have exactly `1000 USDT`

<img width="914" alt="image" src="https://user-images.githubusercontent.com/4975670/201635483-30a7e254-99be-45e2-b581-a9bbf9b83fb1.png">

<img width="619" alt="image" src="https://user-images.githubusercontent.com/4975670/201635642-59e77397-d207-4003-a229-c66c8bd274c4.png">

**Comment by ryzhak** [comment]
pls check https://github.com/ubiquity/ubiquity-dollar/pull/324

**Comment by 0x4007** [comment]
@ryzhak You need to request to take a bounty before you authorized to solve it. You're taking on an unnecessary risk if somebody else is assigned the bounty while you're working on it because then you will not be credited for your work. 

Fortunately nobody else tried solving it at the same time!

It looks like your solution is valid so please confirm your wallet address and you will receive full payment! Looks like I forgot to include the price but the following labels should tally up to $100 USDC 

[Profit: <10%](https://github.com/ubiquity/ubiquity-dollar/labels/Profit%3A%20%3C10%25)

[Time: <1 Day](https://github.com/ubiquity/ubiquity-dollar/labels/Time%3A%20%3C1%20Day)

**Comment by ryzhak** [comment]
@pavlovcik 

ok, got it

wallet: https://etherscan.io/address/0x165343c045a00770b61DbCa01956590cC6005666

**Comment by ryzhak** [comment]
@pavlovcik 

> It looks like your solution is valid so please confirm your wallet address and you will receive full payment! Looks like I forgot to include the price but the following labels should tally up to $100 USDC

sorry to bother, still waiting for this one

**Comment by 0x4007** [comment]
Thanks for the reminder! Sorry for the delay. 

https://etherscan.io/tx/0x3d470dc278634982bb2e79db30ff527e20acda3c8a1e1a66e27c094f024c7856
https://etherscan.io/tx/0x0f1a1e5e68b880f7cbe7b1bfcb7833acd1444b3958d14c6e8f6e3f4ca747d648
