### ISSUE TITLE
Scrollbars on Inventory on Windows OS

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#326]
Sent from a friend

![image](https://user-images.githubusercontent.com/4975670/202064918-2bdb9d40-040c-4e2a-a99e-72a7412d5b5b.png)

**Comment by ryzhak** [comment]
@pavlovcik 

I can take this one

**Comment by Draeieg** [comment]
no more nasty bars and scroll still works
![image](https://user-images.githubusercontent.com/88983138/202601905-775a2283-0045-48e0-91f5-d24df89ebe23.png)

**Comment by 0x4007** [comment]
I asked @Draeieg in the direct messages to help me verify this. It looks like it works but I would love the opportunity to more thoroughly test.

@ryzhak looks like it works. Please post your DAI address again here? We will automate this payment process in the future but still need more time to set it all up. Thank you!

**Comment by ryzhak** [comment]
@pavlovcik 

good

wallet: https://etherscan.io/address/0x165343c045a00770b61DbCa01956590cC6005666

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0x3bce500713491ce7402ad98ca68e301163957f27ea6abd4be9c1dd42e1c2fd54
https://etherscan.io/tx/0xbeb522cfcb3124816d1f32e009dabcdbf5a75ebd50f2eea5d2919f2bc3f3f6ed
