### ISSUE TITLE
Setup `yarn audit`

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#342]
@0xcodercrane would you mind helping me research and determine if CodeQL and `yarn audit` make sense to add to our security CI before we create this bounty?

> - Also a built in [yarn audit](https://github.com/MetaMask/metamask-extension/blob/develop/.circleci/scripts/yarn-audit.sh) seems like a good idea.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/discussions/197#discussioncomment-3641178_

**Comment by cuddle-dev** [comment]
Let me help you with that

**Comment by FibrinLab** [comment]
I already setup yarn audit in another closed issue. I think this can be closed also.

**Comment by 0x4007** [comment]
> I already setup yarn audit in another closed issue. I think this can be closed also.

Can you link the closed issue/commit here?

**Comment by FibrinLab** [comment]
> > I already setup yarn audit in another closed issue. I think this can be closed also.
> 
> Can you link the closed issue/commit here?

Here you go https://github.com/ubiquity/ubiquity-dollar/issues/411

**Comment by 0x4007** [comment]
I'm surprised I created an almost perfectly duplicated issue.
