### ISSUE TITLE
Claim Rewards Failure (When Have Multiple Stakes)

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#346]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/4975670/204081153-e793454c-0139-4ba3-8119-643345a384e9.png">

I have two different staking positions and I have always tried to claim both at the same time but noticed some issues.

1. I can always claim the first one (either one of the two) and while the transaction is pending, the UI ignores my request to claim the second. I don't believe an error is thrown on the UI for this either.

2. Once the first transaction [is completed](https://etherscan.io/tx/0xc80bc3c828979b57c5557c286f3f1ee6769cad36834d16dfdd9165883582813b), I attempted to claim the second stake. The UI registers my attempt, but incorrectly estimates the gas limit, leading to a [failed transaction](https://etherscan.io/tx/0x84cb59fee4ce6fa6f23044e5cd2ca0ad3d4d94d1e399f4a9d0653e950994e7b8). 

After it failed, I tried refreshing the page and claiming again, and it seems to [have worked](https://etherscan.io/tx/0x914323b2256532e14ed1368cd70c6390f3be6589449fa07a934913673ec86a43).

---

I would like for the UI to allow me to:
1. Claim both at the same time 
  a. Ideally just fix the bug where I can't claim the second one while the first one is pending.
2. I would like to have the gas limit estimate hardcoded (assuming that this is a viable strategy) so that we don't have this issue anymore.

**Comment by acaldas** [comment]
@pavlovcik Can I take this one?

I see 3 improvements:

- Allow multiple claims to be requested at the same
- Add feedback of when the claim button is not clickable (while the transaction is being processed)
- Add a "claim all" button that sends a transaction for each claim. I believe the smart contract doesn't support claiming all in one transaction?

**Comment by 0x4007** [comment]
> * Allow multiple claims to be requested at the same

Yes, ideally.

> * Add feedback of when the claim button is not clickable (while the transaction is being processed)

Yes. Once a button is clicked, the button should be disabled (I don't recall if the UI is currently implemented this way.)

> * Add a "claim all" button that sends a transaction for each claim. I believe the smart contract doesn't support claiming all in one transaction?

Would be awesome but requires that the smart contract can process this in a single transaction. Otherwise we should just let the user manually press claim to invoke separate transactions.

---

Lastly, we should consider a solution like hardcoding the gas limit or else the gas estimation problem may occur again.

**Comment by 0x4007** [comment]
Hey @acaldas sorry for the delays again. What is your wallet address?

**Comment by acaldas** [comment]
Here it is: 0x9F7F0721335dd004D3e848Fd1202264603Bb7397

**Comment by 0x4007** [comment]
> Here it is: 0x9F7F0721335dd004D3e848Fd1202264603Bb7397

https://etherscan.io/tx/0xe5f8616146cdff8c99d4ca5985e79a0649bb991f3c51b8bc8deefe7b7b3c4a8a
https://etherscan.io/tx/0xe1827e13ebc4baa3a3c3c8ed4ccc8918795221906b1e5d6573647bbf90f1c16c
