### ISSUE TITLE
Refactor UI to Interface With Updated Contract Method Names

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#354]
Requires https://github.com/ubiquity/ubiquity-dollar/pull/351 to be merged in before this can be released to the DevPool.

> Frontend should be completely broken after these changes (need a task to fix it)

**Comment by acaldas** [comment]
@pavlovcik Can I take this one?
It's blocking other UI issues like my PR: https://github.com/ubiquity/ubiquity-dollar/pull/366

I see that `typechain` is listed as a dependency but the contract types are not being used in the UI.
I'd like to set that up and then do the refactor.

**Comment by Keyrxng** [comment]
had just started working on this one as my first, would like to take it as well

**Comment by sergfeldman** [comment]
@acaldas Usually we give 1 bounty at a time to 1 developer so as not to block other developers.

@Keyrxng According to the rules, before starting a bounty, you should request it in the comments and get approval.

**Comment by sergfeldman** [comment]
@acaldas @Keyrxng Please put down your deadlines for completing this issue.

**Comment by acaldas** [comment]
@sergfeldman I'm aware of the 1 bounty limiy, but since this issue is blocking every UI bounty I wanted to unblock it.
I should be able deliver this in the next 1/2 days.

**Comment by sergfeldman** [comment]
Since there is no answer from @Keyrxng the bounty is assigned on @acaldas

**Comment by 0x4007** [comment]
@acaldas I just redid this but will still pay out the bounty. What's your address?

**Comment by acaldas** [comment]
> @acaldas I just redid this but will still pay out the bounty. What's your address?

Hey, that's great, thanks!

Here it is: 0x9F7F0721335dd004D3e848Fd1202264603Bb7397

**Comment by 0x4007** [comment]
> Here it is: 0x9F7F0721335dd004D3e848Fd1202264603Bb7397

https://etherscan.io/tx/0x7d6fe1f73d11ece7f747ed010ce93ebe2378b05879ee7c1af38dcaa449a7de57
https://etherscan.io/tx/0x4fa0368ea7274781ea91c505129904cba1575881dbb9bea4d5077079a658d1c4
