### ISSUE TITLE
Fix Yarn Workspace Warnings

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#355]
Context: https://github.com/ubiquity/ubiquity-dollar/pull/258

Creating an issue so that we don't forget about this. 

This is not intended to be released to the DevPool, but rather, handled by trusted devs. The reason why is that I think the core devs should handle this is because it may require us to remove/replace core dependencies. I think the core devs will have better judgement on this. Open to the idea of releasing into the DevPool in the future if that is a non issue.

**Comment by Steveantor** [comment]
Would like to work on this #258

**Comment by sergfeldman** [comment]
> Would like to work on this #258

@Steveantor This issue is supposed to be done by the core team.
Let's wait for the confirmation from @pavlovcik

**Comment by 0x4007** [comment]
My mistake I moved all the stale issues to bounties but @sergfeldman is correct so I'll rectify.

**Comment by 0x4007** [comment]
Guess I'll use devpool as the placeholder for core team (for now)

**Comment by Steveantor** [comment]
> Guess I'll use devpool as the placeholder for core team (for now)

If you rename it to Ubiquity-Core (to avoid confusions)

**Comment by 0x4007** [comment]
> > Guess I'll use devpool as the placeholder for core team (for now)
> 
> 
> 
> If you rename it to Ubiquity-Core (to avoid confusions)
> 
> 

That's a good idea I'll have to address when I'm back on my computer!

**Comment by laryhills** [comment]
I would love to address this issue @pavlovcik

**Comment by 0x4007** [comment]
> I would love to address this issue @pavlovcik

Sorry but this issue is not available to new bounty hunters because the results are quite a bit subjective (I'm skeptical that 100% of the warnings will be solved.) However, @Steveantor given your proven track record (5+ bounties closed) I would be happy to offer you this bounty.

**Comment by Steveantor** [comment]
PR #468

**Comment by 0x4007** [comment]
It was real messy to try and fix the `yarn.lock` merge conflicts. I am surprised that it is so complicated to fix. Hopefully I didn't break something else while trying to resolve that. 

Please share your wallet address!

**Comment by Steveantor** [comment]
> It was real messy to try and fix the `yarn.lock` merge conflicts. I am surprised that it is so complicated to fix. Hopefully I didn't break something else while trying to resolve that.
> 
> Please share your wallet address!

yeah, yarn.lock is messy in itself, to begin with
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by 0x4007** [comment]
> > It was real messy to try and fix the `yarn.lock` merge conflicts. I am surprised that it is so complicated to fix. Hopefully I didn't break something else while trying to resolve that.
> > Please share your wallet address!
> 
> yeah, yarn.lock is messy in itself, to begin with Here's my address: `0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE` @pavlovcik

I hope that I can simply "rebuild" the lock file as this continues to happen.

https://etherscan.io/tx/0xafb7c73f364b851f1a008bdf5a2a34d0f32466e3cea9aea2e5edb6256c99336b
https://etherscan.io/tx/0x497fdf41c5e232065b958bfb8b7517df4d7fb46283d1fa7f9c53463e2ae6a83d
