### ISSUE TITLE
Auto "Approve and run"

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#362]
@0xcodercrane another instance of "Approve and run" can you do some research to resolve this issue?

<img width="1072" alt="Screenshot 2022-12-07 at 04 31 52" src="https://user-images.githubusercontent.com/4975670/206016661-97890bee-fdf8-4a5f-b4a4-2daabde03b7f.png">

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/361#issuecomment-1339971838_

**Comment by cuddle-dev** [comment]
Ok will kick off this stuff

**Comment by 0x4007** [comment]
Thank you ser.

**Comment by 0x4007** [comment]
I invited @rndquu because it seems to disproportionately affect their PRs. I don't think this bounty should take very long to understand why its happening and to get a solution.

**Comment by 0x4007** [comment]
<img width="801" alt="image" src="https://user-images.githubusercontent.com/4975670/206895974-f5809152-0503-4bfd-9966-4225de2668bc.png">

New GitHub accounts and first-time contributor = manual CI runs. This shouldn't be an issue after one of @rndquu's PRs are merged I think.

https://github.com/ubiquity/ubiquity-dollar/settings/actions
