### ISSUE TITLE
Foundry Tests "Panic" Crashing

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#363]
Several tests this evening have crashed. Could somebody do some research on resolving this?

```
Run yarn test:all
➤ YN0000: No files changed, compilation skipped
➤ YN0000: The application panicked (crashed).
➤ YN0000: Message:  Unable to create fork: 
➤ YN0000: Could not instantiate forked environment with fork url: https://rpc.ankr.com/eth
➤ YN0000: Location: evm/src/executor/backend/mod.rs:[4](https://github.com/ubiquity/ubiquity-dollar/actions/runs/3622649352/jobs/6107615296#step:10:5)09
➤ YN0000: 
➤ YN0000: This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
➤ YN0000: 
➤ YN0000: Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
➤ YN0000: Run with RUST_BACKTRACE=full to include source snippets.
➤ YN0000: Done in 3s 63[5](https://github.com/ubiquity/ubiquity-dollar/actions/runs/3622649352/jobs/6107615296#step:10:6)ms
Error: Process completed with exit code 1.
```

<img width="739" alt="image" src="https://user-images.githubusercontent.com/4975670/206020025-553e6d6c-fb03-47fc-bff7-df4b1cd705a2.png">

https://github.com/ubiquity/ubiquity-dollar/actions/runs/3622649352/jobs/6107615296

**Comment by zgorizzo69** [comment]
honestly it seems that for some reason the anker endpoint was failing aybe we can add a task to try calling the endpoint before testing and if it is not responding fallback to another endpoint

**Comment by zgorizzo69** [comment]
I also had a test failing with ` Could not instantiate forked environment with fork url: https://cloudflare-eth.com/`

**Comment by 0x4007** [comment]
I think we should copy what other big Foundry based projects do before reinventing the wheel.

**Comment by Steveantor** [comment]
#383  addresses this issue.

**Comment by 0x4007** [comment]
> #383 addresses this issue.

Technically you are supposed to request to take the bounty in case any others front-run you. Fortunately nobody else attempted this at the same time so there are no issues! 

What is your DAI payment wallet address?

**Comment by Steveantor** [comment]
> > #383 addresses this issue.
> 
> Technically you are supposed to request to take the bounty in case any others front-run you. Fortunately nobody else attempted this at the same time so there are no issues!
> 
> What is your DAI payment wallet address?

yeah, that's for sure,
here's my address: `0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0x21c783a7e371962cbc9233bca0392a4ec112259b5b63ab5fe0a3a77f62e29b5a
https://etherscan.io/tx/0xbb470f837edf59df303353d4f5f243d4ebd7d1b27a7cae6fa6f9f457afd4875a
