### ISSUE TITLE
improve DirectGovernanceFarmer to handle apeIn with four tokens

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#370]
the deposit function only takes one token but we want people to be able to apeIn with up to four tokens instead of 
signing up to four transactions (deposit with uAD + deposit with USDC +deposit with DAI + deposit with USDT )

the goal is to add a deposit function that takes up to 4 tokens

**Comment by zgorizzo69** [comment]
@pavlovcik feel free to add whatever labels are needed estimation is between 1 to 3 hours

**Comment by sergfeldman** [comment]
@zgorizzo69 https://etherscan.io/tx/0xa2f132921acab6efcb71b3859b03b1c4150704d792a46cf6258dddf4397dfa10

**Comment by 0x4007** [comment]
> @zgorizzo69 https://etherscan.io/tx/0xa2f132921acab6efcb71b3859b03b1c4150704d792a46cf6258dddf4397dfa10

Same as our other discussions.

**Comment by zgorizzo69** [comment]
> > @zgorizzo69 https://etherscan.io/tx/0xa2f132921acab6efcb71b3859b03b1c4150704d792a46cf6258dddf4397dfa10
> 
> Same as our other discussions.

This has been reviewed by @hashedMae  and should be merge IMO the thing is @0xcodercrane has been assigned as a reviewer but he is quite busy. Can I merge when there is at least one review or should I wait two @pavlovcik ?

**Comment by 0x4007** [comment]
Should be fine to merge as long as it passes the security checks. It looks like you were going to add the ability to withdraw in multiple tokens but I don't believe that has been implemented. I did some small renames to conform to the new code naming conventions (don't use our token symbols to increase clarity for new developers.)

I enabled auto-merge so you should be able to handle the rest from here.

> no need to add a withdraw function though

Why is this part of your spec to not allow for withdrawals?

**Comment by zgorizzo69** [comment]
Withdraw with multiple token is part of the specs (also present in the pr)

**Comment by 0x4007** [comment]
> Withdraw with multiple token is part of the specs (also present in the pr)

It looks like this statement conflicts with 

> no need to add a withdraw function though

if we call your first comment in this conversation the spec.

Anyways, I enabled auto-merge so take a look at the PR conversation and you should be able to complete this when you're ready.
