### ISSUE TITLE
Scrollbars on Inventory on Windows OS, Issue Back

### ISSUE THREAD

**Issue by RyeBergg** [pavlovcik/uad-ui#373]
![image](https://user-images.githubusercontent.com/120143927/206590129-f743ef84-daf8-448f-938c-2d4ea8351fa1.png)

Windows OS, Google Chrome. Scroll bars seem to be back?
Seemed like you fixed in #326 prior.

Ran a forced browser recache, ctrl f5, still there.

**Comment by 0x4007** [comment]
We are having hangups merging `development` to `main` please try on the following commit deploy:

https://6374e145d192e208c34ec0fb--ubiquity-dollar.netlify.app/

If it is gone there, that means that we will eventually merge to `main` and it will be gone!

Please let me know if it is still present on the commit deploy link.

**Comment by RyeBergg** [comment]
Looks resolved. My bad, assumed it would have been merged into production already.
