### ISSUE TITLE
`Staking` & `UbiquityChef` Contract Slither Issue

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#381]
> There's three slither issues coming up still. Two are both cause _deposit calls _updatePools and the contstructor calls _deposit inside a loop. It's not possible to resolve this without a massive refactor of BondingV2 and MasterChefV2
Third is cause I replaced transfer with call for sending Ether, this is the current best practice.

Originally posted by @hashedMae in https://github.com/ubiquity/ubiquity-dollar/commit/5d004fa7cfa9cf259fb67d17d52d439bac61f15e#commitcomment-92608369

**Comment by hashedMae** [comment]
I resolved these in #284 
Comment was intended as a progress update

**Comment by hashedMae** [comment]
@pavlovcik @0xcodercrane Okay to mark this as closed?

**Comment by cuddle-dev** [comment]
yes
