### ISSUE TITLE
"Push to Start" to Connect Wallet

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#385]
We should take the same code from the [home/landing page](https://ubq.fi) and have it replace the "please connect your wallet" message.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/4975670/206906707-0c3b6e83-c025-4555-92a8-82c8dc777755.png">

Landing page "push to start"

<img width="436" alt="image" src="https://user-images.githubusercontent.com/4975670/206906700-d8010abd-60ec-4d03-93b1-9199e17fdeb1.png">

Current "please connect your wallet"

---

- [ ] Include the sound effect
- [ ] Only play sound effect and the animation of expansion when user successfully connects their wallet.
- [ ] Unsuccessful connect should play a different sound which I can personally compose later. For now, try any placeholder using the same sound API.
- [ ] Hide existing "Connect Wallet" button to instead have the user press this button to connect. (`visibility: invisible` should be sufficient for this bounty)
- [ ] When the user is "logged in" aka connected their wallet, the original disconnect button should be visible. 
- [ ] If the user invokes the disconnect button, the view for this should return to the beginning state (as it does when the user first loads the dApp.

**Comment by 0x4007** [comment]
Because design is pretty subjective, I think it should be expected that I'll hop in and tweak before we merge. The main objective tasks are in the checklist above though!

**Comment by mul1sh** [comment]
> We should take the same code from the [home/landing page](https://ubq.fi) and have it replace the "please connect your wallet" message.
> 
> <img alt="image" width="403" src="https://user-images.githubusercontent.com/4975670/206906707-0c3b6e83-c025-4555-92a8-82c8dc777755.png">
> 
> Landing page "push to start"
> 
> <img alt="image" width="436" src="https://user-images.githubusercontent.com/4975670/206906700-d8010abd-60ec-4d03-93b1-9199e17fdeb1.png">
> 
> Current "please connect your wallet"
> 
> * [ ]  Include the sound effect
> * [ ]  Only play sound effect and the animation of expansion when user successfully connects their wallet.
> * [ ]  Unsuccessful connect should play a different sound which I can personally compose later. For now, try any placeholder using the same sound API.
> * [ ]  Hide existing "Connect Wallet" button to instead have the user press this button to connect. (`visibility: invisible` should be sufficient for this bounty)
> * [ ]  When the user is "logged in" aka connected their wallet, the original disconnect button should be visible.
> * [ ]  If the user invokes the disconnect button, the view for this should return to the beginning state (as it does when the user first loads the dApp.

Looks interesting, I can get this done later today

**Comment by mul1sh** [comment]
I'll  take a quick look at the existing code, go through over it in an hour or so to understand it and then quickly implement the feature as required.

**Comment by 0x4007** [comment]
Make sure to inspect https://github.com/ubiquity/ubq.fi

**Comment by mul1sh** [comment]
@pavlovcik sorry been a bit caught this week, will sort this tomorrow asap!!

**Comment by jasonmilad** [comment]
Taking a look at this right now, should have it ready by the end of the day.

**Comment by 0x4007** [comment]
How's it coming along?

**Comment by mul1sh** [comment]
> How's it coming along?

On it now, sorry been a crazy week 😬

**Comment by mul1sh** [comment]
@pavlovcik sorry but the holiday threw me off abit 😅 but kindly give me till this coming Friday, I'll get this done.

**Comment by 0x4007** [comment]
This bounty was estimated to take 1 day but it has been 3 weeks since you claimed the bounty. Unfortunately we will need to release this back into the DevPool.

**Comment by kgelpes** [comment]
Hi, is this issue still open? I'd like take it, looks straightforward

**Comment by 0x4007** [comment]
Hey @kgelpes great work! Looks like you're quite talented with UI/UX. Hope to see more of your contributions soon! Please share your wallet address to receive DAI and UBQ tokens!

**Comment by kgelpes** [comment]
> Hey @kgelpes great work! Looks like you're quite talented with UI/UX. Hope to see more of your contributions soon! Please share your wallet address to receive DAI and UBQ tokens!

@pavlovcik Thank you! If there's any UI/UX related task available I'll take it.
My address is `0kevin.eth`

**Comment by 0x4007** [comment]
> @pavlovcik Thank you! If there's any UI/UX related task available I'll take it. My address is `0kevin.eth`

Ok dope I'll definitely keep it in mind! If you have proposals/suggestions for specific improvements, please feel free to write a specification/bounty as a GitHub issue. If we like it, then we have a standardized pricing model based on the time estimate to complete and priority of the task, and we'll be able to fund it if you carry it out after we confirm pricing.

https://etherscan.io/tx/0xb1791696cad48b36045aad9a5d0c19c2fcf21b23715592d94e6df7cd50836075
https://etherscan.io/tx/0x6882b1f55c8c6d136656803858ee10fc8c99414962e3fb970ff20ad9d1791ec7
