### ISSUE TITLE
Test issue for bounty bot

### ISSUE THREAD

**Issue by cuddle-dev** [pavlovcik/uad-ui#392]

**Comment by ghost** [comment]
any detailed description on the issue?

**Comment by 0x4007** [comment]
> any detailed description on the issue?

The only issues that are available for bounty hunters are the ones assigned to @ubiquity-bounties. This is a test issue for internal automation.

**Comment by ghost** [comment]
Oke, thanks!
So could you assign a issue for me?

**Comment by 0x4007** [comment]
No. Bounty hunters must choose their own bounties. You can find the program guidelines here.

https://dao.ubq.fi/devpool-flow

**Comment by cuddle-dev** [comment]
cute!

**Comment by rndquu** [comment]
closing this because we have a [QA organization](https://github.com/ubiquibot) for such kind of test issues
