### ISSUE TITLE
Move all core contracts to the diamond

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#394]
- [ ] convert and add as a facet all contracts inside core directory make sure docstrings are present
- [ ] refactor UADManager and create another lib with a different storage slot and only keeps really cross facet state inside app storage
- [ ] add more tests (especially for upgrades) 
- [ ] updated upgrade script
- [ ] Deploy and test on goerli network in use of new deploy script.
- [ ] instructions and high level architecture in readme.md for deploy and upgrade script.

**Comment by zgorizzo69** [comment]
so a little note on the estimation 
for each one of the core contract I have to 
+ create a new library for its storage may also plug it also to the app storage 
+ remove all constructor code to add it either to a set function and/or inside the diamond init   
+ modify function visibility to internal when possible 
+ make sure to apply the needed modifers 
+ modify all the tests

**Comment by zgorizzo69** [comment]
a lot of external contract will now be part of the diamond so I also have to change a lot of functions. for instance I will have to remove the dollarAddress from functions that takes it as a paramter as this will be address(this) and so the logic might change a bit

**Comment by 0x4007** [comment]
Sorry for playing with the bot on this issue. This is satisfying to see the pricing working as envisioned.

**Comment by davidpius95** [comment]
@pavlovcik  If this Issue is still open I will love to work on it by using the Diamond-3 Template

**Comment by sergfeldman** [comment]
> @pavlovcik If this Issue is still open I will love to work on it by using the Diamond-3 Template

@davidpius95 This issue is already assigned. 
Please, select another bounty.

**Comment by sergfeldman** [comment]
@zgorizzo69 Please, post your DAI address here.

@pavlovcik Please, pay for this bounty if it is accepted.

**Comment by zgorizzo69** [comment]
0x10693e86f2e7151B3010469E33b6C1C2dA8887d6

**Comment by 0x4007** [comment]
> 0x10693e86f2e7151B3010469E33b6C1C2dA8887d6

https://etherscan.io/tx/0x8fbcac025841eb7ff29554e43ac8417e5e3512d03fd8734d71b057426778bfff
