### ISSUE TITLE
Create Archival Repository for deprecated V1 Contracts

### ISSUE THREAD

**Issue by hashedMae** [pavlovcik/uad-ui#399]
In an effort to avoid confusion we have been removing deprecated contracts from the active repository as they're replaced. 
This has caused some issues when there's a need to reference these contracts for research or investigation purposes as we've had to go and then find them on Etherscan or elsewhere. 
I propose to create an archival repository for the V1 contracts as they were originally deployed. This will create a consistent reference point that can be installed as a library for any future needs. 
It is my recommendation that the same be done with the current production environment should it ever be replaced.

**Comment by 0x4007** [comment]
https://github.com/ubiquity/uad-contracts

However, we are able to reference code that existed on a specific commit so for the specific scenario you presented I don't understand why it is an issue to use this @ubiquity/ubiquity-dollar repo
