### ISSUE TITLE
`uCR-NFT` ⮕ `uCR` Conversion

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#400]
Allow users to convert Ubiquity Credit NFTs to Ubiquity Credits (fungible).

Depends on #115 (we need to know the redemption rate of `1 uCR` for `? uAD` as it has less redemption power over time)

## Background

- We know that uCR-NFT is always worth 1 uAD
- We know how much uAD is 1 uCR worth at any given point in time
  - Depends on #115
- We know what duration of the uCR-NFT remains in percentage

## Math
 
 ```
(1 uCR-NFT) * (Remaining duration %) * (uCR/uAD conversion rate)
```

> Example:
> 
> 10 000 uCR-NFT with a total duration of 6 months has been around for 4 months, so they have 33% duration remaining.
> uCR/uAD redemption rate is 1.5
> So the user can get: 10 000 * 33% * 1.5 = 4 950 uCR (which is currently worth 3300 uAD)

_Originally posted by @hpiyankov in https://github.com/ubiquity/ubiquity-dollar/issues/105#issuecomment-1115346883_
      
## Note

In #112 it is emphasized where to implement this function

> Right now if you convert uCR-NFT to uCR with the CreditManager you get a 1-1 conversion, no > mater how close the uCR-NFT token is to expiring. While if expired does not allow you to > convert at all.
> 
> The relevant function is burnCreditNftsForCredits
> 
> What needs to happen
> Using the CreditClock we should consider the price of the uAD-uAD-equivalent of the uCR-NFT > amount (right now it converts 1-1) (this means dividing it by the CreditClock > creditRateAtBlockNumber, the result should be a higher amount of uCR (because it's devalued))
> At mint time the conversion should be 100%
> At expiration time the conversion should be 0%
> In between we lower it linearly using the expiration time

**Comment by ethernomad** [comment]
I'm ready to work on this - can it be assigned to me?

I previously completed #115.
