### ISSUE TITLE
`uAD` ⮕ `uCR` Conversion

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#401]
Allow users to convert Ubiquity Dollars to Ubiquity Credits (fungible).

Depends on #115

## Background

uCR also needs a premium for burning uAD, otherwise, it makes no sense.
- [ ] requires `premium` variable 

uCR uses the same formula for premium as uCR-NFT, however it gets only 70% of the premium (configurable)
- [ ] requires `offset` variable 

The depreciation rate of uAD is defined in such a way, that at the time of uCR-NFT expiration, uCR is worth 70% (configurable via setting the rate - R) of its original value. 
- [ ] requires `rate` variable #115

## Math Overview

For example: if the expiration duration is 30 days, then we can define the needed rate  - R for the period as:

```
(1+R)^(blocks) = 1/0.7
```

If we assume 1 block per 12 seconds, in 30 days we get 216 000 blocks

Then: 

```
(1+R) ^216000 = 1.4286
R =  0.000001651366844
```

The ratio of uAD/uCR starts at 1 and we define an inflation rate (the one which we derived above, for example). Then the ratio of the uAD/AR changes with each block according to the formula:

```
(1+R)^(elapsed blocks)
```

Important: R should be configurable for a given period. E.g. we should be able to change R, without this affecting negatively already existing uCR. 

If we assume a block time of 12 seconds, this gives us the following ratio per day:

## Math Examples

So let’s look at an example:
User A wants to burn 1000 uAD on day 1. The current ratio is 1:1 and we offer him 30% premium (for example). He gets 1000 * 1 * 1.3 = 1300 uCR
On day 15 debt cycle ends, the mint cycle begins
On day 16 the ratio is 1.19. If the user redeems his 1300 uCR at this point, he would get 1300/1.19 = 1092 uAD
On day 31 the ratio is 1.42. If the user redeems his 1300 uCR at this point, he would get 1300/1.42 = 915 uAD

Example2:
The debt cycle has started on day 5, at a ratio of 1.048 (irrelevant for further calculations, just here to show that the 1:1 ratio is a fixed point in time and not associated with cycles)
User B wants to burn 1000 uAD on day 10. The current ratio is 1:1.11 and we offer him a premium of (10%, since we are later in the debt cycle). He would then get: 1000 * 1.1 * 1.1 = 1210 uCR
On day 31, the debt cycle ends, we mint and the user redeems his funds at a ratio of  1.42. He would get back 1210 / 1.42 = 852 uAD

_Originally posted by @hpiyankov in https://github.com/ubiquity/ubiquity-dollar/issues/116#issuecomment-1115352490_
    
## Appendix

https://docs.google.com/document/d/12gGDjRw4s1TRH4mT9v3yb_TFnFDKfzKgTjTfIKtoAMM/edit

**Comment by FibrinLab** [comment]
@pavlovcik Is this still part of the loot box issue? The bonding curve forked from bancor could be modified for this.

**Comment by 0x4007** [comment]
This is not to be implemented as a bonding curve. It's a contract that allows users to burn their Ubiquity Dollars for Ubiquity Credits when we are below peg in order to reduce the supply of the Ubiquity Dollars.

**Comment by molecula451** [comment]
i think we have refactored a lot for this tasks to be meet? re-open if am wrong on this one @rndquu @gitcoindev
