### ISSUE TITLE
Setup LavaMoat

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#409]
> I accidentally disabled [lavamoat](https://github.com/LavaMoat/LavaMoat) on the core dollar contracts at some point while converting this into a monorepo. We should definitely re-add to the whole project.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/discussions/197#discussioncomment-3641178_

**Comment by FibrinLab** [comment]
Would like to give this a go. Can you assign this to me?

**Comment by FibrinLab** [comment]
0x43BbdE754e2e4e8A3b1282D1037Ce1a1B7c577C2

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0x9c9f9b910d8a5cb2a45ab96aeab52ae0194d955d2cfd3fe4194fcbfbb6bebe5e

https://etherscan.io/tx/0x8d28bf901c6a11d238ae490a04d144bb6452049e2d718c1943d6b3b5f315a3bd

Thank you for your work! Will merge when I overcome this GitHub authentication issue.

**Comment by FibrinLab** [comment]
@pavlovcik I enjoy working on Ubiquity
