### ISSUE TITLE
Setup CodeQL

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#410]
> - Turns out its a MetaMask product, which prompted me to check out their CI and looks like they have a ton more scripts to consider! [CodeQL](https://github.com/MetaMask/metamask-extension/actions/workflows/codeql-analysis.yml) looks interesting.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/discussions/197#discussioncomment-3641178_

**Comment by FibrinLab** [comment]
While waiting for the Bonding curve Formular, I could set this up in a few hours. Can I get assigned this?

**Comment by ubiquity-bounties** [comment]
What is your wallet address @FibrinLab ?

**Comment by FibrinLab** [comment]
0x43BbdE754e2e4e8A3b1282D1037Ce1a1B7c577C2

**Comment by 0x4007** [comment]
> 0x43BbdE754e2e4e8A3b1282D1037Ce1a1B7c577C2

https://etherscan.io/tx/0x9940529a185f9eda0181925e99e5f440ba9deebfee36a57aa1983ec266a61784
https://etherscan.io/tx/0xe6a8816af059a88789dbf490c24b32d23d2a6029aa88ee3ba4184d5cc1c99d77
