### ISSUE TITLE
Setup `yarn audit`

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#411]
> - Also a built in [yarn audit](https://github.com/MetaMask/metamask-extension/blob/develop/.circleci/scripts/yarn-audit.sh) seems like a good idea.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/discussions/197#discussioncomment-3641178_

**Comment by FibrinLab** [comment]
Hello. Can I get this issue assigned to me

**Comment by FibrinLab** [comment]
Hello. I just made a pull request. Created a github workflow that runs and audit script

**Comment by 0x4007** [comment]
Please post your payment address here. Thanks!

**Comment by FibrinLab** [comment]
0x43BbdE754e2e4e8A3b1282D1037Ce1a1B7c577C2

**Comment by 0x4007** [comment]
Hey I just want to confirm if receiving DAI is ok at this address?

**Comment by FibrinLab** [comment]
Yes it can. It's MetaMask

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0x41355a9a7467dbdd5fabdda69cd0b6dfe77e22abef3266c8e7a4af743cf1737b
https://etherscan.io/tx/0x1f619d30e81a3f7e674d4b818f9bfa529cd982639dfef7313b3b48bc980461f3

Congrats!
