### ISSUE TITLE
Don't want to have unit tests named `testFail`

### ISSUE THREAD

**Issue by cuddle-dev** [pavlovcik/uad-ui#414]
## Problem

There are a few unit tests names `testFail*` which means it passes even though it fails. we need to remove `Fail` from those functions

**Comment by zorglob21** [comment]
So we need to check every testFail function and rename those that are problematic or rename all of the functions?

**Comment by cuddle-dev** [comment]
> So we need to check every testFail function and rename those that are problematic or rename all of the functions?

right

**Comment by rndquu** [comment]
may I take this one?

**Comment by sergfeldman** [comment]
@rndquu I see that PR was linked and unlinked.

@pavlovcik @0xcodercrane Whether this issue is actual?

**Comment by 0x4007** [comment]
> @rndquu I see that PR was linked and unlinked.
> 
> @pavlovcik @0xcodercrane Whether this issue is actual?

Perhaps there was a deleted comment because I don't see what you're quoting.

**Comment by 0x4007** [comment]
@rndquu please share your wallet address here

**Comment by rndquu** [comment]
> @rndquu please share your wallet address here

0x336C033842FA316d470e820c81b742e62A0765DC

**Comment by 0x4007** [comment]
> > @rndquu please share your wallet address here
> 
> 0x336C033842FA316d470e820c81b742e62A0765DC

https://etherscan.io/tx/0xddbf6b4244ba2330780e5d3179fcbcf815421c57ed511ba7440922e91c94312f
