### ISSUE TITLE
Enforce American English via cspell dictionaries 

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#421]
I prefer to stick with American English cspell dictionaries.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/pull/302#discussion_r1055484873_

**Comment by hashedMae** [comment]
I installed cspell via yarn and went through the dollar contracts. Should this be added as a GitHub action?

**Comment by 0x4007** [comment]
> I installed cspell via yarn and went through the dollar contracts. Should this be added as a GitHub action?

cspell should run as a CI check, yeah!

Also in `lint-staged`

**Comment by 0x4007** [comment]
@Steveantor wallet address?

**Comment by Steveantor** [comment]
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by 0x4007** [comment]
> Here's my address:
0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE
@pavlovcik

https://etherscan.io/tx/0xaee4c4569e743e357fbd746934d222bcd2eb182bfc5d7c6f214f85826bad27ef
