### ISSUE TITLE
GitHub Action CI to run Anvil

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#425]
1. Create a `.yml` file that starts an Anvil instance on Github Actions. I presume that this would be basically a one-liner aside from the boilerplate `.yml` markdown.
2. Call the GitHub Actions Runner API to manually invoke the Action, starting an Anvil instance.

**Comment by FibrinLab** [comment]
Still an active issue? Can I work on this?

**Comment by sergfeldman** [comment]
> Still an active issue? Can I work on this?

@pavlovcik @0xcodercrane Is this issue actual?

**Comment by acaldas** [comment]
Hey, I worked a bit on this as part of [#209](https://github.com/ubiquity/ubiquity-dollar/issues/209), I'm back from my holidays. 
I set up a Github Action running Anvil with NGrok on Pull Requests.
As part of this task should Ngrok run too?

I can just adjust the action to run on API or manual triggers and make a PR.

**Comment by FibrinLab** [comment]
> Hey, I worked a bit on this as part of [#209](https://github.com/ubiquity/ubiquity-dollar/issues/209), I'm back from my holidays. 
> 
> I set up a Github Action running Anvil with NGrok on Pull Requests.
> 
> As part of this task should Ngrok run too?
> 
> 
> 
> I can just adjust the action to run on API or manual triggers and make a PR.

That's cool

**Comment by 0x4007** [comment]
> Hey, I worked a bit on this as part of [#209](https://github.com/ubiquity/ubiquity-dollar/issues/209), I'm back from my holidays. I set up a Github Action running Anvil with NGrok on Pull Requests. As part of this task should Ngrok run too?
> 
> I can just adjust the action to run on API or manual triggers and make a PR.

I think it shouldn't be on pull requests. Instead it should be invoked only by an API call to the GitHub Actions API. The intent is to build a UI on our dashboard that will do this API request. 

There's also a simple way to let GitHub [render a button to invoke the action](https://github.com/pavlovcik/uad-docs/blob/7246b130b931fdbc94c77fcf7c1561c4a6faf908/.github/workflows/sync.yml#L7), which may help us with some early debugging.

**Comment by cuddle-dev** [comment]
I guess we might need to hold it off for a while until [deploy script](https://github.com/ubiquity/ubiquity-dollar/pull/417) done. we need an anvil instance with smart contracts deployed.

**Comment by 0x4007** [comment]
Hey @acaldas sorry for overlooking your pull request. Thanks for your patience. Can you share your wallet address here?

**Comment by 0x4007** [comment]
Also could you let me know here what the curl request would look like to answer the second part of the bounty specification?

> 2. Call the GitHub Actions Runner API to manually invoke the Action, starting an Anvil instance.

**Comment by acaldas** [comment]
> Hey @acaldas sorry for overlooking your pull request. Thanks for your patience. Can you share your wallet address here?

No worries, here it is: 0x9F7F0721335dd004D3e848Fd1202264603Bb7397

> Also could you let me know here what the curl request would look like to answer the second part of the bounty specification?
> 
> > 2. Call the GitHub Actions Runner API to manually invoke the Action, starting an Anvil instance.

```bash
curl \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer github_pat_<API_TOKEN>"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/ubiquity/ubiquity-dollar/actions/workflows/deploy-anvil.yml/dispatches \
  -d '{"ref":"<BRANCH_REF>"}'
```
And here are the docs with more details: https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event

**Comment by 0x4007** [comment]
> No worries, here it is: 0x9F7F0721335dd004D3e848Fd1202264603Bb7397

https://etherscan.io/tx/0xbcccce50717bbb7d8e5987b9d0ccbe09553d3ce91fbf7fdbc8804670d253b238
https://etherscan.io/tx/0x130d384a88fd3604b45cbafba1dcc33831eabbe9b1c242156f5c1717ad10a651
