### ISSUE TITLE
Smart Contract final: UBQ bonding curve to burn UBQ and mint NFTs 

### ISSUE THREAD

**Issue by sergfeldman** [pavlovcik/uad-ui#434]
To do
Implement the final logic "Buy with any token" according to the discussion
- https://github.com/ubiquity/ubiquity-dollar/discussions/428

The issue is related to 
- https://github.com/ubiquity/ubiquity-dollar/issues/429
- https://github.com/ubiquity/ubiquity-dollar/issues/430

**Comment by 0x4007** [comment]
My fear is that if we do a custom Uniswap call on the smart contract, then we also need to calculate on the UI what the user must spend for any asset they try to buy with. This involves implementing the uniswap-router calculator in the UI which is a task that Sunny had great difficulty with for the "cash out uCR UI" bounty. 

This implementation will be the most elegant from a UX perspective, but we would probably need to make another bounty for incorporating the Uniswap calculation in the UI.

Reference https://github.com/ubiquity/ubiquity-dollar/pull/279#issuecomment-1284812047

**Comment by 0x4007** [comment]
Added blocked label so that the first part of this is implemented first. We should remove the blocked label when that is ready.

**Comment by rndquu** [comment]
Ubiquity NFT is deprecated so we may close this issue as "not planned"
