### ISSUE TITLE
Bonding Curve - "buy with any asset" - calculate Uniswap results in UI

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#436]
My fear is that if we do a custom Uniswap call on the smart contract, then we also need to calculate on the UI what the user must spend for any asset they try to buy with. This involves implementing the uniswap-router calculator in the UI which is a task that Sunny had great difficulty with for the "cash out uCR UI" bounty. 

This implementation will be the most elegant from a UX perspective, but we would probably need to make another bounty for incorporating the Uniswap calculation in the UI.

Reference: https://github.com/ubiquity/ubiquity-dollar/pull/279#issuecomment-1284812047

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/434#issuecomment-1366350265_

**Comment by rndquu** [comment]
As far as I understand this issue can be closed as "not planned" since it corresponds to the Credit and Credit NFT feature which is deprecated
