### ISSUE TITLE
Tests are sometimes not running for random RPC URLs

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#437]
For some RPC URLs from here https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/scripts/runner/conf.ts#L3 tests are not running

This is a random problem as sometimes nodes are again alive and tests are running fine

RIght now if I set `RPC_LIST` to:
```
export const RPC_LIST: string[] = [
  "https://ethereum.publicnode.com"
];
```
and run `yarn test:all` I get the following console output:
```
➤ YN0000: using https://ethereum.publicnode.com for testing...
➤ YN0000: No files changed, compilation skipped
➤ YN0000: 
➤ YN0000: Done in 4s 352ms
```

So tests are not running for RPC URL https://ethereum.publicnode.com.

But if I set `RPC_LIST` to:
```
export const RPC_LIST: string[] = [
  "https://cloudflare-eth.com"
];
```
And run `yarn test:all` again I can see that tests are running as expected:
```
➤ YN0000: using https://cloudflare-eth.com for testing...
➤ YN0000: No files changed, compilation skipped
➤ YN0000: 
➤ YN0000: 
➤ YN0000: Running 2 tests for test/dollar/core/CreditNFTRedemptionCalculator.t.sol:CreditNFTRedemptionCalculatorTest
➤ YN0000: [PASS] test_getCreditNFTAmount() (gas: 44451)
➤ YN0000: [PASS] test_getCreditNFTAmount_revertsIfDebtTooHigh() (gas: 37108)
➤ YN0000: Test result: ok. 2 passed; 0 failed; finished in 7.94s
➤ YN0000: 
➤ YN0000: 
➤ YN0000: Running 7 tests for test/dollar/transfer-hooks/CurveDollarIncentive.t.sol:CurveDollarIncentiveTest
➤ YN0000: [PASS] test_incentivize_buy() (gas: 190780)
➤ YN0000: [PASS] test_incentivize_revertsIfCallerNotUAD() (gas: 18240)
➤ YN0000: [PASS] test_incentivize_revertsIfSenderEqualToReceiver() (gas: 21567)
[...other output]
```

The same behaviour you can see in latest CI runs for latest PRs:
1. https://github.com/ubiquity/ubiquity-dollar/actions/runs/3790068199/jobs/6444392937 => tests are not running on the "Test" build step
```
Run yarn test:all
➤ YN0000: using https://eth-mainnet-public.unifra.io for testing...
➤ YN0000: No files changed, compilation skipped
➤ YN0000: 
➤ YN0000: Done in 3s 468ms
```
2. https://github.com/ubiquity/ubiquity-dollar/actions/runs/3793120005/jobs/6449927279 =>  tests are not running on the "Test" build step (though currently this RPC URL https://eth-mainnet.public.blastapi.io successfully runs tests on localhost)
```
Run yarn test:all
➤ YN0000: using https://eth-mainnet.public.blastapi.io for testing...
➤ YN0000: No files changed, compilation skipped
➤ YN0000: 
➤ YN0000: Done in 3s 811ms
```
3. https://github.com/ubiquity/ubiquity-dollar/actions/runs/3785967627/jobs/6436434604 => tests run as expected

**Comment by pavlovcik** [comment]
I think a quick solution could be to manually test with each of the RPC URLs in our list and remove the duds. 
A better solution would be to test if the tests run but I'm not sure how that could be done.

**Comment by 0x4007** [comment]
Hey @Steveantor as a continuation off of #383, can you do a test RPC request before selecting the RPC? I looked at the logs  somewhere earlier this morning (I can't find the exact example right now) and some appear to be returning HTML for example:
```
... <head><title>Forbidden</title></head>
```
Which is of course not expected from a JSON RPC endpoint.

I believe that this strategy will solve this issue.

**Comment by Steveantor** [comment]
> Hey @Steveantor as a continuation off of #383, can you do a test RPC request before selecting the RPC? I looked at the logs somewhere earlier this morning (I can't find the exact example right now) and some appear to be returning HTML for example:
> 
> ```
> ... <head><title>Forbidden</title></head>
> ```
> 
> Which is of course not expected from a JSON RPC endpoint.
> 
> I believe that this strategy will solve this issue.

I'll be working on this, some RPCs might be blocking the Github's IP address,
(despite them returning 200 Status code)
checking `blockNumber>=0` (**integer**) would be a great indication.
@pavlovcik

**Comment by 0x4007** [comment]
> I'll be working on this, some RPCs might be blocking the Github's IP address, (despite them returning 200 Status code) checking `blockNumber>=0` (**integer**) would be a great indication. @pavlovcik

It sounds like a good plan. Be sure to test on your fork to test your hypothesis.

**Comment by Steveantor** [comment]
PR #445

**Comment by 0x4007** [comment]
Hi @Steveantor please share your wallet address here. Thanks!

**Comment by Steveantor** [comment]
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by 0x4007** [comment]
> Here's my address:
> `0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
> @pavlovcik



https://etherscan.io/tx/0xfa63a7bb1e2cce9b316ed7248c2e9e1cfcb7bea42bc203e67c1b16af723c9f46
https://etherscan.io/tx/0xbc3d3ec45f3e2f0fb664b5c4cd44bbe5ee2cedccd00cf8e454dafb3ef643111a
