### ISSUE TITLE
CI build and test action passes on failed tests

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#440]
Check this CI run: https://github.com/ubiquity/ubiquity-dollar/actions/runs/3800990501/jobs/6464993015

There are failing tests in the "Test" build step but error is not thrown and CI run marked as successful

**Comment by 0x4007** [comment]
@0xcodercrane any ideas here?

**Comment by cuddle-dev** [comment]
yes because their function name is `testFail*` --- this means that it passes even if it fails on test in foundry.  If you remove `Fail` from `testFail`, you can see the build failing.

**Comment by rndquu** [comment]
This is more about the CI action. It should fail with both `test*` and `testFail*` on test error if test is expected to pass.

**Comment by cuddle-dev** [comment]
> This is more about the CI action. It should fail with both `test*` and `testFail*` on test error if test is expected to pass.

I don't think I understood correctly you're saying. It is what foundry does. I don't see the reason to customize CI action.

**Comment by rndquu** [comment]
> > This is more about the CI action. It should fail with both `test*` and `testFail*` on test error if test is expected to pass.
> 
> I don't think I understood correctly you're saying. It is what foundry does. I don't see the reason to customize CI action.

Ok, we need to find a common ground :)

Check this CI run: https://github.com/ubiquity/ubiquity-dollar/actions/runs/3800990501/jobs/6464993015

In the "Test" build step there are failing tests:
```
➤ YN0000: Encountered 5 failing tests in test/ubiquistick/UbiquiStick.t.sol:UbiquiStickTest
➤ YN0000: [FAIL. Reason: Call did not revert as expected] testApproveForBannedOperator() (gas: 181152)
➤ YN0000: [FAIL. Reason: Call did not revert as expected] testSafeTransferFromForBannedOperator() (gas: 181150)
➤ YN0000: [FAIL. Reason: Call did not revert as expected] testSafeTransferFromWithDataForBannedOperator() (gas: 181106)
➤ YN0000: [FAIL. Reason: Call did not revert as expected] testSetApprovalsAllForBannedOperator() (gas: 180658)
➤ YN0000: [FAIL. Reason: Call did not revert as expected] testTransferFromForBannedOperator() (gas: 181106)
```

But CI action `build-and-test` is marked as successful. It is expected to fail because of the failing tests.

I dont' see any `testFail*` tests so I can't understand how foundry is connected with failing tests.

**Comment by rndquu** [comment]
may I take this one?

**Comment by sergfeldman** [comment]
> > > This is more about the CI action. It should fail with both `test*` and `testFail*` on test error if test is expected to pass.
> > 
> > 
> > I don't think I understood correctly you're saying. It is what foundry does. I don't see the reason to customize CI action.
> 
> Ok, we need to find a common ground :)
> 
> Check this CI run: https://github.com/ubiquity/ubiquity-dollar/actions/runs/3800990501/jobs/6464993015
> 
> In the "Test" build step there are failing tests:
> 
> ```
> ➤ YN0000: Encountered 5 failing tests in test/ubiquistick/UbiquiStick.t.sol:UbiquiStickTest
> ➤ YN0000: [FAIL. Reason: Call did not revert as expected] testApproveForBannedOperator() (gas: 181152)
> ➤ YN0000: [FAIL. Reason: Call did not revert as expected] testSafeTransferFromForBannedOperator() (gas: 181150)
> ➤ YN0000: [FAIL. Reason: Call did not revert as expected] testSafeTransferFromWithDataForBannedOperator() (gas: 181106)
> ➤ YN0000: [FAIL. Reason: Call did not revert as expected] testSetApprovalsAllForBannedOperator() (gas: 180658)
> ➤ YN0000: [FAIL. Reason: Call did not revert as expected] testTransferFromForBannedOperator() (gas: 181106)
> ```
> 
> But CI action `build-and-test` is marked as successful. It is expected to fail because of the failing tests.
> 
> I dont' see any `testFail*` tests so I can't understand how foundry is connected with failing tests.

@rndquu hey, have you found a middle ground on the implementation with @pavlovcik and @0xcodercrane ?

**Comment by rndquu** [comment]
> > > > This is more about the CI action. It should fail with both `test*` and `testFail*` on test error if test is expected to pass.
> > > 
> > > 
> > > I don't think I understood correctly you're saying. It is what foundry does. I don't see the reason to customize CI action.
> > 
> > 
> > Ok, we need to find a common ground :)
> > Check this CI run: https://github.com/ubiquity/ubiquity-dollar/actions/runs/3800990501/jobs/6464993015
> > In the "Test" build step there are failing tests:
> > ```
> > ➤ YN0000: Encountered 5 failing tests in test/ubiquistick/UbiquiStick.t.sol:UbiquiStickTest
> > ➤ YN0000: [FAIL. Reason: Call did not revert as expected] testApproveForBannedOperator() (gas: 181152)
> > ➤ YN0000: [FAIL. Reason: Call did not revert as expected] testSafeTransferFromForBannedOperator() (gas: 181150)
> > ➤ YN0000: [FAIL. Reason: Call did not revert as expected] testSafeTransferFromWithDataForBannedOperator() (gas: 181106)
> > ➤ YN0000: [FAIL. Reason: Call did not revert as expected] testSetApprovalsAllForBannedOperator() (gas: 180658)
> > ➤ YN0000: [FAIL. Reason: Call did not revert as expected] testTransferFromForBannedOperator() (gas: 181106)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But CI action `build-and-test` is marked as successful. It is expected to fail because of the failing tests.
> > I dont' see any `testFail*` tests so I can't understand how foundry is connected with failing tests.
> 
> @rndquu hey, have you found a middle ground on the implementation with @pavlovcik and @0xcodercrane ?

hey

I see that the issue is that CI build action does not fail on failed tests and it should be fixed

Nevertheless it would be great to get a confirmation from @pavlovcik or @0xcodercrane

**Comment by 0x4007** [comment]
I delegate my vote to @zgorizzo69 lol

**Comment by zgorizzo69** [comment]
just talked with @rndquu we should indeed investigate and fix as it is not normal that the CI doesn't break on failing tests 
Based on the rest of the output from the CI logs I am guessing that it may be related to the RPC endpoint failing ..

**Comment by 0x4007** [comment]
@rndquu  says it's fixed so we can consider this completed. To be honest I'm on my phone and it's hard to tell what's happening here but I'll go off your word. Please share a wallet address!

**Comment by rndquu** [comment]
> @rndquu says it's fixed so we can consider this completed. To be honest I'm on my phone and it's hard to tell what's happening here but I'll go off your word. Please share a wallet address!

0x336C033842FA316d470e820c81b742e62A0765DC

**Comment by 0x4007** [comment]
> > @rndquu says it's fixed so we can consider this completed. To be honest I'm on my phone and it's hard to tell what's happening here but I'll go off your word. Please share a wallet address!
> 
> 0x336C033842FA316d470e820c81b742e62A0765DC

https://etherscan.io/tx/0xba314d6b9dc415135bdd9b3e78f9cecbfed32b9edb1a379f1c73db71a72c2322
https://etherscan.io/tx/0x6c52cc71acdc2a3d762c89a7db3f42a46d0b5f87b3335f26227cecc7d70c7d69
