### ISSUE TITLE
Bot Deployment Log Should Edit Existing Comment

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#446]
...instead of appending a new deploy comment. 

This is needed because the conversations become unnecessarily long for PRs with multiple commits. 

<img width="666" alt="Screenshot 2023-01-03 at 19 52 39" src="https://user-images.githubusercontent.com/4975670/210352138-7d0ddb6d-5178-4e6b-bbce-1183214605ce.png">

We should check if the bot has already commented. 
- YES: edit comment to append the new message in a line below. This will allow us to see all of the deployments in a single comment from the bot.
- NO: use existing behavior and create a new comment with the deployment.

`https://github.com/ubiquity/ubiquity-dollar/blob/development/utils/print_deployments_logs.js`

**Comment by Steveantor** [comment]
I can give it a go.

**Comment by 0x4007** [comment]
One last small ask, but if you can regex replace ` GMT+0000 (Coordinated Universal Time)` with ` UTC` that would be appreciated!

**Comment by Steveantor** [comment]
PR #449

**Comment by 0x4007** [comment]
Quick idea: I can merge it and you can make some dummy commits so we can see it in action on your PR?

**Comment by Steveantor** [comment]
> Quick idea: I can merge it and you can make some dummy commits so we can see it in action on your PR?

yeah, that's what I'd do

**Comment by 0x4007** [comment]
Merged

**Comment by Steveantor** [comment]
**Putting it here future reference:**

> First PR #449 
> Second PR #451 (bugfix)
> PR used for testing #450

**Comment by 0x4007** [comment]
Okay thank you. You can post your address and I can send payment!

**Comment by Steveantor** [comment]
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by 0x4007** [comment]
> Here's my address:
> 
> `0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
> 
> @pavlovcik 
> 
> 

https://etherscan.io/tx/0xe658c94257f1dcd1cb00661b03e3fc91f4f18c5a96ec57b59f3a916dc4ea54c5

https://etherscan.io/tx/0x916683e3b8e9fcf54d0f7d99070f17058c77192833c1a40b67aef5eaa6ccacf4

**Comment by 0x4007** [comment]
Hey @Steveantor I noticed some unusual behavior. I think they are out of order. Its a small detail but would you mind reordering it? https://github.com/ubiquity/ubiquity-dollar/pull/454#issuecomment-1371692834

**Comment by Steveantor** [comment]
> Hey @Steveantor I noticed some unusual behavior. I think they are out of order. Its a small detail but would you mind reordering it? [#454 (comment)](https://github.com/ubiquity/ubiquity-dollar/pull/454#issuecomment-1371692834)

I'm looking into it @pavlovcik

**Comment by 0x4007** [comment]
Here's a good example of many commits. Perhaps its sorting by month? I noticed that it seems to be in order, without considering the year.

https://github.com/ubiquity/ubiquity-dollar/pull/388#issuecomment-1376775930

**Comment by Steveantor** [comment]
> Here's a good example of many commits. Perhaps its sorting by month? I noticed that it seems to be in order, without considering the year.
> 
> [#388 (comment)](https://github.com/ubiquity/ubiquity-dollar/pull/388#issuecomment-1376775930)

It was following the default behavior,
I've added a PR #464 
@pavlovcik
