### ISSUE TITLE
Solidity Prettier Misconfiguration

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#447]
![image](https://user-images.githubusercontent.com/4975670/210435007-344d0226-4110-43d7-90bb-fea86893dbb7.jpeg)

Source: https://t.me/UbiquityDevPool/2303

> Lint-staged might be misconfigured,
I had use --no-verify a few times.

> We should ideally verify that it’s misconfigured and then fix it

> Although when I tried to make a commit today I didn’t encounter any issues again

> Perhaps it’s only for solidity files and not typescript files? I wouldn’t really know as I never touch the solidity code

> Yes. I agree. Prettier has an override for .sol files. I think that’s what is causing it

**Comment by Steveantor** [comment]
Will work on this.

**Comment by Steveantor** [comment]
PR #455

**Comment by 0x4007** [comment]
Address please @Steveantor thanks!

**Comment by Steveantor** [comment]
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by 0x4007** [comment]
> Here's my address: `0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE` @pavlovcik

https://etherscan.io/tx/0xab3fe4c355c507e8dcc2f2b81bb48e1a63e88331ca70fc5c318fa9201abc003d
https://etherscan.io/tx/0x431c9f5fc059c8c4e67d25d10755fc5fa3667ebabb51d52f734ebd5e76a229ff
