### ISSUE TITLE
Cloudflare Pages Deployment Broken

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#448]
[Cloudflare Log File](https://github.com/ubiquity/ubiquity-dollar/files/10341122/ubiquity-dollar.3677cf0d-2582-4ecb-a893-6f38967640a0.log) of last broken deploy on `development` 1b7a7e27591e6651f8bb708182853232fdf66db7

[Cloudflare Log File](https://github.com/ubiquity/ubiquity-dollar/files/10341142/ubiquity-dollar.08afe1ef-c0ad-4770-922c-60bd31e423cb.log) of last ok deploy on `development` 01641cac8d648649bdfb0bbbbcecf1c6fd0aa051

---

I ran a diff of the two logs and strangely enough 

```
Error: Could not find any Python installation to use
```

exists on both. I'm not sure exactly what the problem is but I believe it is Lavamoat related.

---

### Original Post

I think that Lavamoat broke Cloudflare deploys. It looks like Cloudflare is trying to run Python (is this due to Lavamoat?)

Is this a necessary step every time we deploy? Either we should disable running Python or we should install Python as part of the continuous deployment setup.

You're going to need to setup a Cloudflare account and use Cloudflare Pages (free) to work on this bounty.

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/4975670/210475907-49c40bb1-401e-4d0b-a138-22a546e05d50.png">

**Comment by Steveantor** [comment]
Been investigating this...

**Comment by Steveantor** [comment]
PR #452

**Comment by 0x4007** [comment]
Please share your wallet address. It works! Thanks.

**Comment by Steveantor** [comment]
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by 0x4007** [comment]
> Here's my address:
> 
> `0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
> 
> @pavlovcik 
> 
> 

https://etherscan.io/tx/0xa6774a546d0c78ed8d1a7b4cc615896ea3c0bd4ba2f0317387b6d2d35b9b8c86

https://etherscan.io/tx/0x2593faa55f74e574af172f38de4dcff87331d381c11373ffe4dda6ae6f03db73
