### ISSUE TITLE
UbiquiStick slither checks

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#472]
Right now we have [slither disabled](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/slither.config.json#L8) for this [folder](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/ubiquistick).

What should be done:
1. Remove `src/ubiquistick` from `filter_paths` in the [slither config file](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/slither.config.json)
2. Fix slither errors in the `src/ubiquistick` folder

> Ideally it should be included in slither checks but I figured out it requires a lot of changes. Fixing slither issue would take lots of time rather than re-implementing them properly. so I made it excluded. In the near future, we should include again.

_Originally posted by @0xcodercrane in https://github.com/ubiquity/ubiquity-dollar/pull/417#discussion_r1067061553_

**Comment by hashedMae** [comment]
Is this to remove the exclusion or to actually fix the issues that Slither raises?

**Comment by cuddle-dev** [comment]
> Is this to remove the exclusion or to actually fix the issues that Slither raises?

This issue is to fix the issues that Slither raises.

**Comment by 0x4007** [comment]
Also I believe that Slither has been disabled so we should probably update this issue and make sure that the entire thing works? 

I have some doubts with implementing Slither at the moment if we are still doing some large code changes (e.g. Diamond) is it a better idea to wait or does it make sense to iterate towards full code coverage?

**Comment by hashedMae** [comment]
Final checks should definitely happen when contracts move to a staging phase, but best practice is to write secure code from the jump. If we get to staging and the vulnerabilities run too deep, there's potential for refactoring that could delay production by weeks or months. Right now there's far too many places where we're not following the Checks Effects Interactions pattern and instead relying on non-reentrant modifiers

------- Original Message -------

**Comment by Steveantor** [comment]
You have to take false positives into consideration as well

**Comment by ghost** [comment]
@pavlovcik @rndquu this seems similar to #536 can i work on this?

**Comment by rndquu** [comment]
> @pavlovcik @rndquu this seems similar to #536 can i work on this?

sure

**Comment by ghost** [comment]
> > @pavlovcik @rndquu this seems similar to #536 can i work on this?
> 
> sure

#687 #681  has 1 review  still pending can i unassign them or i gotta wait?

**Comment by rndquu** [comment]
@pavlovcik can we assign @AnakinSkywalkeer ? There are 2 pending PRs ([one](https://github.com/ubiquity/ubiquity-dollar/pull/687) and [two](https://github.com/ubiquity/ubiquity-dollar/pull/681)) but they are waiting for @zgorizzo69 's review

**Comment by ghost** [comment]
> @pavlovcik can we assign @AnakinSkywalkeer ? There are 2 pending PRs ([one](https://github.com/ubiquity/ubiquity-dollar/pull/687) and [two](https://github.com/ubiquity/ubiquity-dollar/pull/681)) but they are waiting for @zgorizzo69 's review

i solved some errors but other requires me to ask questions about should i open the PR ?

**Comment by rndquu** [comment]
> > @pavlovcik can we assign @AnakinSkywalkeer ? There are 2 pending PRs ([one](https://github.com/ubiquity/ubiquity-dollar/pull/687) and [two](https://github.com/ubiquity/ubiquity-dollar/pull/681)) but they are waiting for @zgorizzo69 's review
> 
> i solved some errors but other requires me to ask questions about should i open the PR ?

pls open a PR

**Comment by 0x4007** [comment]
I was too late to get to this in time but this should be a one day issue, not a one week issue. I still have to re-check all of these old issues' labels.

**Comment by rndquu** [comment]
@AnakinSkywalkeer notice that we've updated the time label from `<1 week` to `<1 day`, the [time limit](https://github.com/ubiquity/ubiquity-dollar/issues/472#issuecomment-1601667538) is intact though

**Comment by ghost** [comment]
> @AnakinSkywalkeer notice that we've updated the time label from `<1 week` to `<1 day`, the [time limit](https://github.com/ubiquity/ubiquity-dollar/issues/472#issuecomment-1601667538) is intact though

oh okay
