### ISSUE TITLE
RPC Endpoint Rate Limiting in CI

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#473]
@Steveantor the CI got rate limited so it didn't pass. Should we make a new issue for this?

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/468#issuecomment-1379999025_
      
---

Related logs https://github.com/ubiquity/ubiquity-dollar/actions/runs/3892946159/jobs/6644961067

In case those expire here's some backups of the logs: 
1. [10_Test.txt](https://github.com/ubiquity/ubiquity-dollar/files/10399859/10_Test.txt)
2. https://pipelines.actions.githubusercontent.com/serviceHosts/0a22f811-4a27-4e7b-a052-c8ab5fb0a8e0/_apis/pipelines/1/runs/2994/signedlogcontent/2?urlExpires=2023-01-12T08%3A59%3A04.3964952Z&urlSigningMethod=HMACV1&urlSignature=hI4GDPjDpH5ZBy9wwT3VcmuCxMaKdFfPP%2FNE%2FWPCnBo%3D

<img width="745" alt="image" src="https://user-images.githubusercontent.com/4975670/212023008-ccb8fd2a-ea97-495e-ab4e-665756bc15f5.png">

**Comment by Steveantor** [comment]
I'd like to work on this since it can be a serious blocker

**Comment by Steveantor** [comment]
I forgot to update here:
tracing:
https://github.com/ubiquity/ubiquity-dollar/pull/474
https://github.com/ubiquity/ubiquity-dollar/pull/476
https://github.com/ubiquity/ubiquity-dollar/pull/478
https://github.com/ubiquity/ubiquity-dollar/pull/479
