### ISSUE TITLE
Refactor tests to maintain a single naming convention

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#480]
Refactor tests using the following convention test[MethodName]_[ExpectedResult]_[Condition]

Examples:

- https://github.com/cryptexfinance/contracts/blob/master/test/HardETHVaultHandler.t.sol#L74
- https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/dollar/ERC20Ubiquity.t.sol#L81

**Comment by pwilson77** [comment]
Hi does this still need to be worked on

**Comment by sergfeldman** [comment]
> Hi does this still need to be worked on

@rndquu @0xcodercrane Please check if this issue is actual.

**Comment by rndquu** [comment]
> > Hi does this still need to be worked on
> 
> @rndquu @0xcodercrane Please check if this issue is actual.

yes, it can be worked on

**Comment by pwilson77** [comment]
sure

**Comment by 0x4007** [comment]
Thanks @pwilson77 please share your DAI wallet address here!

**Comment by pwilson77** [comment]
You are welcome @pavlovcik, here is the wallet address
0x639EeCAA3418AfbAB34A3c5B44cC14A9045D7429

**Comment by 0x4007** [comment]
> You are welcome @pavlovcik, here is the wallet address
0x639EeCAA3418AfbAB34A3c5B44cC14A9045D7429

@pwilson77 my apologies for missing this notification! 

https://etherscan.io/tx/0x1d8a3b07ce67c85482efeb98ba50cbe9cd72afc1bed244c5205bda2e328e5dac
https://etherscan.io/tx/0x454e6110965e2933c0efb12c4038b2eb200fc01387b5df8bba3b15ddc8be0add

**Comment by pwilson77** [comment]
uhm I am a bit confused, I thought the bounty amount had been sent long ago here is the transaction hash
https://etherscan.io/tx/0x615b6424844d4fd695fc27850a6b09dd93cf571b67de5349a264af1cc47bcf94

please let me know if its a mistake @pavlovcik

**Comment by 0x4007** [comment]
Looks like I forgot to post the transaction receipt here. Thanks for letting me know. If you could send the DAI back it would be appreciated. Sorry about that!

**Comment by pwilson77** [comment]
Sure no problem, sent it back 
https://etherscan.io/tx/0xec0629ee2c2c29c6b068fdaf3364bab6d7938a02a9c2f174dfb1cca33379b702
