### ISSUE TITLE
Add build badges and update test coverage config

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#482]
What should be done:
1. Add CI build badge at the top of the https://github.com/ubiquity/ubiquity-dollar/blob/development/README.md with the current CI build status (success or fail)
2. Add test coverage badge with % of lines covered by tests at the top of the https://github.com/ubiquity/ubiquity-dollar/blob/development/README.md
3. Remove the following files from the test coverage report:

- `src/dollar/libs/*`
- `src/dollar/mocks/*`
- `src/dollar/utils/*`
- `src/manager/libraries/*`
- `src/ubiquistick/MockUBQmanager.sol`
- `test/*`

Build badge docs: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

**Comment by FibrinLab** [comment]
> What should be done:
> 
> 1. Add CI build badge at the top of the https://github.com/ubiquity/ubiquity-dollar/blob/development/README.md with the current CI build status (success or fail)
> 
> 2. Add test coverage badge with % of lines covered by tests at the top of the https://github.com/ubiquity/ubiquity-dollar/blob/development/README.md
> 
> 3. Remove the following files from the test coverage report:
> 
> 
> 
> - `src/dollar/libs/*`
> 
> - `src/dollar/mocks/*`
> 
> - `src/dollar/utils/*`
> 
> - `src/manager/libraries/*`
> 
> - `src/ubiquistick/MockUBQmanager.sol`
> 
> - `test/*`
> 
> 
> 
> 
> 
> Build badge docs: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge


@rndquu can I be assigned this.

**Comment by 0x4007** [comment]
Hey @FibrinLab, I appreciate your work on this bounty and your dedication to getting the task done. However, I need to ensure that we can move forward in a timely manner. I see that there have been some delays with the pull requests you've submitted, and I'm concerned that I've spent almost as much time reviewing the pull requests as it would have taken for me to finish the task. In order to stay on schedule, I will need to assign the remaining work to someone else. Thank you for your contributions so far.

**Comment by FibrinLab** [comment]
> Hey @FibrinLab, I appreciate your work on this bounty and your dedication to getting the task done. However, I need to ensure that we can move forward in a timely manner. I see that there have been some delays with the pull requests you've submitted, and I'm concerned that I've spent almost as much time reviewing the pull requests as it would have taken for me to finish the task. In order to stay on schedule, I will need to assign the remaining work to someone else. Thank you for your contributions so far.

Thanks. Hope to work more in the future.

**Comment by QuintusTheFifth** [comment]
@pavlovcik can I get another day for this? I'm not sure I'm gonna be able to work on it much today.

**Comment by rndquu** [comment]
@QuintusTheFifth 

The coveralls CI actions seems not to be working as expected

1. There is a syntax error in the workflow yml: https://github.com/ubiquity/ubiquity-dollar/actions/runs/5175978338
2. Coveralls github actions doesn't upload the report: https://github.com/ubiquity/ubiquity-dollar/actions/runs/5178154758/jobs/9329230449?pr=672

Could you fix those issues?

**Comment by QuintusTheFifth** [comment]
> 1. https://github.com/ubiquity/ubiquity-dollar/blob/development/README.md



> @QuintusTheFifth
> 
> The coveralls CI actions seems not to be working as expected
> 
> 1. There is a syntax error in the workflow yml: https://github.com/ubiquity/ubiquity-dollar/actions/runs/5175978338
> 2. Coveralls github actions doesn't upload the report: https://github.com/ubiquity/ubiquity-dollar/actions/runs/5178154758/jobs/9329230449?pr=672
> 
> Could you fix those issues?

@rndquu 
Only issue I see is the indentation on the last line, but that didn't stop it from working in my own repo. I also refreshed the badge detector on the coveralls.io ubiquity page, it seems to be detecting it now and waiting for jobs.

**Comment by rndquu** [comment]
@QuintusTheFifth check this CI run https://github.com/ubiquity/ubiquity-dollar/actions/runs/5178154758/jobs/9329230449?pr=672

The error states: `ENOENT: no such file or directory, open './coverage/lcov.info' ` so the [coveralls CI action](https://github.com/ubiquity/ubiquity-dollar/blob/b4ac541fe9b12b88d42f0d70442f2ebb3d146437/.github/workflows/coverage-check.yml#L122) can't find `lcov.info` file to upload

Can you show the CI action working in your own repo? I guess badges in your repo are generated using the [coverage.sh script](https://github.com/QuintusTheFifth/ubiquity-dollar/blob/01a07a96a074813fda2490cbef7185ddea06400e/packages/contracts/coverage.sh) which works fine while the CI action fails

**Comment by rndquu** [comment]
Initially this issue was implemented incorrectly, this PR https://github.com/ubiquity/ubiquity-dollar/pull/700 finishes it so we can close the issue
