### ISSUE TITLE
Add CI action that fails on decreased test coverage

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#484]
When user creates a PR to the `development` branch there should be a github action that checks that code coverage is not decreased. If code coverage is decreased the CI action should fail.

Depends on: https://github.com/ubiquity/ubiquity-dollar/issues/483

**Comment by FibrinLab** [comment]
> When user creates a PR to the `development` branch there should be a github action that checks that code coverage is not decreased. If code coverage is decreased the CI action should fail.
> 
> 
> 
> Depends on: https://github.com/ubiquity/ubiquity-dollar/issues/483

How about a CI that check solidity code coverage and fails if less that 80%. Would that work also?

**Comment by rndquu** [comment]
> > When user creates a PR to the `development` branch there should be a github action that checks that code coverage is not decreased. If code coverage is decreased the CI action should fail.
> > Depends on: #483
> 
> How about a CI that check solidity code coverage and fails if less that 80%. Would that work also?

I think it wouldn't work

Consider an example:
1. Coverage is 90%
2. New contract is added without tests
3. Coverage decreases to 88% but overall is greater than 80% so CI action passes

We used such CI action(which fails on decreased code coverage) in one of the previous projects and it really helps

**Comment by 0x4007** [comment]
> We used such CI action(which fails on decreased code coverage) in one of the previous projects and it really helps

Its an interesting idea to consider. Perhaps you can make a bounty for it if you're bullish on the idea and copy the GitHub Action.

**Comment by pwilson77** [comment]
Hi can I work on this

**Comment by pwilson77** [comment]
@pavlovcik , I get this error unpredictable GAS limit , when I click on claim
{
  "reason": "execution reverted",
  "code": "UNPREDICTABLE_GAS_LIMIT",
  "method": "estimateGas",
  "transaction": {
    "from": "0x639EeCAA3418AfbAB34A3c5B44cC14A9045D7429",
    "to": "0x000000000022D473030F116dDEE9F6B43aC78BA3",
    "data": "0x30f28b7a0000000000000000000000006b175474e89094c44da98b954eedeac495271d0f0000000000000000000000000000000000000000000000056bc75e2d63100000e5016dd0b6ebe477d1f5805a8efe3689c1b9cacbe8d0c8a150bc5fbfc05977f1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000000000000000000000000639eecaa3418afbab34a3c5b44cc14a9045d74290000000000000000000000000000000000000000000000056bc75e2d63100000000000000000000000000000f87ca4583c792212e52720d127e7e0a38b818ad10000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000004120501556b0d578bcd0689fe9fc5aa0dd08383d1c2b7f1562e2ec2338d1e35b63463f5ec4d3f5ec9296c33a888b31e1102576d2b30e02c9ff9d99ba216b7833521c00000000000000000000000000000000000000000000000000000000000000",
    "accessList": null
  },
  "error": {
    "code": -32603,
    "message": "execution reverted",
    "data": {
      "originalError": {
        "code": 3,
        "data": "0x756688fe",
        "message": "execution reverted"
      }
    }
  }
}

**Comment by 0x4007** [comment]
@rndquu @Steveantor any ideas on how to solve the claim issue?

**Comment by Steveantor** [comment]
> @rndquu @Steveantor any ideas on how to solve the claim issue?

The connected wallet might be incorrect

**Comment by pwilson77** [comment]
It shows here the right wallet is connected
![image](https://user-images.githubusercontent.com/26203074/233844929-b6f57fb0-87de-421d-91ef-0e31a93cfcb6.png)

**Comment by pwilson77** [comment]
Hi @pavlovcik , @Steveantor , It looks like the funds were transferred earlier when I approved the permitTransferFrom, sorry i didn't notice and clicked claim again
![image](https://user-images.githubusercontent.com/26203074/233846279-723b2913-8e60-4c7e-9987-9a74bf67d5ae.png)
