### ISSUE TITLE
Remove mocks, libs and tests from coverage report

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#485]
Remove the following files from the test coverage report:

- `src/dollar/libs/*`
- `src/dollar/mocks/*`
- `src/dollar/utils/*`
- `src/manager/libraries/*`
- `src/ubiquistick/MockUBQmanager.sol`
- `test/*`

**Comment by 0x4007** [comment]
This makes me think that we should add a `Time: <1 Hour` label. For now, @rndquu I suggest either consolidating this into another similar bounty, or if there are none, then we leave it as is.

**Comment by rndquu** [comment]
> This makes me think that we should add a `Time: <1 Hour` label. For now, @rndquu I suggest either consolidating this into another similar bounty, or if there are none, then we leave it as is.

moved to https://github.com/ubiquity/ubiquity-dollar/issues/482
