### ISSUE TITLE
Add more tests for ERC1155SetUri

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#486]
Add more tests for:
- `src/dollar/ERC1155SetUri/ERC1155BurnableSetUri.sol`
- `src/dollar/ERC1155SetUri/ERC1155PausableSetUri.sol`
- `src/dollar/ERC1155SetUri/ERC1155SetUri.sol`

Test coverage right now:

| File                                               | % Lines           | % Statements      | % Branches        | % Funcs          |
|----------------------------------------------------|-------------------|-------------------|-------------------|------------------|
| src/dollar/ERC1155SetUri/ERC1155BurnableSetUri.sol | 0.00% (0/4)       | 0.00% (0/4)       | 0.00% (0/4)       | 0.00% (0/2)      |
| src/dollar/ERC1155SetUri/ERC1155PausableSetUri.sol | 100.00% (2/2)     | 100.00% (2/2)     | 50.00% (1/2)      | 100.00% (1/1)    |
| src/dollar/ERC1155SetUri/ERC1155SetUri.sol         | 56.52% (52/92)    | 54.39% (62/114)   | 25.00% (10/40)    | 66.67% (14/21)   |

**Comment by 0x4007** [comment]
These could be forked. 

Given that we didn't invent the ERC1155 standard, tests should exist somewhere out there for this already right?

**Comment by rndquu** [comment]
This "set URI for ERC1155" feature should have been implemented writing a smart contract that inherits from the original implementation https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/ERC1155.sol. But instead of inheriting the origin contract was copy-pasted. If it is copy pasted it is considered to be "our custom implementation" and should be tested as well.

There are 2 approaches here:
1. Refactor `ERC1155SetUri ` to inherit from openzeppelin contracts and write tests for modified methods
2. Leave it as is, make a diffcheck for `ERC1155SetUri ` with origin openzeppelin contracts and add tests for modified methods

**Comment by zorglob21** [comment]
@rndquu 
Hello. i did implement this function, and the reason for this choice was that the team wouldn't agree to me modifying the original erc1155 contract, from the sub module folder, if i remember correctly. the variable _uri as to be set to correct visibility. The contracts are strictly similar to open zeppelin except for their names and _uri visibility. Some names had to be changed to avoid conflicts. This was the only alternative to do it as far as i'm aware since i wasn't allowed to touch the original erc1155 contract, which would have been simpler.
Inheriting the contract in a new contract did not work as the _uri variable is private on the open zeppelin version and canno't be overrided.

**Comment by 0x4007** [comment]
@0xcodercrane @rndquu what do you think about @zorglob21's comment?

**Comment by rndquu** [comment]
> @rndquu Hello. i did implement this function, and the reason for this choice was that the team wouldn't agree to me modifying the original erc1155 contract, from the sub module folder, if i remember correctly. the variable _uri as to be set to correct visibility. The contracts are strictly similar to open zeppelin except for their names and _uri visibility. Some names had to be changed to avoid conflicts. This was the only alternative to do it as far as i'm aware since i wasn't allowed to touch the original erc1155 contract, which would have been simpler. Inheriting the contract in a new contract did not work as the _uri variable is private on the open zeppelin version and canno't be overrided.

Issue: https://github.com/ubiquity/ubiquity-dollar/issues/170
PR: https://github.com/ubiquity/ubiquity-dollar/pull/420

I think we could just inherit `StakingShare` from `ERC1155UriStorage` (https://docs.openzeppelin.com/contracts/4.x/api/token/erc1155#ERC1155URIStorage) and make `setURI` with `setBaseURI` public and callable only by user with the "staking manager" role

If staking share contract is not yet redeployed then we could:
1. reopen https://github.com/ubiquity/ubiquity-dollar/issues/170
2. remove `ERC1155**SetUri` contracts
3. use `ERC1155UriStorage`

**Comment by zorglob21** [comment]
@rndquu so basically remove all of the merged PR #420 except for the added staking manager role, and just inherit the ERC1155UriStorage on stakingShare.sol.  I could do this. Regarding the previous PR, i'm sorry it doesn't seem satisfying but i did what was asked, and first i tried to simply work on the erc1155 contract, but that wasn't possible as i said so i had to find another solution.

**Comment by rndquu** [comment]
> @rndquu so basically remove all of the merged PR #420 except for the added staking manager role, and just inherit the ERC1155UriStorage on stakingShare.sol. I could do this. Regarding the previous PR, i'm sorry it doesn't seem satisfying but i did what was asked, and first i tried to simply work on the erc1155 contract, but that wasn't possible as i said so i had to find another solution.

There is no issue, this one https://github.com/ubiquity/ubiquity-dollar/pull/420 is also an option. And all options have their pros and cons.

Anyway, you are welcome to work on this issue and use `ERC1155UriStorage`. I don't know if we should create another bounty for this task, it's up to @pavlovcik to decide. Or we can just update the description of this bounty.

**Comment by 0x4007** [comment]
@zgorizzo69 is gonna know the best about Solidity architecture. I couldn't say.

**Comment by FibrinLab** [comment]
Is this still an active issue?

**Comment by rndquu** [comment]
> Is this still an active issue?

yes, pls check this comment: https://github.com/ubiquity/ubiquity-dollar/issues/486#issuecomment-1400666024

**Comment by FibrinLab** [comment]
> > Is this still an active issue?
> 
> 
> 
> yes, pls check this comment: https://github.com/ubiquity/ubiquity-dollar/issues/486#issuecomment-1400666024

That's fine. I did the test for the staking contract. I could do this tonight

**Comment by rndquu** [comment]
> > > Is this still an active issue?
> > 
> > 
> > yes, pls check this comment: [#486 (comment)](https://github.com/ubiquity/ubiquity-dollar/issues/486#issuecomment-1400666024)
> 
> That's fine. I did the test for the staking contract. I could do this tonight

you're welcome to start

you can comment with the `/assign` command and the bot should assign this issue to you

**Comment by FibrinLab** [comment]
> > > > Is this still an active issue?
> 
> > > 
> 
> > > 
> 
> > > yes, pls check this comment: [#486 (comment)](https://github.com/ubiquity/ubiquity-dollar/issues/486#issuecomment-1400666024)
> 
> > 
> 
> > That's fine. I did the test for the staking contract. I could do this tonight
> 
> 
> 
> you're welcome to start
> 
> 
> 
> you can comment with the `/assign` command and the bot should assign this issue to you

I don't think the command worked

**Comment by FibrinLab** [comment]
`/assign`

**Comment by rndquu** [comment]
> `/assign`

try without the markdown, pure "/assign"

@0xcodercrane perhaps we could support commands with code formatting

**Comment by 0x4007** [comment]
@0xcodercrane looks like the bot is broken

**Comment by cuddle-dev** [comment]
> @0xcodercrane looks like the bot is broken

Ubiquibot has not been installed on the repo. just installed it. it should be fixed now. @FibrinLab would you please try again?

**Comment by FibrinLab** [comment]
> @FibrinLab would you please post your wallet address here?

/wallet 0x43BbdE754e2e4e8A3b1282D1037Ce1a1B7c577C2

**Comment by cuddle-dev** [comment]
> ### [ **[ CLAIM 100 DAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiMTAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiOTE3NjE1NTA5MzM4NDY2MTU2NDg4OTU2ODUzNTQyMDM1MzY3OTgwMzE0OTUyOTYxMTMwNzkzMzgwNDM1NDg3MjAyMTQ1NTg2MjE5MTgiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweDQzQmJkRTc1NGUyZTRlOEEzYjEyODJEMTAzN0NlMWExQjdjNTc3QzIiLCJyZXF1ZXN0ZWRBbW91bnQiOiIxMDAwMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweGY4N2NhNDU4M0M3OTIyMTJlNTI3MjBkMTI3RTdFMEEzOEI4MThhRDEiLCJzaWduYXR1cmUiOiIweDRhZDFkODBkMWMwZDI2YTAwNDQ0NTQxYmMxOGI2ZjExNWU3MmY5NjgxMmY1MWVmNmEwZjk0NWY1MTM2M2RmZmQzMTM4YTcwMGVlY2E5MDIxNjNjM2UzMzRhZDM4NDQzNDI1YjY1OTVhY2ZlYTRjODExMDQ5N2M5MjdmYmQ5NWZhMWMifQ==)
> `0x43BbdE7...B7c577C2`

@FibrinLab  here you go
