### ISSUE TITLE
Add more tests for Staking

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#487]
Add more tests for:
- `src/dollar/Staking.sol`
- `src/dollar/StakingShare.sol`

Test coverage right now:
| File                                               | % Lines           | % Statements      | % Branches        | % Funcs          |
|----------------------------------------------------|-------------------|-------------------|-------------------|------------------|
| src/dollar/Staking.sol                             | 84.62% (110/130)  | 85.33% (128/150)  | 57.14% (16/28)    | 66.67% (16/24)   |
| src/dollar/StakingFormulas.sol                     | 100.00% (9/9)     | 100.00% (12/12)   | 100.00% (2/2)     | 100.00% (4/4)    |
| src/dollar/StakingShare.sol                        | 75.00% (30/40)    | 71.43% (30/42)    | 33.33% (2/6)      | 71.43% (10/14)   |

**Comment by FibrinLab** [comment]
Is there any test in particular you want?

**Comment by rndquu** [comment]
@FibrinLab ideally test coverage for `Staking.sol` and `StakingShare.sol` should be 100%, but if some tests are hard to implement then you can skip them

**Comment by FibrinLab** [comment]
> @FibrinLab ideally test coverage for `Staking.sol` and `StakingShare.sol` should be 100%, but if some tests are hard to implement then you can skip them

Alright. I would like to give this a go.

**Comment by rndquu** [comment]
> > @FibrinLab ideally test coverage for `Staking.sol` and `StakingShare.sol` should be 100%, but if some tests are hard to implement then you can skip them
> 
> Alright. I would like to give this a go.

ok, assigned to you

**Comment by 0x4007** [comment]
@FibrinLab please share your wallet address here!

**Comment by FibrinLab** [comment]
> @FibrinLab please share your wallet address here!

0x43BbdE754e2e4e8A3b1282D1037Ce1a1B7c577C2

**Comment by FibrinLab** [comment]
> @FibrinLab please share your wallet address here!

@pavlovcik 0x43BbdE754e2e4e8A3b1282D1037Ce1a1B7c577C2

**Comment by 0x4007** [comment]
> > @FibrinLab please share your wallet address here!
> 
> @pavlovcik 0x43BbdE754e2e4e8A3b1282D1037Ce1a1B7c577C2

https://etherscan.io/tx/0x28535d192a637923de538dbcc52bd70023e5b62a295991789f843e5450bd3be2
