### ISSUE TITLE
Add more tests for UbiquityChef and UbiquityFormulas

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#488]
Add more tests for:
- `src/dollar/UbiquityChef.sol`
- `src/dollar/UbiquityFormulas.sol`

Test coverage right now:
| File                                               | % Lines           | % Statements      | % Branches        | % Funcs          |
|----------------------------------------------------|-------------------|-------------------|-------------------|------------------|
| src/dollar/UbiquityChef.sol                        | 88.41% (61/69)    | 88.16% (67/76)    | 61.11% (11/18)    | 100.00% (15/15)  |
| src/dollar/UbiquityFormulas.sol                    | 40.74% (11/27)    | 42.55% (20/47)    | 0.00% (0/2)       | 40.00% (2/5)     |

**Comment by 0x4007** [comment]
Consolidated into https://github.com/ubiquity/ubiquity-dollar/issues/489
