### ISSUE TITLE
Add more tests for Ubiquity Dollar custom smart contracts

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#489]
### Notice: tests must achieve 80% or greater code coverage per smart contract.

# Add more tests for the following smart contracts

- `src/ubiquistick/UbiquiStick.sol`
- `src/ubiquistick/UbiquiStickSale.sol`

| File                                               | % Lines           | % Statements      | % Branches        | % Funcs          |
|----------------------------------------------------|-------------------|-------------------|-------------------|------------------|
| src/ubiquistick/UbiquiStick.sol                    | 42.31% (11/26)    | 39.29% (11/28)    | 0.00% (0/12)      | 57.14% (8/14)    |
| src/ubiquistick/UbiquiStickSale.sol                | 0.00% (0/13)      | 0.00% (0/15)      | 0.00% (0/6)       | 0.00% (0/6)      |

- `src/ubiquistick/LP.sol`
- `src/ubiquistick/SimpleBond.sol`
- `src/ubiquistick/UAR.sol`

| File                                               | % Lines           | % Statements      | % Branches        | % Funcs          |
|----------------------------------------------------|-------------------|-------------------|-------------------|------------------|
| src/ubiquistick/LP.sol                             | 0.00% (0/1)       | 0.00% (0/1)       | 100.00% (0/0)     | 0.00% (0/1)      |
| src/ubiquistick/SimpleBond.sol                     | 84.91% (45/53)    | 86.44% (51/59)    | 44.44% (8/18)     | 85.71% (12/14)   |
| src/ubiquistick/UAR.sol                            | 0.00% (0/1)       | 0.00% (0/1)       | 100.00% (0/0)     | 0.00% (0/1)      |

- `src/dollar/UbiquityChef.sol`
- `src/dollar/UbiquityFormulas.sol`

| File                                               | % Lines           | % Statements      | % Branches        | % Funcs          |
|----------------------------------------------------|-------------------|-------------------|-------------------|------------------|
| src/dollar/UbiquityChef.sol                        | 88.41% (61/69)    | 88.16% (67/76)    | 61.11% (11/18)    | 100.00% (15/15)  |
| src/dollar/UbiquityFormulas.sol                    | 40.74% (11/27)    | 42.55% (20/47)    | 0.00% (0/2)       | 40.00% (2/5)     |

- `src/dollar/core/CreditRedemptionCalculator.sol`
- `src/dollar/core/DollarMintExcess.sol`
- `src/dollar/core/UbiquityCreditToken.sol`

| File                                               | % Lines           | % Statements      | % Branches        | % Funcs          |
|----------------------------------------------------|-------------------|-------------------|-------------------|------------------|
| src/dollar/core/CreditRedemptionCalculator.sol     | 0.00% (0/9)       | 0.00% (0/14)      | 0.00% (0/2)       | 0.00% (0/3)      |
| src/dollar/core/DollarMintExcess.sol               | 0.00% (0/30)      | 0.00% (0/37)      | 0.00% (0/2)       | 0.00% (0/4)      |
| src/dollar/core/UbiquityCreditToken.sol            | 0.00% (0/2)       | 0.00% (0/3)       | 100.00% (0/0)     | 0.00% (0/1)      |

**Comment by 0x4007** [comment]
I consolidated other similar bounties because it appears that these would need to be custom written. GitHub Copilot surely can help a ton with this!

It isn't clear to me why @rndquu grouped them the way that you did, so I preserved the grouping in my edit of the spec here. If the grouping is not significant, I suggest consolidating all of them into a single list for additional clarity. 

I think we should also seek to specify a certain percentage of code coverage. I'll ask the DevPool to weigh in on this. I got one response suggesting 80%

**Comment by rndquu** [comment]
> I consolidated other similar bounties because it appears that these would need to be custom written. GitHub Copilot surely can help a ton with this!
> 
> It isn't clear to me why @rndquu grouped them the way that you did, so I preserved the grouping in my edit of the spec here. If the grouping is not significant, I suggest consolidating all of them into a single list for additional clarity.
> 
> I think we should also seek to specify a certain percentage of code coverage. I'll ask the DevPool to weigh in on this. I got one response suggesting 80%

I grouped them by small chunks of related contracts where each chunk is basically a 1 day bounty

> I think we should also seek to specify a certain percentage of code coverage

ideally it should be 100%, but if some tests are hard to implement we can skip them

**Comment by rndquu** [comment]
May I take this one?

**Comment by sergfeldman** [comment]
> May I take this one?

@rndquu If you have time after doing progress in other tasks that you agreed with Alex, then you can take this bounty :)

**Comment by rndquu** [comment]
> > May I take this one?
> 
> @rndquu If you have time after doing progress in other tasks that you agreed with Alex, then you can take this bounty :)

Yes, I have time

**Comment by rndquu** [comment]
0x336c033842fa316d470e820c81b742e62a0765dc

**Comment by 0x4007** [comment]
> 0x336c033842fa316d470e820c81b742e62a0765dc

https://etherscan.io/tx/0xf80b353a2e1856d298c9b79d061a6ab4125bbcfb976927ea63a626bdbecfbf1d
https://etherscan.io/tx/0xed778230ec778433fc0cbd6d01ff8756b869465a9defc62a2a45d2cdf6e36e3d
