### ISSUE TITLE
Add more tests for ubiquistick: LP, SimpleBond and UAR

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#490]
Add more tests for:
- `src/ubiquistick/LP.sol`
- `src/ubiquistick/SimpleBond.sol`
- `src/ubiquistick/UAR.sol`

Test coverage right now:
| File                                               | % Lines           | % Statements      | % Branches        | % Funcs          |
|----------------------------------------------------|-------------------|-------------------|-------------------|------------------|
| src/ubiquistick/LP.sol                             | 0.00% (0/1)       | 0.00% (0/1)       | 100.00% (0/0)     | 0.00% (0/1)      |
| src/ubiquistick/SimpleBond.sol                     | 84.91% (45/53)    | 86.44% (51/59)    | 44.44% (8/18)     | 85.71% (12/14)   |
| src/ubiquistick/UAR.sol                            | 0.00% (0/1)       | 0.00% (0/1)       | 100.00% (0/0)     | 0.00% (0/1)      |

**Comment by 0x4007** [comment]
Consolidated into https://github.com/ubiquity/ubiquity-dollar/issues/489
