### ISSUE TITLE
Add more tests for UbiquiStick and UbiquiStickSale

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#491]
Add more tests for:
- `src/ubiquistick/UbiquiStick.sol`
- `src/ubiquistick/UbiquiStickSale.sol`

Test coverage right now:
| File                                               | % Lines           | % Statements      | % Branches        | % Funcs          |
|----------------------------------------------------|-------------------|-------------------|-------------------|------------------|
| src/ubiquistick/UbiquiStick.sol                    | 42.31% (11/26)    | 39.29% (11/28)    | 0.00% (0/12)      | 57.14% (8/14)    |
| src/ubiquistick/UbiquiStickSale.sol                | 0.00% (0/13)      | 0.00% (0/15)      | 0.00% (0/6)       | 0.00% (0/6)      |

**Comment by 0x4007** [comment]
Consolidated into https://github.com/ubiquity/ubiquity-dollar/issues/489
