### ISSUE TITLE
Research inconsistent oracle behavior on testnet and not mainnet

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#494]
I just want to ensure that there isn't an issue here. The best way is to understand why this fails on a testnet and not on mainnet. 

---

> On local testnet, it fails unless a trade has taken place, like the `metapool.get_price_cumulative_last()` in the constructor. I don't understand why the behaviour works on mainnet but not a local testnet.

_Originally posted by @hashedMae in https://github.com/ubiquity/ubiquity-dollar/pull/417#discussion_r1071507824_

**Comment by hashedMae** [comment]
In Vyper, like Solidity, uninitialized values are meant to default to zero. This doesn't always happen though and will sometimes point to garbage memory. Their way of fixing this was to make initialization mandatory during compilation (ie `uint reserve_0 = 0;`), but this isn't enforced for arrays.  Forge also doesn't have a Vyper compiler and would be using the bytecode for the Curve Pool when it creates a new one from the factory. 

One possible fix would be to create a mock of the Curve Pool contract in solidity for testing and local environments.

**Comment by 0x4007** [comment]
> Their way of fixing this was to make initialization mandatory during compilation (ie `uint reserve_0 = 0;`), but this isn't enforced for arrays. 

If I'm understanding this correctly, can you make a PR and initialize all the related variables to 0?

**Comment by hashedMae** [comment]
> > Their way of fixing this was to make initialization mandatory during compilation (ie `uint reserve_0 = 0;`), but this isn't enforced for arrays.
> 
> If I'm understanding this correctly, can you make a PR and initialize all the related variables to 0?

Forge doesn't have a vyper compiler. Deploying on an actual and not just local testnet would clear this up. I just don't know which one has a MetaPool factory deployed

**Comment by 0x4007** [comment]
No testnet has metapools deployed. Either way, if we are migrating to v3 isn't that technically no longer considered a "meta pool" making meta pool related issues obsolete?

**Comment by malik672** [comment]
> In Vyper, like Solidity, uninitialized values are meant to default to zero. This doesn't always happen though and will sometimes point to garbage memory. Their way of fixing this was to make initialization mandatory during compilation (ie `uint reserve_0 = 0;`), but this isn't enforced for arrays. Forge also doesn't have a Vyper compiler and would be using the bytecode for the Curve Pool when it creates a new one from the factory.
> 
> One possible fix would be to create a mock of the Curve Pool contract in solidity for testing and local environments.

no for solidity all default values are always zero, initializing to zero, will just cost more gas, even uniswap does not initialize to zero

**Comment by 0x4007** [comment]
> no for solidity all default values are always zero, initializing to zero, will just cost more gas, even uniswap does not initialize to zero

Thanks for the tip!

**Comment by rndquu** [comment]
After we moved to the diamond architecture we don't have the [method](https://github.com/ubiquity/ubiquity-dollar/blob/53b40102fd5d748dd92364955c81e7f7c82ef285/packages/contracts/src/dollar/core/UbiquityDollarManager.sol#L74) which caused the original issue in the codebase anymore so I think we can close the current issue.
