### ISSUE TITLE
`prettier` in `package.json` calling `forge fmt`

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#516]
I just realized that this could be causing the discrepancy with the formatting. Because this task is named "prettier" it is possible that lint-staged is calling this instead of what we expect.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/pull/417#discussion_r1085080563_

---
```
 "devDependencies": {
    "cspell": "latest",
    "prettier": "latest",
    "prettier-plugin-solidity": "latest"
  }
```

if we agree to keep prettier over forge fmt we need to :
1 - add the dev dependencies as stated above 
2 - update the overrides section of the  .prettierrc in the root folder

_Originally posted by @zgorizzo69 in  https://github.com/ubiquity/ubiquity-dollar/pull/417#issuecomment-1400977221_

**Comment by 0x4007** [comment]
@zgorizzo69 can you clarify what exactly you think I should do for 

> update the overrides section of the .prettierrc in the root folder

I basically already handled this in my mega PR. Here's the commit with the latest change https://github.com/ubiquity/ubiquity-dollar/blob/91db6ed9376c7fe1480a9b063e44c94d61a583ac/packages/contracts/package.json

**Comment by pavlovcik** [comment]
@0xcodercrane the bounty bot messed up the calculation here. Can you study what happened?

**Comment by FibrinLab** [comment]
<img width="306" alt="Screenshot 2023-02-01 at 06 18 36" src="https://user-images.githubusercontent.com/87988127/215957932-2be8c28d-8b61-452d-bd8c-5bd0f20578ef.png">
I think this is causing the formatting errors for the solidity files. 

@pavlovcik

**Comment by FibrinLab** [comment]
@pavlovcik Currently working on issue 

> <img alt="Screenshot 2023-02-01 at 06 18 36" width="306" src="https://user-images.githubusercontent.com/87988127/215957932-2be8c28d-8b61-452d-bd8c-5bd0f20578ef.png">
> 
> I think this is causing the formatting errors for the solidity files.
> @pavlovcik

Maybe try just using tab_width = 4 with the formatter. I believe it defaults to 2

**Comment by 0x4007** [comment]
> @pavlovcik Currently working on issue

This is assigned to me so don't worry about it.

@FibrinLab we will not use `forge fmt`. We will only use `prettier` so I'm planning to just delete that config.

**Comment by molecula451** [comment]
mind unassing if not working on the issue?

**Comment by 0x4007** [comment]
> mind unassing if not working on the issue?

If you can follow up in a couple of days and there are no updates then we can assign you!

**Comment by molecula451** [comment]
> > mind unassing if not working on the issue?
> 
> If you can follow up in a couple of days and there are no updates then we can assign you!

I just follow up, it looks like assignee it's not working on it after all

https://github.com/ubiquity/ubiquity-dollar/pull/685

**Comment by ghost** [comment]
imma make a PR soon

**Comment by ghost** [comment]
> I just realized that this could be causing the discrepancy with the formatting. Because this task is named "prettier" it is possible that lint-staged is calling this instead of what we expect.
> 
> _Originally posted by @pavlovcik in [#417 (comment)](https://github.com/ubiquity/ubiquity-dollar/pull/417#discussion_r1085080563)_
> 
> ```
>  "devDependencies": {
>     "cspell": "latest",
>     "prettier": "latest",
>     "prettier-plugin-solidity": "latest"
>   }
> ```
> 
> if we agree to keep prettier over forge fmt we need to : 1 - add the dev dependencies as stated above 2 - update the overrides section of the .prettierrc in the root folder
> 
> _Originally posted by @zgorizzo69 in [#417 (comment)](https://github.com/ubiquity/ubiquity-dollar/pull/417#issuecomment-1400977221)_

hey,
can u tell which thing in override i gotta change 
on reading the above talk i see we gotta put tab width 4 which it is already 
``` "overrides": [
    {
      "files": "*.sol",
      "options": {
        "printWidth": 80,
        "tabWidth": 4,
        "useTabs": false,
        "singleQuote": false,
        "bracketSpacing": false
      }
    }
  ]

**Comment by ghost** [comment]
@pavlovcik im gonna push the changes to #681

**Comment by rndquu** [comment]
> @pavlovcik im gonna push the changes to #681

Pls create a separate PR, no need to clutter https://github.com/ubiquity/ubiquity-dollar/pull/681

**Comment by ghost** [comment]
> > @pavlovcik im gonna push the changes to #681
> 
> Pls create a separate PR, no need to clutter #681

oh sure i reverted the PR gonna make a separate

**Comment by molecula451** [comment]
> @molecula451 The time limit for this bounty is on Tue, 20 Jun 2023 15:58:51 GMT

https://github.com/ubiquity/ubiquity-dollar/pull/685
