### ISSUE TITLE
Corrupted HTML Structure on Login Animation Component 

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#517]
This unfortunately slipped through because our UbiquiBot was down. The animation from https://github.com/ubiquity/ubiquity-dollar/pull/477 introduced a non matching tag error for the React component. This throws an error in the UI console. 

I spoke with @Steveantor in the dms about it so making this issue as a formality.

**Comment by FibrinLab** [comment]
Still an active issue?

**Comment by 0x4007** [comment]
Yes it was never completed.

**Comment by FibrinLab** [comment]
> Yes it was never completed.

Alright will work on this after the ERC1155Uri bounty
