### ISSUE TITLE
Expose RPC URL from github action runner

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#526]
Depends on: https://github.com/ubiquity/ubiquity-dollar/pull/417

What should be done:
1. When https://github.com/ubiquity/ubiquity-dollar/pull/417 is ready we should deploy contracts in their initial state when ["deploy test blockchain" workflow](https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/workflows/deploy-anvil.yml) starts. The "deploy test blockchain" workflow can be started only manually.
2. When user runs the "deploy test blockchain" workflow it should print the deployed RPC URL in the workflow logs so that everybody could connect to that test node.

**Comment by 0x4007** [comment]
> When user runs the "deploy test blockchain" workflow it should print the deployed RPC URL in the workflow logs so that everybody could connect to that test node.

I wonder if the best way to have the beta testing UI populate these for the user would be to scrape and parse the logs?

**Comment by rndquu** [comment]
> > When user runs the "deploy test blockchain" workflow it should print the deployed RPC URL in the workflow logs so that everybody could connect to that test node.
> 
> I wonder if the best way to have the beta testing UI populate these for the user would be to scrape and parse the logs?

This needs further research. For the 1st "private testnets" feature iteration user needs to find out RPC URL in the github action logs. But yes, plain old web scraping could be an option.

**Comment by 0x4007** [comment]
>  But yes, plain old web scraping could be an option.

I presume we can access the logs via the API as well so with a simple regular expression we should be able to handle this pretty easily.

**Comment by gitcoindev** [comment]
Hi I found a way to achieve this, my QA is here: https://github.com/gitcoindev/ubiquity-dollar/issues/1

The solution was to parse Anvil logs and write the GitHub actions URL to a file. I also created an artifact with the URL, which is created after the job completes, but for testing the running instance the URL is added as a GitHub comment.

**Comment by 0x4007** [comment]
> The solution was to parse Anvil logs and write the GitHub actions URL to a file. I also created an artifact with the URL, which is created after the job completes, but for testing the running instance the URL is added as a GitHub comment.

Sounds epic. @rndquu do you think you can take a look into the QA?
