### ISSUE TITLE
Create UI for custom RPC methods

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#528]
When user wants to test a PR he should be able to update blockchain's state for testing purposes.

Anvil provides custom RPC methods for better testing: [https://book.getfoundry.sh/reference/anvil/#custom-methods](https://book.getfoundry.sh/reference/anvil/#custom-methods)

What should be done:

1. Add "Custom RPC methods" button to the bottom of the https://uad.ubq.fi/ (button should be hidden for production builds)
2. On "Custom RPC methods" click popup should be opened where user can send txs for the following RPC methods:
- anvil_impersonateAccount
- anvil_stopImpersonatingAccount
- anvil_setBalance
- anvil_setStorageAt
- anvil_dumpState
- anvil_loadState
- evm_increaseTime
- eth_sendTransaction

**Comment by Keyrxng** [comment]
First time contributor so I'm hoping to get this assigned and I'll have a pr ready for the beginning of the week, cheers!

**Comment by rndquu** [comment]
> First time contributor so I'm hoping to get this assigned and I'll have a pr ready for the beginning of the week, cheers!

Pls try to self assign again via `/assign`

**Comment by rndquu** [comment]
> /assign

Try the `/start` command :) I've totally forgotten that we'd refactored it

**Comment by Keyrxng** [comment]
thanks rndquu!

**Comment by rndquu** [comment]
> ### [ **rndquu: [ CLAIM 0 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMCJ9LCJub25jZSI6IjUzMzg1NjQwOTY3OTU1MjcxNTc1OTg1NjM2MjkzNzM4NzAyMjQyNTU1MjI3ODg2MDI4NTQ2NTQ2ODAyMzI2NzIwMTM3NTA1NzAwMTA3IiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHgzMzZDMDMzODQyRkEzMTZkNDcwZTgyMGM4MWI3NDJlNjJBMDc2NURDIiwicmVxdWVzdGVkQW1vdW50IjoiMCJ9LCJvd25lciI6IjB4Zjg3Y2E0NTgzQzc5MjIxMmU1MjcyMGQxMjdFN0UwQTM4QjgxOGFEMSIsInNpZ25hdHVyZSI6IjB4N2UyNGZmMjIzOGFlMzhhMzMxNmFkMzgzOWEzZGVmMzhhMzdiNzZhMzZiN2I2NzMxM2Y3NDkwNDE2YjBlMmU3MjJkZGE1NjM2MzA2YTI3MWRkOGQ4ODJjZmY3MTUyZTBkMzQzMzM2NGM1ZTllZmZlZmM0ZjNhZTY0NDkwZmUzYmExYyJ9&network=100)

Note to self: already addressed here https://github.com/ubiquity/ubiquibot/issues/632

**Comment by 0x4007** [comment]
This fix should be rolled out within a few days. There is an open pull request to sync `development` to `main`.
