### ISSUE TITLE
Cloudflare Pages Takes 20 Minutes to `Build foundry from the github source code`

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#529]
Not sure why that is but I just watched the logs and its painfully slow. We should just wget/curl a compiled binary for Cloudflare CI. 

You should consider the timestamps in the logs and optimize whatever is taking a long time with sensible solutions for this bounty.

Logs from 8b8a91d292183b4ff5d8566c02c5fc8f727fe798 for reference. [ubiquity-dollar.6a4973f9-ef0b-49ae-aaac-90a39d0479f5.log](https://github.com/ubiquity/ubiquity-dollar/files/10539895/ubiquity-dollar.6a4973f9-ef0b-49ae-aaac-90a39d0479f5.log)

**Comment by 0x4007** [comment]
I might take this tomorrow I just wanted to be sure to write it here so I don't forget about it.

**Comment by 0x4007** [comment]
Update: Cloudflare CI/CD just plain broke. I don't pay so they don't give support. I posted in their community but we unfortunately might have to eject Cloudflare CI from our process. 

https://community.cloudflare.com/t/ci-cd-crashed-and-is-permanently-queued/472435/2

**Comment by 0x4007** [comment]
@Steveantor can you share your wallet address? Thanks for looking into this.

**Comment by Steveantor** [comment]
Here's my address:
`0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
@pavlovcik

**Comment by 0x4007** [comment]
> Here's my address:
> `0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE`
> @pavlovcik

https://etherscan.io/tx/0xdb02dc2dc3dfe41eee846fc5c7a29bf920b36ec7ba050c39d6864b3d36eef549
https://etherscan.io/tx/0x6464711d36bdc8de72a17237a776186e002bece979189c57a489b24074261578
