### ISSUE TITLE
Fix revert of getCreditAmount() in CreditRedemptionCalculator

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#535]
Afther merging this PR https://github.com/ubiquity/ubiquity-dollar/pull/417 the following test for https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/CreditRedemptionCalculator.sol#L45 reverts without error:
```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.16;

import "../../../src/dollar/core/CreditRedemptionCalculator.sol";
import "../../helpers/LocalTestHelper.sol";

contract CreditRedemptionCalculatorTest is LocalTestHelper {
    CreditRedemptionCalculator creditCalc;

    function setUp() public override {
        super.setUp();
        creditCalc = new CreditRedemptionCalculator(manager);
    }

    function testGetCreditAmount_ShouldReturnAmount() public {
        uint amount = creditCalc.getCreditAmount(1 ether, 10);
        assertEq(amount, 9999999999999999999);
    }
}
```

The test reverts when trying to convert `bytes16` to `uint256` on this line https://github.com/abdk-consulting/abdk-libraries-solidity/blob/9e69beb255e2f87d67b44047dae229ba42ee9a64/ABDKMathQuad.sol#L135

Check this line: https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/CreditRedemptionCalculator.sol#L58

Considering values in the test above the math is the following:
```
bytes16 op = (_coef.fromUInt().mul(multiplier.ln())).exp();

multiplier = blockHeightDebt / curBLock = 10 / 5 = 2
_coef = 1000000000000000000
op = 2^(1000000000000000000 * 2) = 2^2000000000000000000
```

So `uint256` can't hold `2^2000000000000000000` so the test reverts.

Previous contract version (that worked fine): https://github.com/rndquu/ubiquity-dollar/blob/ff39e908247463b2eabf2d6c8442ccd495be1687/packages/contracts/src/dollar/core/CreditRedemptionCalculator.sol
Current contract version (which reverts): https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/CreditRedemptionCalculator.sol

What should be done:
- find math docs (or compare with the previous contract version) and fix the error
- add test for `getCreditAmount()`

**Comment by 0x4007** [comment]
We should try moving to permits for these smaller transactions. Would be cool if we can stack permits to consolidate transactions.
