### ISSUE TITLE
logic problem inside creditNFT / updateTotalDebt

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#557]
https://github.com/ubiquity/ubiquity-dollar/blob/95cca1bc97bae16d9c178662c4340a2ba364238d/packages/contracts/src/dollar/core/CreditNft.sol#L112
Before the while loop we are setting `outstandingDebt` to be `_totalOutstandingDebt`
```
 uint256 outstandingDebt = _totalOutstandingDebt;
```
and after we are setting `_totalOutstandingDebt` to be `outstandingDebt` although we are not modifiying `outstandingDebt` inside the loop ..and we are updating  `_totalOutstandingDebt` for nothing as it will be overridden after the loop

**Comment by sergfeldman** [comment]
@peepo
