### ISSUE TITLE
ensure the deploy script is working

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#559]
after checkout the dev branch if you follow the readme to deploy locally you will face several errors the goal is to fix them

**Comment by zgorizzo69** [comment]
I will do it @pavlovcik if it is ok

**Comment by 0x4007** [comment]
@hashedMae just walked me through this one right now we're about to merge which should make deployment stable. 


https://github.com/ubiquity/ubiquity-dollar/pull/554

**Comment by zgorizzo69** [comment]
awesome make sure the readme is correct cos right now if you follow the steps it doesn't work

**Comment by 0x4007** [comment]
If you want to clean it up further go ahead though but I think the instructions work now.
