### ISSUE TITLE
StakingToken external function to modify setURI

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#561]
Renamed from StakingShare to StakingToken...

yep it is used inside stakingshare which inherits ERC1155SetUri which provide an internal _setURI however stakingShare does not include an external function to modify setURI should we open an issue to add that feature ?

_Originally posted by @zgorizzo69 in https://github.com/ubiquity/ubiquity-dollar/pull/398#discussion_r1102560290_

**Comment by 0x4007** [comment]
Should include functionality, and have tests.

**Comment by FibrinLab** [comment]
@pavlovcik i worked on the stakingshare test issue. So basically should the "seturi" now be an external function with more tests?

**Comment by 0x4007** [comment]
> @pavlovcik i worked on the stakingshare test issue. So basically should the "seturi" now be an external function with more tests?

That's correct. Needs to also include our access control for minter role only having access to change.

**Comment by FibrinLab** [comment]
> > @pavlovcik i worked on the stakingshare test issue. So basically should the "seturi" now be an external function with more tests?
> 
> That's correct. Needs to also include our access control for minter role only having access to change.

Would love to have a look after I am done with the issue I am working on

**Comment by FibrinLab** [comment]
@pavlovcik This issue has already been fix. I worked on this in another issue.

**Comment by rndquu** [comment]
Closing this one because it is already [implemented](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/StakingShare.sol#L212)
