### ISSUE TITLE
cspell ci

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#562]
For some reason cspell doesn't seem to run for any one for the pre-commit hook. 

This bounty is for the cspell to be handled along the husky pre-commit hook.

**Comment by Steveantor** [comment]
I think #575 resolved this

**Comment by 0x4007** [comment]
#575 is in the CI (on GitHub Actions) this bounty is for it to be handled within the husky pre-commit hook.

**Comment by Steveantor** [comment]
> #575 is in the CI (on GitHub Actions) this bounty is for it to be handled within the husky pre-commit hook.

I see

**Comment by BeanieMen** [comment]
any steps to reproduce the issue?

**Comment by molecula451** [comment]
There must be a balance between if we want to enforce this husky package. I would close this issue as not planned as it is potentially adding complexity to the project and maintainability issues due to lack of input and requirements && and a possible future resurrection inviting the hunter @AnakinSkywalkeer

**Comment by molecula451** [comment]
Closing as not planned.

Reasons:

- Potentially adding **_UNWATED_** complexity
- Needs input beyond the actual requirements
- Further feedback
- It might be re-opened in a future if need it!

**Comment by 0x4007** [comment]
I'll need to send some xDAI to both participants because this was my fault for not ensuring that the bounty is valid. 

https://gnosisscan.io/tx/0x3162608e9e18f71b4b29b0780904b664d160d0d79b0f761569f0d590b5f16044 @me505 
https://gnosisscan.io/tx/0xbb9e74ab8951f5cc45fb38dd1d56f7e04e3c0ba6db98bfbaf58bfe63043d950a @AnakinSkywalkeer
