### ISSUE TITLE
Invariant Testing

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#563]
We should implement invariant testing for [LibUbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/a1b11e1b944227144d7cc19ab320220d9fce8b69/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol). 

So collaborator who's going to take this issue should carefully study the  [LibUbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/a1b11e1b944227144d7cc19ab320220d9fce8b69/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol) and think of the invariants that should be tested.

Invariants could be:
- user can not mint more Dollars in USD than provided collateral
- user can not redeem more collateral in USD than provided Dollar tokens
- https://github.com/ubiquity/ubiquity-dollar/issues/925#issuecomment-2128859442

Possible solutions for invariant testing (I would simply start with foundry since we're using it as a development framework + it also contains fuzz testing):
- https://book.getfoundry.sh/forge/invariant-testing
- https://github.com/crytic/echidna
- https://github.com/crytic/medusa

What should be done:
1. Impelent invariant tests for the  [LibUbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/a1b11e1b944227144d7cc19ab320220d9fce8b69/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol) contract (you may create them in a separate test file like `UbiquityPoolFacet.invariant.t.sol` so we could distinguish unit, fuzz and invariant tests)
2. Setup testing CI this way:
a) On PR invariant tests should run with a small number of runs (so that we could merge PRs fast)
b) On merge to the `development` branch invariant tests should run with a great number of runs to test many cases (keep in mind that github action runnners can run for 6 hours)

Original description:
```
Determine if this is beneficial for us:

https://twitter.com/PaulRBerg/status/1624014054254690304
https://github.com/foundry-rs/book/pull/760

---

https://twitter.com/gakonst/status/1624146214412521483?s=46&t=gH3q4dow54h4x7JQWCQSeg
```

**Comment by hashedMae** [comment]
We would have to determine if the protocol has any hard and fast rules like Uniswap's x*y=k. I don't think it's useful for the entire protocol but if we can find any "rules" within the protocol that we would expect to persist no matter the conditions then invariant testing would be useful to stress test those.

**Comment by 0x4007** [comment]
Perhaps @zgorizzo69 might have some ideas. I haven't personally done the deep dive on what exactly invariant testing is but after I do I would have an opinion on it.

**Comment by malik672** [comment]
@pavlovcik is this still open

**Comment by 0x4007** [comment]
I think the research is useful but it's @rndquu's decision if this bounty is invalidated.

**Comment by rndquu** [comment]
> I think the research is useful but it's @rndquu's decision if this bounty is invalidated.

I would close the following tasks (including the current issue):
- https://github.com/ubiquity/ubiquity-dollar/issues/587
- https://github.com/ubiquity/ubiquity-dollar/issues/563
- https://github.com/ubiquity/ubiquity-dollar/issues/515
- https://github.com/ubiquity/ubiquity-dollar/issues/291

All of them will be part of a [security epic](https://github.com/ubiquity/ubiquity-dollar/issues/639#issuecomment-1554194502) which we will break down into small tasks

@pavlovcik ok?

**Comment by 0x4007** [comment]
Just to clarify, you want to create a meta-issue with these as new subtasks? What's the benefit of remaking all of them vs just manually compiling them in a single new issue?

**Comment by rndquu** [comment]
> Just to clarify, you want to create a meta-issue with these as new subtasks?

yes

> What's the benefit of remaking all of them vs just manually compiling them in a single new issue?

I don't really understand the question. We can't compile all of them in a single issue because each of those tasks is pretty time consuming.

**Comment by 0x4007** [comment]
> > Just to clarify, you want to create a meta-issue with these as new subtasks?
> 
> 
> 
> yes
> 
> 
> 
> > What's the benefit of remaking all of them vs just manually compiling them in a single new issue?
> 
> 
> 
> I don't really understand the question. We can't compile all of them in a single issue because each of those tasks is pretty time consuming.
> 
> 
> 
> 

I meant creating a new blank issue, and then linking all of the existing sub issues in a checklist. 

The blank issue is now your "meta-issue"

---

The alternative is that you mark all of the issues as unplanned, then create a blank issue with a checklist, and then recreate all the sub tasks. 

Both will produce the same outcome but one should be much faster to do, if it works like that.

**Comment by rndquu** [comment]
> I meant creating a new blank issue, and then linking all of the existing sub issues in a checklist.

I meant the same flow

**Comment by 0x4007** [comment]
> > I think the research is useful but it's @rndquu's decision if this bounty is invalidated.
> 
> I would close the following tasks (including the current issue):
> 
> * [Echidna Properties #587](https://github.com/ubiquity/ubiquity-dollar/issues/587)
> * [Invariant Testing #563](https://github.com/ubiquity/ubiquity-dollar/issues/563)
> * [Deep Fuzzing on Newly Modified Solidity Files #515](https://github.com/ubiquity/ubiquity-dollar/issues/515)
> * [Make echidna working #291](https://github.com/ubiquity/ubiquity-dollar/issues/291)
> 
> All of them will be part of a [security epic](https://github.com/ubiquity/ubiquity-dollar/issues/639#issuecomment-1554194502) which we will break down into small tasks
> 
> @pavlovcik ok?

Can you handle this @rndquu ?

**Comment by rndquu** [comment]
> > > I think the research is useful but it's @rndquu's decision if this bounty is invalidated.
> > 
> > 
> > I would close the following tasks (including the current issue):
> > 
> > * [Echidna Properties #587](https://github.com/ubiquity/ubiquity-dollar/issues/587)
> > * [Invariant Testing #563](https://github.com/ubiquity/ubiquity-dollar/issues/563)
> > * [Deep Fuzzing on Newly Modified Solidity Files #515](https://github.com/ubiquity/ubiquity-dollar/issues/515)
> > * [Make echidna working #291](https://github.com/ubiquity/ubiquity-dollar/issues/291)
> > 
> > All of them will be part of a [security epic](https://github.com/ubiquity/ubiquity-dollar/issues/639#issuecomment-1554194502) which we will break down into small tasks
> > @pavlovcik ok?
> 
> Can you handle this @rndquu ?

I didn't forget about this task

We first need to remove mocks from the contracts because it doesn't make sense in fuzzing Dollar contracts which use mocks under the hood

I'll break down the "remove mocks" epic into subtasks soon

**Comment by molecula451** [comment]
@rndquu this taks has "DevOps" label it's this expected to perform on CI or only local?

**Comment by rndquu** [comment]
> @rndquu this taks has "DevOps" label it's this expected to perform on CI or only local?

Invariant testing is a subpart of fuzzing tests which we already [run](https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/workflows/deep-fuzz.yml) on CI on push to the `development` branch. So I think for invariant tests we could use the same strategy (running on CI on push to the `development` branch).

**Comment by alexandr-masl** [comment]
Hey everyone, I've also started the UI testing issue [#257](https://github.com/ubiquity/ubiquity-dollar/issues/257)
However, since it still needs to pass some checks and isn't ready to be picked up yet, should I unassign myself from it while I work on this one ?

**Comment by 0x4007** [comment]
You can be assigned to both.

**Comment by alexandr-masl** [comment]
Hi @0x4007, @rndquu, and team,

I wanted to follow up regarding [my pull request](https://github.com/ubiquity/ubiquity-dollar/pull/953) that addresses this issue. I wanted to check if there are any updates or further changes needed from my end to move this forward. Any feedback or guidance would be greatly appreciated

**Comment by rndquu** [comment]
> Hi @0x4007, @rndquu, and team,
> 
> I wanted to follow up regarding [my pull request](https://github.com/ubiquity/ubiquity-dollar/pull/953) that addresses this issue. I wanted to check if there are any updates or further changes needed from my end to move this forward. Any feedback or guidance would be greatly appreciated

Hey, sorry for a long response, I'll check it today

**Comment by alexandr-masl** [comment]
I have been unassigned from the issue for some reason. Could you please provide any clarification ?

**Comment by rndquu** [comment]
> I have been unassigned from the issue for some reason. Could you please provide any clarification ?

As far as I understand the `ubiquity-os` bot unassigned you because there was some period of inactivity

**Comment by 0x4007** [comment]
> > I have been unassigned from the issue for some reason. Could you please provide any clarification ?
> 
> 
> 
> As far as I understand the `ubiquity-os` bot unassigned you because there was some period of inactivity

I think it doesn't read draft pulls right now. This will be fixed soon. Also strange it didn't warn at 3.5 days. @gentlementlegen

**Comment by alexandr-masl** [comment]
Hey, please let me know if any further changes are expected from my side to move this forward
