### ISSUE TITLE
Diamond junk code optimization

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#564]
> How much of Solidity's generated code is junk?

> On average, a third of the generated code can be removed, resulting in significant gas savings and increased network throughput.

> In some cases (esp. with 💎 pattern) over 90% of the generated code is junk.

> eips.ethereum.org/EIPS/eip-2535

https://twitter.com/dedaub/status/1624146336240046092?s=46&t=DRwufshieKnkPQ95Q65TEw

https://medium.com/@sifislag/2a9c13d0b98e?source=friends_link&sk=82245f0b858a6853ccbecf047c16c7dc

**Comment by Eren-Yeaager** [comment]
Can u assign me this issue?

**Comment by Eren-Yeaager** [comment]
thank you [pavlovcik]

**Comment by Eren-Yeaager** [comment]
hi @pavlovcik  actually had a doubt ..... do i need to optimize every contract present in the code base???
