### ISSUE TITLE
Refactoring Tests to use `vm.createSelectFork()` 

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#571]
This fails in CI cause of the lack of `.env`
I preserved the pattern above by commenting it out but have reverted to just using 
```mainnet = vm.createSelectFork("https://eth.ubq.fi/v1/mainnet");```

It'd be a seperate issue but refactoring our tests to use `vm.createSelectFork()` instead of passing it as a flag in the CLI might be worthwhile.

_Originally posted by @hashedMae in https://github.com/ubiquity/ubiquity-dollar/pull/531#discussion_r1106308807_

**Comment by hashedMae** [comment]
I'll do it but my price is 400

**Comment by hashedMae** [comment]
None of the current tests are using a fork environment. Instead, tests like for `TWAPOracleDollar3Pool` that relies on `CurveFactory` is testing a `MockTWAPOracle` instead of the actual contract. I don't know how many tests are following this pattern but it means that multiple contracts are currently untested.

**Comment by 0x4007** [comment]
It sounds like we should create a new bounty? Unfortunately I don't understand deeply enough to write the specification and would need help to create the issue.

**Comment by hashedMae** [comment]
I'll crawl through tonight to find all the offending tests and write an issue

**Comment by rndquu** [comment]
[according to](https://github.com/ubiquity/ubiquity-dollar/issues/630#issuecomment-1532432806) @hashedMae we can close this one because it is already a part of the other [issue](https://github.com/ubiquity/ubiquity-dollar/issues/630)
