### ISSUE TITLE
Extract dollar form diamond and improve access control granularity for all tokens

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#577]
we should extract the dollar ERC20 from the diamond and the access control from the diamond should be injected in the constructor
- add the dollar address inside the manager facet
- adapt all the facets and tests that reference it 
- create new burn and mint  roles for each of the ubiquity token

the dollar should be behind a UUPS proxy in order to be able to upgrade it ( we should have the tests improved to assess the upgradability)

**Comment by 0x4007** [comment]
It isn't clear to me if this is also including the creation of the new manager for only tokens.
