### ISSUE TITLE
Echidna Properties

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#587]
https://github.com/crytic/properties/blob/main/PROPERTIES.md#erc20

**Comment by 0x4007** [comment]
Need to know if useful and if so add them

**Comment by FibrinLab** [comment]
Is this still am active issue? Any additional details?

**Comment by 0x4007** [comment]
@rndquu

**Comment by rndquu** [comment]
> Is this still am active issue? Any additional details?

Sorry, this will be a core team issue, pls check other issues to solve

**Comment by rndquu** [comment]
Closing in favour of https://github.com/ubiquity/ubiquity-dollar/issues/563
