### ISSUE TITLE
development deploy should either use ENV or constant/mnemonic 

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#588]
if you only have `PRIVATE_KEY` set in env and run `yarn workspace @ubiquity/contracts deploy:development` it will fail cos it takes your private key and use the mnemonic test to get the publickey

**Comment by Steveantor** [comment]
> Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`

There's a linked PR
