### ISSUE TITLE
Upgrade Conventional Commits CI to support GitHub webapp commit messages

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#590]
I guess we need to upgrade our conventional commits CI to support GitHub webapp commit messages.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/586#issuecomment-1450904927_

**Comment by rndquu** [comment]
How did you manage to create such commit message `Update packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts` via github UI ?

I tried both editing with codespaces and "in place editing" and everywhere there was an option to write a proper commit message, but `Update packages/contracts/scripts/deploy/manager/DiamondDeployHelper.ts` seems to be auto generated.

**Comment by 0x4007** [comment]
Looks like @zgorizzo69 did that and can provide a clarification here.

I know there is one more way to edit via the GitHub UI that he might have done. In my review, there is a "suggestion" function where I can "suggest" to change the code directly. Then the reviewee can easily press a button to write the changes all from the PR review UI.

**Comment by zgorizzo69** [comment]
i just accepted and commited the changes it was not clear how / what test will be used for the commit message
