### ISSUE TITLE
Autosync development-ci branch

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#603]
Problem: right now when a bounty hunter opens a PR which updates the CI (example: https://github.com/ubiquity/ubiquity-dollar/pull/574) then we should:
1. Merge PR to the `development` branch
2. Check that the feature actually works

Ideally we should test such PRs without merging to the `development` branch.

So the expected flow for bounty hunters will be:
1. If the PR is connected with the CI then bounty hunter should open it to the `development-ci` branch first
2. We test the issue
3. The PR is reopened to the `development` branch and merged

What should be done:
1. Create a `development-ci` branch
2. Add a github action that autosyncs new updates from the `development` branch to the `development-ci` branch (example: https://github.com/pavlovcik/dao.ubq.fi/blob/677a373a263ce1ffd0239201f74bebfdac0e1f01/.github/workflows/sync.yml)
3. Update docs (or bounty hunter's readme) so that they know the desired flow for PRs connected with the CI

**Comment by BeanieMen** [comment]
sorry

**Comment by nopeless** [comment]
@rndquu , I'd like to suggest some extra specifications

Automatic merging is usually not a great idea (example: if two people edit the same file, git cannot automatically merge the two edits, or at least require a human to review it). And sometimes, the two edits will be merged but result in logical errors

The absolute easiest way to prevent these merges would be restricting CI workflow file edits to `development-ci` and non-workflow source files to `development`. However, this is not practical and would be too cumbersome. Additionally, the constant merging will create many merge commits that muddles the git history

Thus, I suggest a few things that achieves this `development-ci` bifurcation

1. Using **rebase**: `development-ci` rebases `development` branch's commits on itself (sometimes this process can fail, and requires manual intervention. Rather rare scenario)
2. Keeping parallel PRs: For each PR to CI, a copy of the PR is made by a github action such as <https://github.com/marketplace/actions/create-pull-request>. 

The single `development-ci` branch strategy has its downsides that are negligible

Such as:

> Two bounty hunters working on the same workflow file, thus not being able to determine who's workflow it is

This can be solved by only merging and observing one PR at a time.

Here is my proposal in a diagram form

![development-ci drawio](https://github.com/ubiquity/ubiquity-dollar/assets/38830903/c329cf2c-6041-4b8d-8c41-5807e0cccbb7)


P.S. I am helping @me505

**Comment by rndquu** [comment]
@nopeless hi, thank you for a thoughtful input

> Using rebase: development-ci rebases development

ok

> step 1 - original pull request

On step 1 it is better if bounty hunter opens a PR directly to the `development-ci` branch (without opening a parallel PR). This way we don't clutter UI with 2 identical PRs to different branches

Overall the provided schema is fine

**Comment by nopeless** [comment]
> On step 1 it is better if bounty hunter opens a PR directly to the `development-ci` branch (without opening a parallel PR). This way we don't clutter UI with 2 identical PRs to different branches
> 

This is also has a partial downside, a PR cannot be "merged twice". So for example, if a workflow update proposal forgot to add a build step before deploying, the bounty hunter would have to make another PR. This is totally viable as well.

I personally don't mind closed bot PRs (dependabot, allcontributors etc)

If application integration is on the table then
another way of achieving this would be having a pseudo merge, where a maintainer would issue a command such as `/merge` that simulates the github pull request merge

Here is a diagram with the suggestions @rndquu 

![development-ci v2 drawio](https://github.com/ubiquity/ubiquity-dollar/assets/38830903/5e9da2ca-e442-4b2d-ba1d-9848f012e839)

**Comment by rndquu** [comment]
There is too much overhead for a new `/merge` command

We are ok with merging/opening PRs manually

So, again, the process should look similar to this:
1. Bounty hunters opens a PR to the `development-ci` branch (which is synced with the `development` branch) and we merge the PR
2. We test a feature
3. If it is fine then we `git checkout development && git rebase development-ci` else we revert the merged PR in the `development-ci` branch

**Comment by nopeless** [comment]
backlog: it was cherry-pick, not rebase.

However, it seemed that cherry-pick was a little overkill as development-ci would constantly be in sync anyway. So, opted in for the original merge strategy. Works just fine, hopefully it won't cause many issues
