### ISSUE TITLE
Diamond refactoring  / merge deployment script

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#605]
After merging #600 we can have only one deployment script as the previous tokens has been deleted 
- [ ]  merge the  two deployment script to have only one that act as the actual forge script for development but that will deploy

**Comment by zgorizzo69** [comment]
> @ubiquity-bounties would you please post your wallet address here?

0x10693e86f2e7151b3010469e33b6c1c2da8887d6

**Comment by 0x4007** [comment]
> 0x10693e86f2e7151b3010469e33b6c1c2da8887d6

https://etherscan.io/tx/0x6d9f922fea69e5ffb945d803453a07fbd40b3c68b0a6fe3404958ef7d5e3ef3f
