### ISSUE TITLE
Add ZAP to collateral contract

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#610]
There is the [UbiquityPoolFacet](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol) contract which allows users to:
- transfer any ERC20 tokens to the contract in exchange for `uAD` 
- redeem `uAD` tokens from the contract in exchange for the collateral ERC20 tokens

We should have the ability to swap any ERC20 token to `LUSD` under the hood when user [deposits](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L17) collateral in order to mint `uAD`. 

Notice that:
- swaps should be made via the [CoW Swap](https://swap.cow.fi/).
- there might be edge cases on [mint](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L17) or [redeem](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L33) when there is not enough liquidity in the pools

Original description:
- we want user to be able to **ZAP** In any token to be swapped to `LUSD` to retrieve `uAD` as described in #609

**Comment by 0x4007** [comment]
I assume 1. that we can fork how zapper does it 2. they call Uniswap to complete the transaction.

**Comment by hashedMae** [comment]
Didn't someone build a ZAP contract for another feature before? If not this one should be built in a more extendable manner, so it'd be able to ZAP to any of our existing or future contracts. Instead of having to build a bespoke zapper for each one.

**Comment by 0x4007** [comment]
@zapaz built the zap lol

Check out the Instadapp codebase under our organization.

**Comment by zorglob21** [comment]
Is this issue still open?

**Comment by 0x4007** [comment]
https://github.com/ubiquity/ubiquity-instadapp/tree/master/backend/contracts/mainnet

I just reviewed the old code to refresh my memory. 
- It was built to be used inside of Instadapp. 
- It is designed to allow users to instantly start farming our governance tokens (zap in) and then to also be able to zap out. 
- This does not leverage Uniswap/Curve for swapping tokens so perhaps it is non applicable. Sorry about that!

**Comment by rndquu** [comment]
This issue https://github.com/ubiquity/ubiquity-dollar/issues/609 added the ability for users to:
1. Transfer ERC20 tokens to the contract in exchange for UAD
2. Redeem UAD tokens from the contract in exchange for the collateral ERC20 tokens

> we want user to be able to ZAP In any token to be swapped to $LUSD to retrieve uAD as described in https://github.com/ubiquity/ubiquity-dollar/issues/609

So this issue describes this feature:
1. User should be able to transfer any collateral ERC20 token
2. Under the hood the collateral is swapped for LUSD

On step 2 we need to swap collateral ERC20 tokens for LUSD using any audited DEX aggregator, like [1inch](https://app.1inch.io/)

Is the description correct?

**Comment by molecula451** [comment]
zapping smells flashloan like

**Comment by 0x4007** [comment]
> On step 2 we need to swap collateral ERC20 tokens for LUSD using any audited DEX aggregator, like [1inch](https://app.1inch.io/)
> 
> 
> 
> Is the description correct?

Seems all correct but I would pick [CoW Swap](https://swap.cow.fi)

**Comment by rndquu** [comment]
> > On step 2 we need to swap collateral ERC20 tokens for LUSD using any audited DEX aggregator, like [1inch](https://app.1inch.io/)
> > Is the description correct?
> 
> Seems all correct but I would pick [CoW Swap](https://swap.cow.fi)

Updated description

**Comment by 0x4007** [comment]
> Notice that:
> 
> * there might be edge cases on [mint](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L17) or [redeem](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L33) when there is not enough liquidity in the pools

Can you explain to me the edge cases? I don't understand the issue.

> * the underlying collateral token (`LUSD` in our case) should be configurable (i.e. we should be able to update it to some other token)

We should be able to eventually enable support for more assets in case there are issues with acquiring new `LUSD`. In the original specification for implementing the collateral module, I remember asking to enable support for `sUSD` as well, and then we should disable `sUSD` deposits after we deploy so that the architecture to support multiple collateral types is implemented.

**Comment by rndquu** [comment]
> > Notice that:
> > 
> > * there might be edge cases on [mint](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L17) or [redeem](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L33) when there is not enough liquidity in the pools
> 
> Can you explain to me the edge cases? I don't understand the issue.

I meant that freshly created ERC20 tokens might not have any liquidity at all so the swap would not be possible but I guess the CoW Protocol has already covered such cases

> > * the underlying collateral token (`LUSD` in our case) should be configurable (i.e. we should be able to update it to some other token)
> 
> We should be able to eventually enable support for more assets in case there are issues with acquiring new `LUSD`. In the original specification for implementing the collateral module, I remember asking to enable support for `sUSD` as well, and then we should disable `sUSD` deposits after we deploy so that the architecture to support multiple collateral types is implemented.

Yes, I overlooked this feature. Multicolalteral feature (along with disabling deposits for certain ERC20 tokens) is already implemented as a part of https://github.com/ubiquity/ubiquity-dollar/issues/609.

Deleted this line from the description:
- "the underlying collateral token (LUSD in our case) should be configurable (i.e. we should be able to update it to some other token)"

**Comment by molecula451** [comment]
this is basically an array of addresses `address[]` virtualized on an interface so that it supports further tokens && more importantly so that it handles different chains, because tokens are not the same on the different chains, neither exchanges (exchanges are realtive, UniV2 impl, etc), and liquidity but there is probably more under the hood, am stepping if not bounty hunter comes, on and after latests pull requests

**Comment by rndquu** [comment]
> because tokens are not the same on the different chains

@pavlovcik do we have plans to run UAD on different networks apart from ethereum mainnet?

**Comment by 0x4007** [comment]
If omnibridge works as I expect then we can dynamically deploy without any accommodations on Gnosis Chain by using their omnibridge, for payment settlement in uAD on Gnosis Chain. 

If we can't rely on that for some reason then we might need to deploy an instance on Gnosis Chain. 

However I think it's overkill to redeploy the entire protocol on multiple networks. Arbitrageurs should keep stability intact. We just need to deploy derivative tokens.

**Comment by rndquu** [comment]
> it's overkill to redeploy the entire protocol on multiple networks

ok, so right now the focus is only on the ethereum mainnet

**Comment by hashedMae** [comment]
The best way to achieve this would be using [CoW Hooks](https://docs.cow.fi/overview/cow-hooks/cow-hooks-example/permit-swap-and-bridge-cow-hook). The major limitation is that it only works with tokens that support EIP-2612 Permit. This should be fine for the majority of uses but some tokens won't be usable with the zap function. May need to create a predefined list of compatible tokens to avoid confusion.

**Comment by 0x4007** [comment]
The only token that comes to mind in my normal usage of CoW Swap is the dYdX token regarding incompatibility. I think it would be considered quite the edge case and probably not a significant issue compared to the benefits but I appreciate the caveat.

**Comment by 0x4007** [comment]
@rndquu  should we close this as unplanned

**Comment by molecula451** [comment]
i think it's a nice feature to have but we can close as not completed, for future developing if we see the value on the actual live protocol out of the necessity, my thoughts, rfc @gitcoindev

**Comment by rndquu** [comment]
Yes, it is not a "must have" feature hence it makes sense to save time and close it as "not planned"
