### ISSUE TITLE
Algorithmic Market Operations for Collateral

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#611]
There is the [UbiquityPoolFacet](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol) where users can:
1. Deposit collateral ERC20 tokens in exchange for Dollar tokens
2. Redem Dollar tokens in exchange for the collaterral

We should put the provided collateral to work and earn some yield.

What should be done:
1. Take any AMO strategy contract (from frax finance or some other well audited protocol)
2. Create an ERC-4626 contract over that strategy so that we could easily add new AMO strategies to the ubiquity protocol
3. Add thorough natspec comments for all of the contracts, methods and mechanics
4. Add unit testing
 
Good article: https://mirror.xyz/jackchong.eth/iB_teRKgBaKm4OTKFmjf8hFAM55C1_i0Z2kf-KkYz2I

_Original description:_
we want an AMO for collateral gathered thanks to  https://github.com/ubiquity/ubiquity-dollar/issues/609
Algorithmic Market Operations  module is an autonomous contract(s) that enacts arbitrary  monetary policy so long as it does not change the uAD price off its peg. This means that AMO controllers can perform open market operations algorithmically (as in the name), but they cannot arbitrarily mint uAD out of thin air and break the peg. The aims is to invests idle collateral into various DeFi vaults/protocols

**Comment by 0x4007** [comment]
Can you place a time estimate?

**Comment by hashedMae** [comment]
so algo farming?

**Comment by 0x4007** [comment]
It just means that we want to have some collateral to be put to work to make some yield. We should use the [ERC-4626: Tokenized Vaults](https://eips.ethereum.org/EIPS/eip-4626) interface as discussed in the past. I do think that we need to specify AMO strategies and have them be separate bounties but the intent behind this bounty is to consider this architecture and include AMO capability within the core collateral module.

**Comment by rndquu** [comment]
@pavlovcik I removed time and priority labels because we should make the spec more clear

**Comment by rndquu** [comment]
> It just means that we want to have some collateral to be put to work to make some yield. We should use the [ERC-4626: Tokenized Vaults](https://eips.ethereum.org/EIPS/eip-4626) interface as discussed in the past. I do think that we need to specify AMO strategies and have them be separate bounties but the intent behind this bounty is to consider this architecture and include AMO capability within the core collateral module.

Questions:
1. So each AMO strategy is an ERC-4626 vault, right?
2. When user deposits collateral ERC20 tokens in exchange for UAD then user should also select an AMO strategy, right? Or user can deposit funds and then, in another transaction, select different AMOs for different deposited amounts?
3. Frax supports the following AMOs: Aave, Compound, Yearn, Curve, Uniswap. Which one we should implement 1st?
4. Who earns the yield? User or ubiquity protocol?

**Comment by 0x4007** [comment]
> > It just means that we want to have some collateral to be put to work to make some yield. We should use the [ERC-4626: Tokenized Vaults](https://eips.ethereum.org/EIPS/eip-4626) interface as discussed in the past. I do think that we need to specify AMO strategies and have them be separate bounties but the intent behind this bounty is to consider this architecture and include AMO capability within the core collateral module.
> 
> 
> 
> Questions:
> 
> 1. So each AMO strategy is an ERC-4626 vault, right?
> 
> 2. When user deposits collateral ERC20 tokens in exchange for UAD then user should also select an AMO strategy, right? Or user can deposit funds and then, in another transaction, select different AMOs for different deposited amounts?
> 
> 3. Frax supports the following AMOs: Aave, Compound, Yearn, Curve, Uniswap. Which one we should implement 1st?
> 
> 4. Who earns the yield? User or ubiquity protocol?

1. Yes
2. We should handle AMOs entirely internally. It is no longer intended to be user facing. This is how FRAX does it for max profit. 
3. I'm not sure at the moment. I imagine that they can be pretty quick to put together if we fork other code (like FRAX AMOs?)
4. Ubiquity

**Comment by FibrinLab** [comment]
@pavlovcik Can I work on this issue?

**Comment by rndquu** [comment]
> @rndquu @pavlovcik Can I work on this issue?

Sure, pls check the updated description

**Comment by molecula451** [comment]
i've seeing some good changes in your PR @FibrinLab what happened?

**Comment by FibrinLab** [comment]
> i'm seeing some good changes in your PR @FibrinLab what happened?

Finishing up

**Comment by molecula451** [comment]
if you don't open at least a PR ready for review the bot will keep ejecting you, if you can't handle i suggest you pick up another task

**Comment by bojan07** [comment]
Can I start to work on this issue now?

**Comment by bojan07** [comment]
Seems @FibrinLab gave up this issue.. let me start

**Comment by 0x4007** [comment]
> ```diff
> ! action returned an unexpected value
> ```

We're almost there with the new deployment. I'm surprised that it pushed through and still assigned you.

**Comment by molecula451** [comment]
pavlovcik's new pfp 😄

**Comment by molecula451** [comment]
it looks like the bot it's trying to participate on each action, of the repo, each action you, a comment it's trying to do, deleting most of the unused comments to avoid clogging on contributors PR

**Comment by 0x4007** [comment]
Yes there's a bug with the task timeout unassign logic. 

If there's an error thrown it will dump it in the database, console, and the issue that invoked it.

**Comment by 0x4007** [comment]
> it looks like the bot it's trying to participate on each action, of the repo, each action you, a comment it's trying to do, deleting most of the unused comments to avoid clogging on contributors PR

Hiding comments is better for archival purposes.

**Comment by gpylypchuk** [comment]
Hey, this is still open? bc @FibrinLab is assigned but did not see the pr

**Comment by molecula451** [comment]
> Hey, this is still open? bc @FibrinLab is assigned but did not see the pr

yes, it's open

**Comment by rndquu** [comment]
> Hey, this is still open? bc @FibrinLab is assigned but did not see the pr

Yes, you may take inspiration from https://github.com/FraxFinance/frax-solidity/blob/master/src/hardhat/contracts/Frax/FraxAMOMinter.sol

You may propose how we can break down this task to smaller issues

**Comment by gpylypchuk** [comment]
> > Hey, this is still open? bc @FibrinLab is assigned but did not see the pr
> 
> Yes, you may take inspiration from https://github.com/FraxFinance/frax-solidity/blob/master/src/hardhat/contracts/Frax/FraxAMOMinter.sol
> 
> You may propose how we can break down this task to smaller issues

Okay, I've been researching about this, because I do not know too much. 
So the main idea is use e.g. USDC as collateral for the Dollar and then use it with a strategy to earn?

**Comment by molecula451** [comment]
> Okay, I've been researching about this, because I do not know too much. So the main idea is use e.g. USDC as collateral for the Dollar and then use it with a strategy to earn?

this is a huge task you may check closed PRs to have reference. I'd suggest you first familiarize yourself with the repo before start working on this one.

> So the main idea is use e.g. USDC as collateral for the Dollar and then use it with a strategy to earn?

Our selected stablecoin for now is LUSD

**Comment by rndquu** [comment]
> > > Hey, this is still open? bc @FibrinLab is assigned but did not see the pr
> > 
> > 
> > Yes, you may take inspiration from https://github.com/FraxFinance/frax-solidity/blob/master/src/hardhat/contracts/Frax/FraxAMOMinter.sol
> > You may propose how we can break down this task to smaller issues
> 
> Okay, I've been researching about this, because I do not know too much. So the main idea is use e.g. USDC as collateral for the Dollar and then use it with a strategy to earn?

Exactly

**Comment by gpylypchuk** [comment]
It has to be upgreadeable?

**Comment by 0x4007** [comment]
Pretty sure everything is upgradable by default since the core of the protocol is a Diamond.

**Comment by gpylypchuk** [comment]
Ahh that is correct, sorry :)

I propose a directory like that, what do you think?
Also, then, including libraries.

```
📂facets
 ┣ 📂implementations
 ┃ ┣ 📂aave
 ┃ ┃ ┗ 📜AaveAMO.sol
 ┃ ┗ 📂curve
 ┃   ┗ 📜CurveAMO.sol
 ┗ 📜DollarAMOMinterFacet.sol

📂interfaces
┗ 📜IDollarAMOMinter.sol

📂test
┗ 📂diamond
  ┗ 📂facets
    ┗ 📜DollarAMOMinterFacet.t.sol
```

**Comment by 0x4007** [comment]
@rndquu @gitcoindev @molecula451 would know better.

**Comment by rndquu** [comment]
> Ahh that is correct, sorry :)
> 
> I propose a directory like that, what do you think? Also, then, including libraries.
> 
> ```
> 📂facets
>  ┣ 📂implementations
>  ┃ ┣ 📂aave
>  ┃ ┃ ┗ 📜AaveAMO.sol
>  ┃ ┗ 📂curve
>  ┃   ┗ 📜CurveAMO.sol
>  ┗ 📜DollarAMOMinterFacet.sol
> 
> 📂interfaces
> ┗ 📜IDollarAMOMinter.sol
> 
> 📂test
> ┗ 📂diamond
>   ┗ 📂facets
>     ┗ 📜DollarAMOMinterFacet.t.sol
> ```

Looks good

> It has to be upgreadeable?

Yes, it should be part of the diamond

**Comment by molecula451** [comment]
> Ahh that is correct, sorry :)
> 
> I propose a directory like that, what do you think? Also, then, including libraries.
> 
> ```
> 📂facets
>  ┣ 📂implementations
>  ┃ ┣ 📂aave
>  ┃ ┃ ┗ 📜AaveAMO.sol
>  ┃ ┗ 📂curve
>  ┃   ┗ 📜CurveAMO.sol
>  ┗ 📜DollarAMOMinterFacet.sol
> 
> 📂interfaces
> ┗ 📜IDollarAMOMinter.sol
> 
> 📂test
> ┗ 📂diamond
>   ┗ 📂facets
>     ┗ 📜DollarAMOMinterFacet.t.sol
> ```

While you are implementing and putting the pieces together, the craft will en-route you to cope the pieces with the diamond so in essence making it up-gradable you should focus on deliver the task context of this issue, since the task is large and provide and overall PR to look for

**Comment by sergfeldman** [comment]
Since this task was created long time ago and seems not in progress right now, I will test some AI services on it.
If necessary, I will delete my comments after testing.

**Comment by sergfeldman** [comment]
### Estimation of each To Do item of the task using the Random Distribution Adaptation methodology:

1. **Take an AMO strategy contract**: This involves researching and selecting an appropriate AMO strategy from existing protocols. Initial estimation range: 2-5 days.
   - Researching and understanding the selected AMO strategy thoroughly: 2-3 days.
   - Adapting the strategy to fit the UbiquityPoolFacet's requirements: 1-2 days.

2. **Create an ERC-4626 contract over the strategy**: This includes drafting, developing, and testing the ERC-4626 wrapper. Initial estimation range: 3-6 days.
   - Drafting and planning the ERC-4626 implementation: 1-2 days.
   - Coding the ERC-4626 wrapper: 2-3 days.
   - Initial testing and debugging of the wrapper: 1 day.

3. **Add thorough natspec comments**: Documenting all contracts, methods, and mechanics. Initial estimation range: 1-3 days.
   - Writing comments: 1-2 days.
   - Review and revision of comments for clarity and completeness: 0.5-1 day.

4. **Add unit testing**: Writing comprehensive tests for all functionalities. Initial estimation range: 2-4 days.
   - Planning and writing test cases: 1-2 days.
   - Implementation and debugging of test cases: 1-2 days.

### Estimation of the entire task using the Three-point Estimation methodology:

- **Optimistic Estimate**: 8 days 
  - Best case scenario with smooth development and minimal issues.
- **Pessimistic Estimate**: 18 days 
  - Accounting for potential challenges, learning curves, and debugging.
- **Most Likely Estimate**: 12 days 
  - Considering typical development challenges and minor delays.

**Reasoning**: The optimistic scenario assumes fast research, straightforward adaptation, minimal debugging, and efficient documentation. The pessimistic scenario accounts for potential issues in understanding and adapting the AMO strategy, challenges in ERC-4626 implementation, extensive debugging, and detailed documentation needs. The most likely scenario balances these factors with expected development challenges.

### Estimation of the entire task using the Complexity Categorization methodology:

Given the need to understand and adapt external AMO strategies, develop a new ERC-4626 contract, document comprehensively, and ensure thorough testing, this task is categorized as **Complex**.

- **Optimistic Estimate**: 10 days
- **Pessimistic Estimate**: 20 days
- **Most Likely Estimate**: 15 days

**Reasoning**: This estimation considers the complexity of adapting and integrating AMO strategies into the Ubiquity protocol, the creation of a new ERC-4626 contract, and the importance of thorough documentation and testing. The complexity categorization is based on the intricate details of DeFi protocols, the necessity for secure and efficient implementation, and the potential for unforeseen challenges in development and integration.

### Mean estimation of the entire task:

- **Three-point Estimation Methodology Mean**: 12 days.
- **Complexity Categorization Methodology Mean**: 15 days.

**Final Mean Estimation**: 14 days (rounded to the nearest whole number). 

This final mean estimation accounts for the complexities of integrating with DeFi protocols, developing new contracts, documentation, and testing, while also considering potential development challenges and delays.

**Comment by pavlovcik** [comment]
That's pretty interesting. Does it take into account the conversation as well? If not then I recommend recreating the issue at @ubiquibot/production or @ubiquibot/sandbox as we generally use those for testing purposes. 

This could be a useful plugin if it knows how to add the time label

**Comment by sergfeldman** [comment]
@pavlovcik You noticed the essence of the testing. I compared the estimate based on the task description only (above) and the estimate based on the task description and conversation (I will post below). In this particular case, they are almost the same.

Yes, we can create a plugin that will select the most appropriate time label. 
It would be interesting to create a plugin that, based on the description of the task and the repository code, would offer optimal solution options, indicate the strengths and weaknesses of each option, write a detailed step-by-step execution plan with the time estimate for each option.

I will delete comments with my testing tomorrow.

**Comment by sergfeldman** [comment]
### Estimation of each To Do item of the task using the Random Distribution Adaptation methodology:

- **Analyzing AMO Strategy Contract**: 1-2 days. Reviewing existing AMO contracts from protocols like Frax Finance to understand the mechanisms and best practices.
- **Creating an ERC-4626 Contract Over the Strategy**: 3-5 days. Developing a new ERC-4626 contract that can interface with the chosen AMO strategy and be flexible for future additions.
- **Natspec Comments**: 1-2 days. Adding thorough documentation within the codebase is crucial for future maintenance and understanding by new developers.
- **Unit Testing**: 2-4 days. Writing comprehensive unit tests to ensure all functionalities work as expected under various scenarios.
- **Integration and Testing with Ubiquity Protocol**: 3-5 days. Integrating the new AMO strategy with the Ubiquity protocol and conducting thorough testing to ensure compatibility and performance.

### Estimation of the entire task using the Three-point Estimation methodology:

- **Optimistic Estimate**: 10 days. Assumes smooth development and integration process with minimal setbacks.
- **Pessimistic Estimate**: 18 days. Accounts for potential challenges in integration, unexpected complexities in AMO strategies, and possible revisions needed after testing.
- **Most Likely Estimate**: 14 days. Considering typical development and testing challenges, plus some buffer for unforeseen issues.

**Reasoning**: The task involves multiple complex components, including the integration of new financial strategies into an existing protocol and ensuring these integrations are secure, efficient, and maintainable. The variance in the estimates accounts for the unpredictability in development complexities and testing outcomes.

### Estimation of the entire task using the Complexity Categorization methodology:

Given the task involves integrating with external protocols, developing compliant ERC-4626 contracts, and ensuring the system's security and efficiency, the complexity is categorized as "complex."

- **Optimistic Estimate**: 12 days. Assuming efficient reuse of existing, well-audited code and smooth integration.
- **Pessimistic Estimate**: 20 days. Considering potential difficulties in adapting AMO strategies, addressing security concerns, and achieving desired functionality with ERC-4626.
- **Most Likely Estimate**: 16 days. Balancing the optimistic outlook with the reality of potential setbacks and the need for comprehensive testing.

**Reasoning**: The integration of multiple components, need for security audits, and compliance with financial protocols increase the complexity. The estimates reflect a blend of optimism for leveraging existing solutions and caution for the intricate nature of financial protocols.

- **Mean estimation of the entire task using the Three-point Estimation methodology and the Complexity Categorization methodology**: (14 days + 16 days) / 2 = 15 days rounded to the nearest whole number is 15 days.

**Comment by molecula451** [comment]
> @pavlovcik You noticed the essence of the testing. I compared the estimate based on the task description only (above) and the estimate based on the task description and conversation (I will post below). In this particular case, time estimates are almost the same.
> 
> Yes, we can create a plugin that will select the most appropriate time label. It would be interesting to create a plugin that, based on the description of the task and the repository code, would offer optimal task resolution options, indicate the strengths and weaknesses of each option, write a detailed step-by-step execution plan with the time estimate for each option.
> 

It would be nice to see such plugin, altho the developer experience always know as a much a time estimated as this also depends if the developer prolongs this due to timing pause (because personal decision) o because it can do even faster (again personal decision) understanding of the task it's crucial factor, another factor it's optimal implementation, a developer might implement something fast accurately or not so of a good taste, which lead to delays in periods of PR review and overall understanding of the task

this task it's NOT underpaid, but it also requires a bit of economical understanding + the technical factor

**Comment by 0x4007** [comment]
@rndquu is this still current?

**Comment by rndquu** [comment]
> @rndquu is this still current?

Yes

@sudotx Could you describe how exactly you're going to implement the AMO feature?

**Comment by molecula451** [comment]
It is current

**Comment by sudotx** [comment]
@rndquu  Nothing concrete in mind yet, i am still getting up to speed on what work has been  on it prior

**Comment by molecula451** [comment]
> @rndquu Nothing concrete in mind yet, i am still getting up to speed on what work has been on it prior

checkout closed PR for instances, this task requires a strategy implementation and testing

**Comment by rndquu** [comment]
> @rndquu Nothing concrete in mind yet, i am still getting up to speed on what work has been on it prior

This issue could be solved this way:
1. Create a new AMO minter contract (forked from [FraxAMOMinter](https://github.com/FraxFinance/frax-solidity/blob/85039d4dff2fb24d8a1ba6efc1ebf7e464df9dcf/src/hardhat/contracts/Frax/FraxAMOMinter.sol)). We don't need all of the methods there, only the ones that transfer collateral from [LibUbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/91816753d250dfe34f6956eb7fc6d66a5ce0e96c/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol) to a destination AMO strategy.
2. Create a new AMO strategy ([example](https://github.com/FraxFinance/frax-solidity/blob/85039d4dff2fb24d8a1ba6efc1ebf7e464df9dcf/src/hardhat/contracts/Misc_AMOs/Lending_AMOs/AaveAMO_V2.sol)). It should conform either to the ERC-4626 interface either to some custom `IUbiquityAmoStrategy` interface. I'm not sure why Frax doesn't use a common interface for its AMO strategies, perhaps it's burdensome to implement/maintain a single interface for all protocols (i.e. AMO strategies).

**Comment by molecula451** [comment]
@sudotx never opened an PR and it didn't came back to actively communicate update. The bot didn't even unassigned em, @ubiquity/software-development

**Comment by 0x4007** [comment]
We will handle all those odds and ends of bot problems with v2

**Comment by zugdev** [comment]
EIP-2535 is something I have personal experience with, I've designed facets as adapters to interact with multiple protocols previously. Is this issue still open should I make it alive?

**Comment by rndquu** [comment]
> EIP-2535 is something I have personal experience with, I've designed facets as adapters to interact with multiple protocols previously. Is this issue still open should I make it alive?

@0x4007 Do we still need to make yield on the provided collateral?

**Comment by 0x4007** [comment]
Yeah that's a main planned revenue strategy.

**Comment by rndquu** [comment]
@zugdev I think it makes sense to make a forked version of [FraxAMOMinter](https://github.com/FraxFinance/frax-solidity/blob/85039d4dff2fb24d8a1ba6efc1ebf7e464df9dcf/src/hardhat/contracts/Frax/FraxAMOMinter.sol) a separate diamond [facet](https://github.com/ubiquity/ubiquity-dollar/tree/0a230f977ad91bbfb01dd28bc1d2ea77faed5237/packages/contracts/src/dollar/facets) while keeping separate AMO strategies standalone contracts.

**Comment by zugdev** [comment]
@rndquu I am still thinking through it, at the end of the day we want to generate yield on Dollar's collateral. Take supplying to Aave markets for example, is supply and withdraw intended to be done arbitrarily by some multisig? If so should I trust managers to correctly manage collateral liquidity for Dollar minters? 

In my head the best, trust minimizing, approach is: 

1. Every new collateral is auto supplied.
2. On Dollar burn, withdraw necessary amount to cover collateral needed.
3. Yield generated distributed to holders (This is a new feature apart from this one tbh, straightest one would be 100% yield to treasury)

The biggest risk involved is in Aave being breached, which should be very low. The facet would be internal so no external risk as long as we guarantee no arbitrary calls.

**Comment by 0x4007** [comment]
Automated is preferred in the long run. In the beginning stages there is a chance that it might be manual though.

**Comment by rndquu** [comment]
> @rndquu I am still thinking through it, at the end of the day we want to generate yield on Dollar's collateral. Take supplying to Aave markets for example, is supply and withdraw intended to be done arbitrarily by some multisig? If so should I trust managers to correctly manage collateral liquidity for Dollar minters?
> 
> In my head the best, trust minimizing, approach is:
> 
> 1. Every new collateral is auto supplied.
> 2. On Dollar burn, withdraw necessary amount to cover collateral needed.
> 3. Yield generated distributed to holders (This is a new feature apart from this one tbh, straightest one would be 100% yield to treasury)
> 
> The biggest risk involved is in Aave being breached, which should be very low. The facet would be internal so no external risk as long as we guarantee no arbitrary calls.

For v1 we can keep it simple:
- Supply (to aave for example) and withdraw of collateral (back to UbiquityPool) will be done manually by the owner address

For v2 we can aim for:
- auto supply
- auto redeem on Dollar burn
- yield distribution

If it's simpler to implement [FraxAMOMinter](https://github.com/FraxFinance/frax-solidity/blob/85039d4dff2fb24d8a1ba6efc1ebf7e464df9dcf/src/hardhat/contracts/Frax/FraxAMOMinter.sol) as a separate contract (not as a Diamond's facet) then you may go this way. It's less error prone.

**Comment by zugdev** [comment]
@rndquu I need some more context, I thought the Diamond was in prod, based on the last Foundry broadcast it appears that's not correct. Is the idea to implement an AMO minter or to have the AMO itself? An AMO might not be necessary to have an Aave interacting facet or wrapper. I will write a sketch today and share here for debate.

**Comment by 0x4007** [comment]
Diamond is deployed on mainnet 

I thought all the addresses are on the readme?

**Comment by rndquu** [comment]
> I thought the Diamond was in prod, based on the last Foundry broadcast it appears that's not correct.

It's on prod: https://github.com/ubiquity/ubiquity-dollar/blob/0a230f977ad91bbfb01dd28bc1d2ea77faed5237/packages/contracts/broadcast/Deploy001_Diamond_Dollar_Governance.s.sol/1/run-latest.json#L133

> Is the idea to implement an AMO minter or to have the AMO itself? An AMO might not be necessary to have an Aave interacting facet or wrapper.

The idea is to implement an AMO minter and a real AMO strategy that we would be able to use. `ERC-2535` (Diamond) doesn't support equal method identifiers (i.e. facets with the same method signatures). It means that if we move each AMO strategy (by the way original FRAX [repository](https://github.com/FraxFinance/frax-solidity/tree/85039d4dff2fb24d8a1ba6efc1ebf7e464df9dcf/src/hardhat/contracts) has >100 of them) to facets then chances are that method identifies will collide.

**Comment by zugdev** [comment]
Ok I understand it all now, thanks for clearing it. I thought this project was on Gnosis, therefore didn't consider the mainnet deployment. I am already working on this, will bring news soon.

**Comment by zugdev** [comment]
Opened a draft, I would appreciate some feedback on requirements as you have a much broader future view of Ubiquity than I do. For example minting uAD and UBQ to AMOs might not be useful, if so we could cut that out. Else would need to find a more straight forward way of minting to AMO, with no collateral but with external management as FRAX does.

**Comment by rndquu** [comment]
> For example minting uAD and UBQ to AMOs might not be useful, if so we could cut that out.

Yes

**Comment by zugdev** [comment]
I think I should be reassigned here
