### ISSUE TITLE
update wallet as walletconnect is sunsetting in june 

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#614]
in the dapp we are using wallet connect 1.8 but 
[walletconnect v1 will be shutdown in june ](https://medium.com/walletconnect/weve-reset-the-clock-on-the-walletconnect-v1-0-shutdown-now-scheduled-for-june-28-2023-ead2d953b595)

**Comment by Eren-Yeaager** [comment]
Hi can u assign me this issue?

**Comment by 0x4007** [comment]
Wow I remember specifically asking about using WalletConnect 2.0 I'm not sure how this could have happened!

@Eren-Yeaager I already assigned you to #564

**Comment by Eren-Yeaager** [comment]
Thank u so much

**Comment by Eren-Yeaager** [comment]
is this issue assigned to me now?

**Comment by Steveantor** [comment]
> is this issue assigned to me now?

You've already assigned to #564 
Please finish that one first before continuing! 
@Eren-Yeaager

**Comment by Steveantor** [comment]
Test bot hotfix

**Comment by 0xColm** [comment]
Hi Can you assign me this issue?

**Comment by Steveantor** [comment]
test

**Comment by Eren-Yeaager** [comment]
Hi ,previously i wanted to work on this issue especially but i was assigned other issue which i was not able to understand properly. Please assign me this issue.

**Comment by 0x4007** [comment]
By the way @Steveantor you should technically be using the /assign command. I hope you get used to the /assign flow because that's how you will use it on our partner projects!

**Comment by Steveantor** [comment]
> Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`

There's a linked PR

**Comment by Steveantor** [comment]
> Do you have any updates @Steveantor? If you would like to release the bounty back to the DevPool, please comment `/unassign`

yes, the review process is slower
