### ISSUE TITLE
Build Fails on Windows x86_64

### ISSUE THREAD

**Issue by Steveantor** [pavlovcik/uad-ui#615]
Yarn build fails on Windows OS citing the following error:

```node
ERROR: "build:types" exited with 1.
```

**Comment by Steveantor** [comment]
test

**Comment by Steveantor** [comment]
test12

**Comment by Steveantor** [comment]
test

**Comment by Steveantor** [comment]
test

**Comment by Steveantor** [comment]
test

**Comment by zorglob21** [comment]
it seems that this issue solved itself. I was able to run build on my windows 11 64 bit

**Comment by 0x4007** [comment]
> it seems that this issue solved itself. I was able to run build on my windows 11 64 bit

@Steveantor can you confirm?

**Comment by Steveantor** [comment]
> > it seems that this issue solved itself. I was able to run build on my windows 11 64 bit
> 
> @Steveantor can you confirm?

Will need to re test

**Comment by rndquu** [comment]
> it seems that this issue solved itself. I was able to run build on my windows 11 64 bit

thank you, closing this one then, @Steveantor pls reopen if this is still an issue
