### ISSUE TITLE
Automatic selector populating for diamond facets

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#616]
We have 2 files where we [add selectors](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/diamond/DiamondTestSetup.sol#L138) for the diamond storage:
1. https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/scripts/deploy/dollar/solidityScripting/01_Diamond.s.sol
2. https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/diamond/DiamondTestSetup.sol

We add all the selectors manually so it is easy to miss one or forget to update the migration script after changes to one of the contracts.

What should be done:
1. Automate selector populating both in these files: [01_Diamond](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/scripts/deploy/dollar/solidityScripting/01_Diamond.s.sol) and [DiamondTestSetup](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/diamond/DiamondTestSetup.sol). Foundry can read from json files so perhaps we could read the build ABIs and automatically populate selectors for all facets.
2. Use a dynamic array [here](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/scripts/deploy/dollar/solidityScripting/01_Diamond.s.sol#L140) and [here](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/diamond/DiamondTestSetup.sol#L538)

**Comment by rndquu** [comment]
@pavlovcik could you set a priority here?

**Comment by 0x4007** [comment]
> @pavlovcik could you set a priority here?

I'll grant you permission to set priority on any issue on this repository for `Time: <1 Hour` and `Time: <1 Day` issues.

I don't think I understand this issue enough to evaluate its priority level accurately.

**Comment by molecula451** [comment]
This issue description was updated to help deploy and achieve a reasonable implementation

**Comment by molecula451** [comment]
I must admit this issue naming was mislading all the time this "populating"  😅

**Comment by molecula451** [comment]
i think you should re-start rndqnuu
