### ISSUE TITLE
fix git submodules

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#624]
multiple configurations found for the same submodules inside .gitmodules

![image](https://user-images.githubusercontent.com/16853695/231725264-ef64c8bf-4a32-4776-ba8f-7f9cdd4fe455.png)

**Comment by eugenioclrc** [comment]
Related: https://github.com/ubiquity/ubiquity-dollar/issues/643

**Comment by PhantomCracker** [comment]
@pavlovcik still have issues with /assign command?

**Comment by 0x4007** [comment]
> @pavlovcik still have issues with /assign command?

Apologies. We're working on fixing the bot stability this week.

**Comment by cuddle-dev** [comment]
Apologize @here. this is just for testing. I am assigning @PhantomCracker  to the issue right now.

**Comment by 0x4007** [comment]
> Apologize @here. this is just for testing. I am assigning @PhantomCracker to the issue right now.

Perhaps you should be testing in the testing repository instead. https://github.com/ubiquibot/production

**Comment by PhantomCracker** [comment]
No worries @here 👍

**Comment by rndquu** [comment]
closing this one as "not planned" because it is part of https://github.com/ubiquity/ubiquity-dollar/issues/643
