### ISSUE TITLE
Fix Test for asserting total number of available facets.

### ISSUE THREAD

**Issue by FibrinLab** [pavlovcik/uad-ui#629]
My fear is when two branches are both looking to merge in a new facet and both have incremented the facet count by one. The first one will pass the merge CI. The second one will fail. It is a simple problem but technically it would be a perpetual problem. That's why I'm bringing this to the team's attention to see if there's a better way to do this.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/pull/444#discussion_r1181249307_

**Comment by FibrinLab** [comment]
> My fear is when two branches are both looking to merge in a new facet and both have incremented the facet count by one. The first one will pass the merge CI. The second one will fail. It is a simple problem but technically it would be a perpetual problem. That's why I'm bringing this to the team's attention to see if there's a better way to do this.
> 
> 
> 
> _Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/pull/444#discussion_r1181249307_
> 
>             

I got this from GPT
@pavlovcik

One possible solution to this problem is to modify the foundry test scenario so that it checks for a range of acceptable facet numbers, instead of a fixed number. For example, instead of testing for an exact number of facets, the test could be modified to check that the number of facets falls within a certain range, such as between a minimum and maximum value. This would allow for some flexibility in the number of facets that are acceptable and would be less likely to break with each pull request.

Another possible solution is to automate the process of updating the foundry test scenario with each pull request. This could be done using a script or tool that automatically reads the number of facets from the 3D model or other source and updates the test scenario accordingly. This would ensure that the test scenario always matches the actual number of facets in the model and would reduce the likelihood of errors or discrepancies.

It may also be possible to use a combination of these approaches, such as setting a range of acceptable facet numbers and automating the process of updating the test scenario with each pull request. This would provide both flexibility and consistency in the testing process.

**Comment by FibrinLab** [comment]
> My fear is when two branches are both looking to merge in a new facet and both have incremented the facet count by one. The first one will pass the merge CI. The second one will fail. It is a simple problem but technically it would be a perpetual problem. That's why I'm bringing this to the team's attention to see if there's a better way to do this.
> 
> 
> 
> _Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/pull/444#discussion_r1181249307_
> 
>             

I got this from GPT
@pavlovcik

One possible solution to this problem is to modify the foundry test scenario so that it checks for a range of acceptable facet numbers, instead of a fixed number. For example, instead of testing for an exact number of facets, the test could be modified to check that the number of facets falls within a certain range, such as between a minimum and maximum value. This would allow for some flexibility in the number of facets that are acceptable and would be less likely to break with each pull request.

Another possible solution is to automate the process of updating the foundry test scenario with each pull request. This could be done using a script or tool that automatically reads the number of facets from the 3D model or other source and updates the test scenario accordingly. This would ensure that the test scenario always matches the actual number of facets in the model and would reduce the likelihood of errors or discrepancies.

It may also be possible to use a combination of these approaches, such as setting a range of acceptable facet numbers and automating the process of updating the test scenario with each pull request. This would provide both flexibility and consistency in the testing process.

**Comment by 0x4007** [comment]
I'm not keen on either suggestion. We can leave this bounty as a draft (no final price set) until we figure a more elegant solution

**Comment by rndquu** [comment]
closing this one because it is part of https://github.com/ubiquity/ubiquity-dollar/issues/616
