### ISSUE TITLE
Refactor tests remove mockups

### ISSUE THREAD

**Issue by hashedMae** [pavlovcik/uad-ui#630]
from #571 
>None of the current tests are using a fork environment. Instead, tests like for TWAPOracleDollar3Pool that relies on CurveFactory is testing a MockTWAPOracle instead of the actual contract. I don't know how many tests are following this pattern but it means that multiple contracts are currently untested.

Several tests are testing mockup contracts instead of the real ones. They need to be fixed to test the proper contracts and to fork mainnet if necessary.

Offending Tests
`ChefFacet.t.sol`
`CreditNftManagerFacet.t.sol`
`CreditNftRedemptionCalculatorFacet.t.sol`
`CreditRedemptionCalculatorFacet.t.sol`
`ManagerFacet.t.sol`
`StakingFacet.t.sol`
`TwapOracleFacet.t.sol`

Changing `DiamondTestHelper.sol` is also necessary.

**Comment by hashedMae** [comment]
@pavlovcik @zgorizzo69 If this looks good to y'all I can get started on it right away. This makes #571 redundant as well.

**Comment by Eren-Yeaager** [comment]
@pavlovcik Can you please assign me this issue

**Comment by Eren-Yeaager** [comment]
I can refactor it within a week.

**Comment by 0x4007** [comment]
Hey @hashedMae you shouldn't adjust the prices directly. However I'm willing to saddle up on this now so you can get started!

**Comment by 0x4007** [comment]
> /assign
> 
> 

The best thing to do here is to open up a pull request and try and solve the bounty soon!

**Comment by molecula451** [comment]
working it @pavlovcik

**Comment by molecula451** [comment]
Contracts like:

CreditNftManager
CreditNftRedemption
CreditRedemptionCalculator

doesn't seem to be on Mainnet, cannot mix diamond with already deployed mainnet for querying like for e.g

`ITWAPOracle(twapOracleAddress).token1();`

which will get me 3crv address, this one must be explicitily on chain call and already deployed contract.

I am PR for the other 4 tests

@rndquu @pavlovcik

**Comment by 0x4007** [comment]
I thought we supported local/mainnet hybrid testing. I could be wrong though.

**Comment by molecula451** [comment]
> I thought we supported local/mainnet hybrid testing. I could be wrong though.

We can do hybrid mix and combine locally and a on-chain, but technically, not using the local ones to call chain, unless deployed, faking a mainnet deploy won't do much either.  I am also clarifying a bit the OP requirements

**Comment by molecula451** [comment]
e.g would be the `test_overall()` to test mainnet data but with ABI compatible, we cannot just use ITWAPOracleDollar3pool.sol on https://github.com/molecula451/ubiquity-dollar/blob/save-changes/packages/contracts/src/dollar/interfaces/ITWAPOracleDollar3pool.sol

We use one like the changes on my repo https://github.com/molecula451/ubiquity-dollar/blob/save-changes/packages/contracts/test/diamond/facets/TWAPOracleFacet.t.sol

## Call to diamond and to mainnet contracts
![twapo](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/21365ebf-dfdd-4240-858e-9ac6acafde50)

if we do not use the onchain compatible ABI we would get a `REVERT` on the call

but at the same time we might keep original local tests (non-mainnet calls) (IManager has a lot of them e.g)

## Call to Ubiquity Meta Pool on chain
![A](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/11a748bf-577f-43e5-b766-e826bec02093)

these tests were refactored to work on mainnet accordignly, we can see there we cannot call `.consult()` to ubiquity metapool with fake ABI, likewise we cannot call fake metapool and expect to gives us mainnet data, which in turn goes to my point where

CreditNftManager
CreditNftRedemption
CreditRedemptionCalculator

are nowhere mainnet, they're not even in `deployments.json`

**Comment by rndquu** [comment]
We have pretty fast local (in a none-forked environment) unit tests so I don't see many reasons to refactor for mainnet forking. At the current project stage adding mainnet forking in unit tests only gives us RPC rate limit errors and more failing builds which brings us back to tasks like "select the best RPC during tests execution".

I agree that we shouldn't tests [mocks](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/mocks) but perhaps a better approach would be to completely remove the [mocks](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/mocks) folder and refactor tests with **local** (i.e. without on-chain forking) contract instances deploying them from scratch if necessary.

We should definitely write tests for a forked mainnet environment but as a part of integration testing, not unit one. Besides we don't have a production deploy yet so there isn't much to fork.

@molecula451 You may create a PR with what you've done so far, perhaps we can omit refactoring for "none-forkable" tests

**Comment by 0x4007** [comment]
> RPC rate limit errors

For whatever its worth, we can use our own internal Ubiquity RPCs now which should alleviate rate limit errors.

**Comment by rndquu** [comment]
> > RPC rate limit errors
> 
> For whatever its worth, we can use our own internal Ubiquity RPCs now which should alleviate rate limit errors.

https://eth.ubq.fi/v1/mainnet

**Comment by molecula451** [comment]
> > > RPC rate limit errors
> > 
> > 
> > For whatever its worth, we can use our own internal Ubiquity RPCs now which should alleviate rate limit errors.
> 
> https://eth.ubq.fi/v1/mainnet

https://github.com/ubiquity/ubiquity-dollar/compare/development...molecula451:ubiquity-dollar:save-changes

**Comment by molecula451** [comment]
> I agree that we shouldn't tests [mocks](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/mocks) but perhaps a better approach would be to completely remove the [mocks](https://github.com/ubiquity/ubiquity

We can't just get rid of the [mocks](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/mocks) folder as there are many other unit tests that depends on it and are not on mainnet, the above changes drastically reduces mock dependencies on applicable test, and fork mainnet instead, but we shall still have it

**Comment by 0x4007** [comment]
> > > RPC rate limit errors
> > 
> > 
> > For whatever its worth, we can use our own internal Ubiquity RPCs now which should alleviate rate limit errors.
> 
> https://eth.ubq.fi/v1/mainnet

I think it is responsible for us to consider this RPC endpoint a secret in order to prevent abuse from the community. Why don't we add this as an environment variable in the tests instead of hardcoding?

**Comment by molecula451** [comment]
> > > > RPC rate limit errors
> > > 
> > > 
> > > For whatever its worth, we can use our own internal Ubiquity RPCs now which should alleviate rate limit errors.
> > 
> > 
> > https://eth.ubq.fi/v1/mainnet
> 
> I think it is responsible for us to consider this RPC endpoint a secret in order to prevent abuse from the community. Why don't we add this as an environment variable in the tests instead of hardcoding?

I can change the read to enviroment point but it will throw action build, i think i'd be good if you manually point in your projects secrets, but i also find non trivial hardcoding the RPC as long as the team maintains it as such

**Comment by 0x4007** [comment]
> throw action build

We can easily add to the repository secrets if you're talking about the GitHub Action build CI. 

> i also find non trivial hardcoding the RPC as long as the team maintains it as such

I don't understand what you mean

**Comment by molecula451** [comment]
> > throw action build
> 
> We can easily add to the repository secrets if you're talking about the GitHub Action build CI.

+1 
> > i also find non trivial hardcoding the RPC as long as the team maintains it as such
> I don't understand what you mean

as long at the team maintains the RPC endpoint, there should not be an issue for the hardcode variable

**Comment by 0x4007** [comment]
Hardcoding exposes it to the community, which means that it can be abused easily and we will have infrastructure issues.

**Comment by molecula451** [comment]
> Hardcoding exposes it to the community, which means that it can be abused easily and we will have infrastructure issues.

i agree, tho i commited as such to pass the CI for review,

changed in https://github.com/molecula451/ubiquity-dollar/commit/623821258c3ddde2be2fa99c4209ded545ba51f5


https://github.com/ubiquity/ubiquity-dollar/assets/41552663/6c78650d-be99-4684-9fce-c016de4172d7

**Comment by 0x4007** [comment]
It seems like the video you posted doesn't work for me.

**Comment by molecula451** [comment]
> It seems like the video you posted doesn't work for me.

it should, but dropboxed here https://www.dropbox.com/s/fwc97cysi301rot/rpc.mp4?dl=0

**Comment by molecula451** [comment]
> Please set your wallet address by using the `/wallet` command.
> 
> ```
> /wallet example.eth
> /wallet 0xBf...CdA
> ```
> 
> @molecula451

/wallet 0x4D0704f400D57Ba93eEa88765C3FcDBD826dCFc4

**Comment by molecula451** [comment]
thank you @pavlovcik && @rndquu
