### ISSUE TITLE
Low Security issue, Decrement storage slot hashes by one 

### ISSUE THREAD

**Issue by eugenioclrc** [pavlovcik/uad-ui#639]
## Description 
The storage slots/hashes have known pre-images. For example [LibCreditRedemptionCalculator.sol#L29-L30](https://github.com/ubiquity/ubiquity-dollar/blob/0c240d095cae6be599e020a8a6ba4d0a5fcf51c6/packages/contracts/src/dollar/libraries/LibCreditRedemptionCalculator.sol#L29-L30), [LibBondingCurve.sol#L19-L20](https://github.com/ubiquity/ubiquity-dollar/blob/0c240d095cae6be599e020a8a6ba4d0a5fcf51c6/packages/contracts/src/dollar/libraries/LibBondingCurve.sol#L19-L20), there are many others instances with the same issue.

## Recommendation
Quote from [EIP-1967](https://eips.ethereum.org/EIPS/eip-1967)
> Furthermore, a -1 offset is added so the preimage of the hash cannot be known, further reducing the chances of a possible attack.

Current implementation is;
`bytes32 constant SLOT = keccak256("path.to.slot");`

Change it to:
`bytes32 constant SLOT = bytes32(uint256(keccak256("path.to.slot")) -1);`

**Comment by rndquu** [comment]
@pavlovcik @eugenioclrc 

Regarding the following tasks:
- https://github.com/ubiquity/ubiquity-dollar/issues/639
- https://github.com/ubiquity/ubiquity-dollar/issues/644
- https://github.com/ubiquity/ubiquity-dollar/issues/645
- https://github.com/ubiquity/ubiquity-dollar/issues/646
- https://github.com/ubiquity/ubiquity-dollar/issues/647

Most of those issues would be caught by slither and should be fixed simply based on slither report.

Right now there are tons of issues in the contracts but we can't afford opening an issue for each "best practise" recommendation.

We should start this way:
1. Update docs and integration tests (I'm working on it now) 
2. Fix slither errors
3. Fix smt (or any other symbolic execution tool) errors
4. Add fuzzing tests and fix errors
5. Add invariant tests and fix errors
6. Get a 3rd party security audit

This way we can hope that product is bug free (but you never know).

@eugenioclrc We have a task for [slither errors](https://github.com/ubiquity/ubiquity-dollar/issues/536). What you can do:
1. Run slither against the project and check the report
2. Propose how much time (along with overall bounty price) it should take to fix the errors (perhaps we should break it to smaller issues)
3. Then we could update description [here](https://github.com/ubiquity/ubiquity-dollar/issues/536) and assign it to you

**Comment by 0x4007** [comment]
I think that sounds like a great plan. Thanks for your input rndquu.

**Comment by eugenioclrc** [comment]
https://github.com/ubiquity/ubiquity-dollar/pull/640
