### ISSUE TITLE
Solidity imported libraries should have a version

### ISSUE THREAD

**Issue by eugenioclrc** [pavlovcik/uad-ui#643]
Currently its not clear what version of used libraries the protocolo is using;
https://github.com/ubiquity/ubiquity-dollar/blob/development/.gitmodules

What should be done:
1. Remove tags (because they are [not working](https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule) in git submodules) and add branch names to [git submodules](https://github.com/ubiquity/ubiquity-dollar/blob/development/.gitmodules) (perhaps this requires some code refactoring, make sure that [libs](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/lib) are also updated after settings branch names)
2. Remove duplicate entries in [git submodules](https://github.com/ubiquity/ubiquity-dollar/blob/development/.gitmodules)

**Comment by 0x4007** [comment]
@rndquu @zgorizzo69 any inputs on this?

**Comment by eugenioclrc** [comment]
> @rndquu @zgorizzo69 any inputs on this?

I could take it but first I want to hear your opinions

**Comment by rndquu** [comment]
@eugenioclrc 

So in the end in [git submodules](https://github.com/ubiquity/ubiquity-dollar/blob/development/.gitmodules) we will have smth similar to:
```
[submodule "packages/contracts/lib/openzeppelin-contracts"]
	path = packages/contracts/lib/openzeppelin-contracts
	url = https://github.com/OpenZeppelin/openzeppelin-contracts
        branch = release-v4.9
[submodule "packages/contracts/lib/forge-std"]
	path = packages/contracts/lib/forge-std
	url = https://github.com/foundry-rs/forge-std
	branch = v1
```

Questions:
1. Is the above example correct?
2. This way we will no more have the ability to use `forge update` but use only `git submodule update --remote`, right? (in this case it would be nice to have a separate script in `package.json` like `forge:update` that uses `git submodule update --remote` under the hood)

Also some dependencies may be broken after such an update so perhaps this task also requires some refactoring.

Overall the issue looks good.

**Comment by eugenioclrc** [comment]
> @eugenioclrc
> 
> So in the end in [git submodules](https://github.com/ubiquity/ubiquity-dollar/blob/development/.gitmodules) we will have smth similar to:
> 
> ```
> [submodule "packages/contracts/lib/openzeppelin-contracts"]
> 	path = packages/contracts/lib/openzeppelin-contracts
> 	url = https://github.com/OpenZeppelin/openzeppelin-contracts
>         branch = release-v4.9
> [submodule "packages/contracts/lib/forge-std"]
> 	path = packages/contracts/lib/forge-std
> 	url = https://github.com/foundry-rs/forge-std
> 	branch = v1
> ```
> 
> Questions:
> 
> 1. Is the above example correct?
> 2. This way we will no more have the ability to use `forge update` but use only `git submodule update --remote`, right? (in this case it would be nice to have a separate script in `package.json` like `forge:update` that uses `git submodule update --remote` under the hood)
> 
> Also some dependencies may be broken after such an update so perhaps this task also requires some refactoring.
> 
> Overall the issue looks good.

1) Yes, you are correct
2) i think that instead of `forge update` a simple `forge install` should be enough, and if you want to update the lib you just change the `branch`, another suggestion could be using `package.json` to handle the libraries. This is an example of a project using that config; [package.json#L25-L31](https://github.com/code-423n4/2023-05-juicebox/blob/main/juice-buyback/package.json#L25-L31)

**Comment by rndquu** [comment]
> another suggestion could be using package.json to handle the libraries

I think setting branch name in git submodules should be enough at the current project stage. 

Migrating to `package.json` has some drawbacks:
1. Not a "native" way to install dependencies in foundry framework
2. New devs who come to the project would expect dependencies in the `lib` folder (because this is a foundry project)
3. Something should definitely be broken (some CI actions or scripts) if we remove the `lib` folder with git submodules

**Comment by PhantomCracker** [comment]
Assign does not work anymore? Or it is because another PR was merged? (from what i have checked, the other PR does not solve this issue)

**Comment by 0x4007** [comment]
We just pushed a big update to the bot and there are some big stability issues at the moment - sorry about that @PhantomCracker.

@0xcodercrane

**Comment by cuddle-dev** [comment]
big apologize here @PhantomCracker

**Comment by PhantomCracker** [comment]
> big apologize here @PhantomCracker

No worries 👍

**Comment by rndquu** [comment]
@PhantomCracker hi, I'm trying to reproduce the update to specific lib versions and it seems that `git submodule update --init --remote` updates only to the latest lib version ignoring any [git submodule tags](https://github.com/ubiquity/ubiquity-dollar/blob/development/.gitmodules#L20)

So here is a list of improvements:
1. Git [submodule tags](https://github.com/ubiquity/ubiquity-dollar/blob/development/.gitmodules#L20) do not a affect the updated lib version. We should use an exact [branch name](https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule) instead
2. We keep using the old libs [here](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/lib). This task implied all dependencies to be updated to the latest version. 

Could you fix those issues?

**Comment by PhantomCracker** [comment]
@rndquu I made this commit for this pull request, can you please check it? 
https://github.com/ubiquity/ubiquity-dollar/pull/661/commits/d554cbd2bc8ec4537dd03c319a141fe2f2d15c0e
Also, if we include both branch and tags, tags have priority over branches

**Comment by rndquu** [comment]
@PhantomCracker 

Regarding this commit https://github.com/ubiquity/ubiquity-dollar/commit/d554cbd2bc8ec4537dd03c319a141fe2f2d15c0e
1. The idea is right, we should set branch names with exact versions (for example `branch = chore/v1.5.6` for `forge-std`) instead of tags because according to [this](https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule) and according to what I've recently tested tags are not working in git submodules
2. Commit hashes [here](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/lib) must match the specified branches in git submodules, i.e. you should first set branch names, then run `forge update` (which will updated commit hashes in the `lib` folder) and finally run `forge test` to check that nothing is broken

**Comment by PhantomCracker** [comment]
@rndquu I have updated the code on this pull request: https://github.com/ubiquity/ubiquity-dollar/pull/665

**Comment by 0x4007** [comment]
Looks like a few hunters are trying to hunt this bounty. @rndquu can you take this reviewing over and make sure thats its handled correctly?

**Comment by 0x4007** [comment]
> Looks like a few hunters are trying to hunt this bounty. @rndquu can you take this reviewing over and make sure thats its handled correctly?

Congratulations @AnakinSkywalkeer you prevailed as the strongest hunter.

**Comment by 0x4007** [comment]
@0xcodercrane  it looks like we generated two payment permits for this issue. Shouldn't this not be possible?

**Comment by ghost** [comment]
> > Looks like a few hunters are trying to hunt this bounty. @rndquu can you take this reviewing over and make sure thats its handled correctly?
> 
> Congratulations @AnakinSkywalkeer you prevailed as the strongest hunter.

Cool! :)

**Comment by ghost** [comment]
> ### [ **[ CLAIM 200 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiOTg2Nzk3MDQ4NjY0Njc4OTczODgxNTk1MjQ3NTYwMTAwNTAxNDg1MDY5NDE5Nzg2NDA1NzM3MTUxODAzMjU4MTI3MTk5Mjk1NDY4MCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4MmJCYzZhODMxNDA0NGQ3MDY4NEM3NENmQTBFMTE3ZWI3NUUzNzA4YyIsInJlcXVlc3RlZEFtb3VudCI6IjIwMDAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4Zjg3Y2E0NTgzQzc5MjIxMmU1MjcyMGQxMjdFN0UwQTM4QjgxOGFEMSIsInNpZ25hdHVyZSI6IjB4ZWNiNjVlZDU0YjJlZTdhMGZmYWQ1YWZmODMxNGVlZjY4NGY4MGRjYjc4YzE4YjRlYTlmNTg4ZTA4M2EwZmExMTQ1NDZkNDY2YmVmYTIzY2I4MWQwNDA5NTc2MTViNWIxYWQwODk2NmI2NGM1Nzc4ODAyZTVlMTE1Y2RjZDM5MjQxYiJ9)
> `0x2bBc6a83...b75E3708c`

@pavlovcik hey can u help me with this like i conected my metamask then i clicked claim it gave me 
"PERMIT ALREADY CLAIMED" but i didn't receive 🤔

**Comment by rndquu** [comment]
> > ### [ **[ CLAIM 200 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiOTg2Nzk3MDQ4NjY0Njc4OTczODgxNTk1MjQ3NTYwMTAwNTAxNDg1MDY5NDE5Nzg2NDA1NzM3MTUxODAzMjU4MTI3MTk5Mjk1NDY4MCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4MmJCYzZhODMxNDA0NGQ3MDY4NEM3NENmQTBFMTE3ZWI3NUUzNzA4YyIsInJlcXVlc3RlZEFtb3VudCI6IjIwMDAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4Zjg3Y2E0NTgzQzc5MjIxMmU1MjcyMGQxMjdFN0UwQTM4QjgxOGFEMSIsInNpZ25hdHVyZSI6IjB4ZWNiNjVlZDU0YjJlZTdhMGZmYWQ1YWZmODMxNGVlZjY4NGY4MGRjYjc4YzE4YjRlYTlmNTg4ZTA4M2EwZmExMTQ1NDZkNDY2YmVmYTIzY2I4MWQwNDA5NTc2MTViNWIxYWQwODk2NmI2NGM1Nzc4ODAyZTVlMTE1Y2RjZDM5MjQxYiJ9)
> > `0x2bBc6a83...b75E3708c`
> 
> @pavlovcik hey can u help me with this like i conected my metamask then i clicked claim it gave me "PERMIT ALREADY CLAIMED" but i didn't receive 🤔

What happened:
1. Originally @PhantomCracker solved the current issue
2. Permit was [generated](https://github.com/ubiquity/ubiquity-dollar/issues/643#issuecomment-1569384273)
3. Then the issue was [opened](https://github.com/ubiquity/ubiquity-dollar/issues/643#issuecomment-1573415281) again because of the errors
4. @AnakinSkywalkeer solved the issue correctly
5. New permit was [generated](https://github.com/ubiquity/ubiquity-dollar/issues/643#issuecomment-1607260128)

Permits from step 2 and 5 have the same nonce. Permit from step 2 has already been claimed so permit from step 5 is invalid.

@pavlovcik help

**Comment by ghost** [comment]
> > > ### [ **[ CLAIM 200 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiOTg2Nzk3MDQ4NjY0Njc4OTczODgxNTk1MjQ3NTYwMTAwNTAxNDg1MDY5NDE5Nzg2NDA1NzM3MTUxODAzMjU4MTI3MTk5Mjk1NDY4MCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4MmJCYzZhODMxNDA0NGQ3MDY4NEM3NENmQTBFMTE3ZWI3NUUzNzA4YyIsInJlcXVlc3RlZEFtb3VudCI6IjIwMDAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4Zjg3Y2E0NTgzQzc5MjIxMmU1MjcyMGQxMjdFN0UwQTM4QjgxOGFEMSIsInNpZ25hdHVyZSI6IjB4ZWNiNjVlZDU0YjJlZTdhMGZmYWQ1YWZmODMxNGVlZjY4NGY4MGRjYjc4YzE4YjRlYTlmNTg4ZTA4M2EwZmExMTQ1NDZkNDY2YmVmYTIzY2I4MWQwNDA5NTc2MTViNWIxYWQwODk2NmI2NGM1Nzc4ODAyZTVlMTE1Y2RjZDM5MjQxYiJ9)
> > > `0x2bBc6a83...b75E3708c`
> > 
> > 
> > @pavlovcik hey can u help me with this like i conected my metamask then i clicked claim it gave me "PERMIT ALREADY CLAIMED" but i didn't receive 🤔
> 
> What happened:
> 
> 1. Originally @PhantomCracker solved the current issue
> 2. Permit was [generated](https://github.com/ubiquity/ubiquity-dollar/issues/643#issuecomment-1569384273)
> 3. Then the issue was [opened](https://github.com/ubiquity/ubiquity-dollar/issues/643#issuecomment-1573415281) again because of the errors
> 4. @AnakinSkywalkeer solved the issue correctly
> 5. New permit was [generated](https://github.com/ubiquity/ubiquity-dollar/issues/643#issuecomment-1607260128)
> 
> Permits from step 2 and 5 have the same nonce. Permit from step 2 has already been claimed so permit from step 5 is invalid.
> 
> @pavlovcik help

ohhh

**Comment by PhantomCracker** [comment]
Maybe we need to create a new issue every time an error occurs instead of reopen the old ones?

P.S: Good job @AnakinSkywalkeer

**Comment by 0x4007** [comment]
> Maybe we need to create a new issue every time an error occurs instead of reopen the old ones?

This was not implemented correctly the first time around so it should not have been accepted and paid out.

---

@AnakinSkywalkeer `0x2bBc6a8314044d70684C74CfA0E117eb75E3708c` can you verify that this is your address?

**Comment by ghost** [comment]
> > Maybe we need to create a new issue every time an error occurs instead of reopen the old ones?
> 
> This was not implemented correctly the first time around so it should not have been accepted and paid out.
> 
> @AnakinSkywalkeer `0x2bBc6a8314044d70684C74CfA0E117eb75E3708c` can you verify that this is your address?

yes its my address  0x2bBc6a8314044d70684C74CfA0E117eb75E3708c

**Comment by 0x4007** [comment]
> > > ### [ **[ CLAIM 200 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiOTg2Nzk3MDQ4NjY0Njc4OTczODgxNTk1MjQ3NTYwMTAwNTAxNDg1MDY5NDE5Nzg2NDA1NzM3MTUxODAzMjU4MTI3MTk5Mjk1NDY4MCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4MmJCYzZhODMxNDA0NGQ3MDY4NEM3NENmQTBFMTE3ZWI3NUUzNzA4YyIsInJlcXVlc3RlZEFtb3VudCI6IjIwMDAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4Zjg3Y2E0NTgzQzc5MjIxMmU1MjcyMGQxMjdFN0UwQTM4QjgxOGFEMSIsInNpZ25hdHVyZSI6IjB4ZWNiNjVlZDU0YjJlZTdhMGZmYWQ1YWZmODMxNGVlZjY4NGY4MGRjYjc4YzE4YjRlYTlmNTg4ZTA4M2EwZmExMTQ1NDZkNDY2YmVmYTIzY2I4MWQwNDA5NTc2MTViNWIxYWQwODk2NmI2NGM1Nzc4ODAyZTVlMTE1Y2RjZDM5MjQxYiJ9)
> > > `0x2bBc6a83...b75E3708c`
> > 
> > @pavlovcik hey can u help me with this like i conected my metamask then i clicked claim it gave me "PERMIT ALREADY CLAIMED" but i didn't receive 🤔
> 
> What happened:
> 1. Originally @PhantomCracker solved the current issue
> 2. Permit was [generated](https://github.com/ubiquity/ubiquity-dollar/issues/643#issuecomment-1569384273)
> 3. Then the issue was [opened](https://github.com/ubiquity/ubiquity-dollar/issues/643#issuecomment-1573415281) again because of the errors
> 4. @AnakinSkywalkeer solved the issue correctly
> 5. New permit was [generated](https://github.com/ubiquity/ubiquity-dollar/issues/643#issuecomment-1607260128)
> 
> Permits from step 2 and 5 have the same nonce. Permit from step 2 has already been claimed so permit from step 5 is invalid.
> 
> @pavlovcik help

@rndquu shouldn't it show "permit already claimed" as soon as the page loads? I remember seeing claimed permits being recognized with no user interaction on the dApp.

**Comment by 0x4007** [comment]
https://gnosisscan.io/tx/0xb0ff172f5af182942f0bad6e96fec98595eabfbccb7c356e674fe503908fc041 @AnakinSkywalkeer

**Comment by eugenioclrc** [comment]
Gnosis?? Cool!!!

**Comment by ghost** [comment]
> https://gnosisscan.io/tx/0xb0ff172f5af182942f0bad6e96fec98595eabfbccb7c356e674fe503908fc041 @AnakinSkywalkeer 

Thanks!! I received it

**Comment by 0x4007** [comment]
> ### [**[ CLAIM 200 WXDAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHhlOTFEMTUzRTBiNDE1MThBMkNlOERkM0Q3OTQ0RmE4NjM0NjNhOTdkIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiOTg2Nzk3MDQ4NjY0Njc4OTczODgxNTk1MjQ3NTYwMTAwNTAxNDg1MDY5NDE5Nzg2NDA1NzM3MTUxODAzMjU4MTI3MTk5Mjk1NDY4MCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4MmJCYzZhODMxNDA0NGQ3MDY4NEM3NENmQTBFMTE3ZWI3NUUzNzA4YyIsInJlcXVlc3RlZEFtb3VudCI6IjIwMDAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4Zjg3Y2E0NTgzQzc5MjIxMmU1MjcyMGQxMjdFN0UwQTM4QjgxOGFEMSIsInNpZ25hdHVyZSI6IjB4ZWNiNjVlZDU0YjJlZTdhMGZmYWQ1YWZmODMxNGVlZjY4NGY4MGRjYjc4YzE4YjRlYTlmNTg4ZTA4M2EwZmExMTQ1NDZkNDY2YmVmYTIzY2I4MWQwNDA5NTc2MTViNWIxYWQwODk2NmI2NGM1Nzc4ODAyZTVlMTE1Y2RjZDM5MjQxYiJ9)
> `0x2bBc6a83...b75E3708c`

Invalidated https://gnosisscan.io/tx/0xe8ca542d6e4fe579ccc8f04f12179476989f58d85b162aa863a36719f73de232
