### ISSUE TITLE
Refactor to `ERC20Ubiquity`

### ISSUE THREAD

**Issue by eugenioclrc** [pavlovcik/uad-ui#644]
There are a few things to solve in `ERC20Ubiquity`

- [x] Import of [`ERC20Burnable`](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/ERC20Ubiquity.sol#L4) is not used 
- [x] OZ already have an `ERC20Permit` implementation, `ERC20Ubiquity` could use it to have a simpler contract
- [x] `_tokenName` and `_symbol` is already set in the `ERC20` it should be redefined
- [x] `name` and `symbol` should not change, also if the admin change it, it will create conflicts with the `DOMAIN_SEPARATOR` see [ERC20Ubiquity.sol#L64](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/ERC20Ubiquity.sol#L64)

I would also recommend to implement solmate ERC20 implementation, is more gas efficient and it has `ERC20Permit` by default but you will have to do a deeper refactor.

**Comment by 0x4007** [comment]
Could you provide a rough time estimate for implementation? I'm assuming it can be done within a day.

---

> name and symbol should not change, also if the admin change it, it will create conflicts with the DOMAIN_SEPARATOR see [ERC20Ubiquity.sol#L64](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/ERC20Ubiquity.sol#L64)

We wanted to preserve the ability to rename. Is there a way to prioritize this while not breaking the functionality of `DOMAIN_SEPARATOR`? I don't even know what that is used for to be honest.

---

@zgorizzo69 what do you think about this proposal?

**Comment by eugenioclrc** [comment]
All these tasks can indeed be accomplished within a day. However, i would recommend a separate task for the refactoring to use solmate. This should be addressed after initial refactor, and it could require additional time.

**Comment by eugenioclrc** [comment]
@pavlovcik The `DOMAIN_SEPARATOR` is part of the [`EIP712`](https://eips.ethereum.org/EIPS/eip-712) and in this case is use for the `ERC20Permit` see [OZ Implementation](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Permit.sol#L44)

**Comment by eugenioclrc** [comment]
this issue should be resolved before this refactor;
https://github.com/ubiquity/ubiquity-dollar/issues/643

**Comment by 0x4007** [comment]
> However, i would recommend a separate task for the refactoring to use solmate. This should be addressed after initial refactor, and it could require additional time.

Please feel free to create the bounty when you're ready.

**Comment by zgorizzo69** [comment]
Yep valid points thanks @eugenioclrc

**Comment by eugenioclrc** [comment]
@pavlovcik @zgorizzo69 im having some issues here, with this refactor i have remove multiple lines, that means that coverage metrics will get lower (the ERC20Permit lib is excluded from coverage), thats why its not passing the coverage task in the github actions.
Got any suggestions?

**Comment by eugenioclrc** [comment]
> @pavlovcik @zgorizzo69 im having some issues here, with this refactor i have remove multiple lines, that means that coverage metrics will get lower (the ERC20Permit lib is excluded from coverage), thats why its not passing the coverage task in the github actions. Got any suggestions?

nevermind, i solved, it seems that somehow the coverage thought that the method `unpaused` wasnt test it... i solved adding a extra test condition;
https://github.com/ubiquity/ubiquity-dollar/pull/649/commits/71cf980879cf907ab1accc0c3f47a7002c8e0294

**Comment by eugenioclrc** [comment]
> Do you have any updates @eugenioclrc? If you would like to release the bounty back to the DevPool, please comment `/unassign`

@pavlovcik @zgorizzo69 the work is ready, why the bot is asking if I have finished?

**Comment by eugenioclrc** [comment]
#649

**Comment by 0x4007** [comment]
My apologies. Unfortunately @zgorizzo69 hasn't had the time to review yet and their review is required to merge pull requests on this repository. I sent them a message to check soon. Thanks for your patience! 

In the future the bot will check for the review status to not follow up with the bounty hunter unless needed.
