### ISSUE TITLE
`call()` should be used instead of `transfer()` to transfer ether.

### ISSUE THREAD

**Issue by eugenioclrc** [pavlovcik/uad-ui#645]
## Summary
`call()` should be used instead of `transfer()` to transfer ether.

Plase view;
- https://www.theblock.co/post/225364/zksync-unfreeze-millions-stuck

## Vulnerability Detail
The `transfer()` and `send()` functions forward a fixed amount of 2300 gas. Historically, it has often been recommended to use these functions for value transfers to guard against reentrancy attacks. However, the gas cost of EVM instructions may change significantly during hard forks which may break already deployed contract systems that make fixed assumptions about gas costs. For example. EIP 1884 broke several existing smart contracts due to a cost increase of the SLOAD instruction.

## Impact
The use of the deprecated transfer() function for an address will inevitably make the transaction fail when:

- The claimer smart contract does not implement a payable function.
- The claimer smart contract does implement a payable fallback which uses more than 2300 gas unit.
- The claimer smart contract implements a payable fallback function that needs less than 2300 gas units but is called through proxy, raising the call's gas usage above 2300.
- Additionally, using higher than 2300 gas might be mandatory for some multisig wallets.

## Code Snippet

- [UbiquiStickSale.sol#L122](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/ubiquistick/UbiquiStickSale.sol#L122)
- [UbiquiStickSale.sol#L128](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/ubiquistick/UbiquiStickSale.sol#L128)
- [LibCollectableDust.sol#L65](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/LibCollectableDust.sol#L65)

**Comment by 0x4007** [comment]
Thank you for your research. This is news to me so I don't have input other than the logic you used to come to this conclusion seems sound. 

@zgorizzo69 what do you think?

**Comment by 0x4007** [comment]
@0xcodercrane any idea what happened with the bot yesterday and why the commands stopped working?

@rotcivegaf please be sure to register your payment wallet address with the /wallet command if you haven't already.

**Comment by rotcivegaf** [comment]
Since there are no risks of reentrancy attacks, the ReentrancyGuard could be removed
Do you want there to be another issue for this or I could solve it here

**Comment by eugenioclrc** [comment]
If its dead code I think it should be removed.

**Comment by rotcivegaf** [comment]
Should I do something else?

**Comment by 0x4007** [comment]
Let me follow up with @zgorizzo69 to merge your pull request
