### ISSUE TITLE
`LibAppStorage` is not using `EIP-1967`

### ISSUE THREAD

**Issue by eugenioclrc** [pavlovcik/uad-ui#647]
### Description:

Instead of using `EIP-1967` as in all others facets, the `AppStorage` is setted on slot `0`; [LibAppStorage.sol#L47](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/LibAppStorage.sol#L47)

### Code:
- [LibAppStorage.sol#L38-L44](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/LibAppStorage.sol#L38-L44)

### Recommendation:
Use `LibAppStorage.appStorage()` instead of `store` to accessung the store, also its recommend to use differents store slots for each variable, and instead of changing directly it should have setters and getters for each variable.

```diff
diff --git a/packages/contracts/src/dollar/libraries/LibAppStorage.sol b/packages/contracts/src/dollar/libraries/LibAppStorage.sol
index 148ee493..7b52c905 100644
--- a/packages/contracts/src/dollar/libraries/LibAppStorage.sol
+++ b/packages/contracts/src/dollar/libraries/LibAppStorage.sol
@@ -36,16 +36,18 @@ struct AppStorage {
 }
 
 library LibAppStorage {
+    bytes32 constant private APP_STORAGE_STORAGE_SLOT = 
+        bytes32(uint256(keccak256("ubiquity.contracts.curve.storage")) - 1);
+    
     function appStorage() internal pure returns (AppStorage storage ds) {
+        bytes32 position = APP_STORAGE_STORAGE_SLOT;
         assembly {
-            ds.slot := 0
+            ds.slot := position
         }
     }
 }
 
 contract Modifiers {
-    AppStorage internal store;
-
     /**
      * @dev Prevents a contract from calling itself, directly or indirectly.
      * Calling a `nonReentrant` function from another `nonReentrant`
```

**Comment by zgorizzo69** [comment]
IMO it is not an issue and using EIP-1967 will decrease readability 
check it here : https://eip2535diamonds.substack.com/p/introduction-to-the-diamond-standard

**Comment by rndquu** [comment]
Does anybody know why [claim URL price](https://github.com/ubiquity/ubiquity-dollar/issues/647#issuecomment-1565445683) is 12.5 DAI while the price label is 25 DAI ? I expect claim URL price to be 25 DAI as the price label states

**Comment by 0x4007** [comment]
I presume it is because it fell back to the organization wide `ubiquibot-config.yml` (`base-rate: 1000`) because we migrated from camel case to kebab case property names. 

`baseRate: 2000` from the config on this repository was not read.
