### ISSUE TITLE
Bot Deploys Comment Should Include Commit Hashes

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#663]
I was trying to understand which commit corresponds to which deployment but the commit hashes don't seem to match based on what I see inside of the rendered dApp. 

The deployment links from the bot also do not include the commit hashes. 

Verifying by timestamp seems unnecessarily imprecise.

> [Deployment: Mon May 29 2023 10:18:51 (UTC)](https://64747bfbcc5035619c6b2463--ubiquity-dollar.netlify.app)
> [Deployment: Mon May 29 2023 11:48:24 (UTC)](https://647490fde519217706996dfd--ubiquity-dollar.netlify.app)
> [Deployment: Mon May 29 2023 13:27:19 (UTC)](https://6474a82b9837770a9c41cb82--ubiquity-dollar.netlify.app)
> [Deployment: Mon May 29 2023 13:38:49 (UTC)](https://6474aade82d509062db6fbe1--ubiquity-dollar.netlify.app)
> [Deployment: Mon May 29 2023 13:42:03 (UTC)](https://6474ab9fae27a57ec36fe779--ubiquity-dollar.netlify.app)

_Originally posted by @ubiquibot[bot] in https://github.com/ubiquity/ubiquity-dollar/issues/661#issuecomment-1566917449_

**Comment by 0x4007** [comment]
Due to delays on our end I will make an exception for you @PhantomCracker. Technically speaking even if you are not assigned you are free to open a pull request. However you may be frontran by somebody else who gets assigned.

**Comment by 0x4007** [comment]
This wasn't implemented correctly because the list doesnt grow with new deployments. 

https://github.com/ubiquity/ubiquity-dollar/blob/7e9c8b5e2481a89ebe161458fe687f7e21382fc8/utils/print-deployments-logs.js#L30C82-L30C82

This line is suspicious because its looking for the old "Deployment" string which has been replaced by the hash for example.

**Comment by 0x4007** [comment]
@rndquu I understand that we are using this logic in our [organization wide continuous deploys](https://github.com/ubiquity/.github/blob/main/utils/print-deployments-logs.js). Would you mind prioritizing this and taking this over to make sure its done correctly?

**Comment by PhantomCracker** [comment]
Hm... I see that the issue isn't made by my code; still, I can do this after I finish with 2 more bounties that I am working on it right now.

**Comment by 0x4007** [comment]
I believe you fixed this @rndquu so I was trying to assign and close to you.

**Comment by rndquu** [comment]
> I believe you fixed this @rndquu so I was trying to assign and close to you.

Yes, printing commit hashes is already implemented in a shared cloudflare deploy [workflow](https://github.com/ubiquity/.github/blob/main/.github/workflows/deploy.yml)

**Comment by 0x4007** [comment]
> Error: Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="symbol()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)

Its unusual that only the assignee reward is crashing.
