### ISSUE TITLE
Move payments to a cheaper chain

### ISSUE THREAD

**Issue by rotcivegaf** [pavlovcik/uad-ui#664]
I fix the issue #645, 
The pay was about 25 DAI, today with the low price of gas (26 Gwei) to claim it would cost me 5 usd
About 20% of the payment

Could another blockchain be used for payments? Like polygon, arbitrum, etc
Or group several payments in the same transaction?

**Comment by 0x4007** [comment]
Wrong repo and duplicate https://github.com/ubiquity/ubiquibot/issues/287
