### ISSUE TITLE
Infrastructure For Remote Fork Tests On Selected Networks

### ISSUE THREAD

**Issue by zgorizzo69** [pavlovcik/uad-ui#682]
depends on https://github.com/ubiquity/ubiquity-dollar/issues/683

we need a way to handle remote tests. Here are a list of feature that we want for our remote fork tests

- we should be able to easily select a fork from any mainnet 
- we should be able to get the address of contracts in-use in our repo from this fork (i.e DAI, WETH) with there symbol
- we should be able to easily add new network to fork 
- we should be able to easily get addresses of our deployed contracts with a label
- we should be able to fork from a specific block number
- the solutions should also work for deployment script. Meaning we should be able to easily get addresses in our scripts . can be cool to also be able to get some through env var

**Comment by zgorizzo69** [comment]
it started from [here](https://github.com/ubiquity/ubiquity-dollar/pull/680#pullrequestreview-1482439456)

**Comment by rndquu** [comment]
we first need at least a development deploy to one of the testnets, updated the description so that this task depends on https://github.com/ubiquity/ubiquity-dollar/issues/683

**Comment by malik672** [comment]
@rndquu you can do all this though foundry

**Comment by rndquu** [comment]
@malik672 don't you have any questions regarding the issue?

> we should be able to easily select a fork from any mainnet

Any mainnet? What networks exactly should we support?

> we should be able to get the address of popular contract from this fork (i.e DAI, WETH) with there symbol

Popular contract? What contracts exactly should we support?

> we should be able to easily get addresses of our deployed contracts with a label

We moved to the diamond storage and don't have a production deploy yet.  So it is not clear (at least for me) what "deployed contracts" we should get.

**Comment by malik672** [comment]
@rndquu yes , the thing is you can do all this with foundry, it's just a few commands and setting up foundry toml

**Comment by 0x4007** [comment]
> @rndquu yes , the thing is you can do all this with foundry, it's just a few commands and setting up foundry toml

Could you share how to do that? We can verify if it solves the specification.

**Comment by malik672** [comment]
From the foundry book
```
[How do I fork from a live network?](https://book.getfoundry.sh/faq?highlight=fork#how-do-i-fork-from-a-live-network)
To fork from a live network, pass --fork-url <URL> to [forge test](https://book.getfoundry.sh/reference/forge/forge-test.html). You can also fork from a specific block using --fork-block-number <BLOCK>, which adds determinism to your test, and allows Forge to cache the chain data for that block.

For example, to fork from Ethereum mainnet at block 10,000,000 you could use: forge test --fork-url $MAINNET_RPC_URL --fork-block-number 10000000.


```

**Comment by malik672** [comment]
1. Selecting a fork from any mainnet is actually easy you can just run: `forge test --fork-url <your_rpc_url>` and pass in the url of the mainnet you want to fork
2. you will have to search for this by yourself one of the easiest ways to do this is to search this is to use uniswap, since it supports goerli,mumbai,sepolia and lots of chains
3. same as number 1, just pass the url
4. when ever you use foundry to deploy contracts through the cli(obviously), it returns the deployed address with the contract name to show the contract that was deployed
5. you can do that by using `forge test --fork-url <your_rpc_url> --fork-block-number 1`, replace 1 with the specified block number of your choice
6. same as 5
7. to read more check the foundry book [https://book.getfoundry.sh/forge/fork-testing?highlight=fork#forking-mode](url)

**Comment by malik672** [comment]
@pavlovcik is this what you wanted?

**Comment by 0x4007** [comment]
> @pavlovcik is this what you wanted?

@zgorizzo69 will know best if this solves the problem.

**Comment by rndquu** [comment]
I guess this task implied a **code infrastructure** but not links to foundry docs. Some points in the original description are not clear so this task should be converted to a discussion.

**Comment by zgorizzo69** [comment]
> @malik672 don't you have any questions regarding the issue?
> 
> > we should be able to easily select a fork from any mainnet
> 
> Any mainnet? What networks exactly should we support?


Yes we should be able to support any main et easily


> 
> > we should be able to get the address of popular contract from this fork (i.e DAI, WETH) with there symbol
> 
> Popular contract? What contracts exactly should we support?

Check the code and existing contract to extract the contract we should support but it must be easy to add/ remove them for any mainnet
> 
> > we should be able to easily get addresses of our deployed contracts with a label
> 
> We moved to the diamond storage and don't have a production deploy yet. So it is not clear (at least for me) what "deployed contracts" we should get.

The contract we have already deployed check the documentation to find out the addresses

**Comment by zgorizzo69** [comment]
> @pavlovcik is this what you wanted?

Nop I had in mind using VM.createfork etc.. inside a set classes that we can inherit from and some config files where we can put the contract addresses
Then we just instantiate/inherit from these classes to activate a fork and access the common/deployed contract

**Comment by malik672** [comment]
but why put the contract address in a config file

**Comment by malik672** [comment]
> > @pavlovcik is this what you wanted?
> 
> Nop I had in mind using VM.createfork etc.. inside a set classes that we can inherit from and some config files where we can put the contract addresses Then we just instantiate/inherit from these classes to activate a fork and access the common/deployed contract

i dont still understand, should i write the test file

**Comment by 0x4007** [comment]
> > > @pavlovcik is this what you wanted?
> 
> > 
> 
> > Nop I had in mind using VM.createfork etc.. inside a set classes that we can inherit from and some config files where we can put the contract addresses Then we just instantiate/inherit from these classes to activate a fork and access the common/deployed contract
> 
> 
> 
> i dont still understand, should i write the test file
> 
> 

@rndquu Any ideas here?

**Comment by rndquu** [comment]
> > > > @pavlovcik is this what you wanted?
> > 
> > 
> > > 
> > 
> > 
> > > Nop I had in mind using VM.createfork etc.. inside a set classes that we can inherit from and some config files where we can put the contract addresses Then we just instantiate/inherit from these classes to activate a fork and access the common/deployed contract
> > 
> > 
> > i dont still understand, should i write the test file
> 
> @rndquu Any ideas here?

This issue needs further specification

**Comment by zgorizzo69** [comment]
> but why put the contract address in a config file

So that we have the address of the contract deployed on the different networks

**Comment by rndquu** [comment]
I think we should close this issue as "not planned" and get back to it when we have necessity in forked unit tests. 

@gitcoindev @molecula451 What do you think?

**Comment by molecula451** [comment]
our **updated** [contract testing](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/test) tests are working as planned, we can come back to this task when we actually need forked and newly introduced tests on mainnet, probably when deployement it's done
