### ISSUE TITLE
Development Environments

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#683]
### Discussed in https://github.com/ubiquity/ubiquity-dollar/discussions/652

<div type='discussions-op-text'>

<sup>Originally posted by **rndquu** May 24, 2023</sup>
Let's use different environments for https://uad.ubq.fi/

I mean:
1. setup https://uad.ubq.fi/ to track `ubiquity/ubiquity-dollar#main` branch for contracts and `ubiquity/ubq.fi#main` branch for UI
2. setup https://dev.uad.ubq.fi/ to track `ubiquity/ubiquity-dollar#development` branch for contracts and `ubiquity/ubq.fi#development` branch for UI
3. setup https://stage.uad.ubq.fi/ to track `ubiquity/ubiquity-dollar#release-X.X.X` branch for contracts and `ubiquity/ubq.fi#X.X.X` branch for UI. Here the `release-X.X.X` branch is the branch that is QAed right now and is about to merged to the `main` branch and deployed to production

This way we could setup different deployment scripts for ubiquity contracts depending on the environment

**Comment by rndquu** [comment]
@pavlovcik 

Regarding smart contracts production deployment: 
1. We are allowed to redeploy all of the [contracts](https://github.com/ubiquity/ubiquity-dollar/wiki/18.-Smart-Contracts), right? 
2. We can't [preserve](https://github.com/ubiquity/ubiquity-dollar/discussions/730#discussioncomment-6413763) the Governance token contract because the new implementation is going to be upgradable. But we can migrate UBQ token balances from the old contract to the new one. Is it ok?
3. Is there something else that we should migrate from the old contracts?

**Comment by 0x4007** [comment]
> 1.

Don't want to redeploy governance token

> 2. 

Not ideal, would want to expire all other options before doing that. The on-chain history adds to its credibility.

> 3.

There's many contracts hard to say off hand to be honest. We should default to migrating all of them and remove specific ones on a case-by-case basis, no?

**Comment by rndquu** [comment]
> We should default to migrating all of them and remove specific ones on a case-by-case basis

ok

**Comment by isreallee82** [comment]
I will like to take this @rndquu

**Comment by rndquu** [comment]
> I will like to take this @rndquu

Sorry, this issue is no longer relevant since:
1. We already have deployment previews thanks to Cloudflare Pages
2. This [PR](https://github.com/ubiquity/ubiquity-dollar/pull/860) introduces a feature of using the contracts from currently selected user network so we don't really need to redeploy everything from scratch on each PR

Perhaps in the future it makes sense to setup auto deploy to testnet on push to the `development` branch but now we're going to deploy manually for simplicity
