### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#692]
Right now we have some compiler [warnings](https://github.com/ubiquity/ubiquity-dollar/actions/runs/5321726749/jobs/9637204382)

What should be done:
1. Fix compiler warnings
2. Make sure [build and test workflow](https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/workflows/build-and-test.yml) fails on any new warning introduced

**Comment by rndquu** [comment]
@pavlovcik could you set a priority?

**Comment by rndquu** [comment]
@pavlovcik 

there is a [2x multiplier](https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/ubiquibot-config.yml#L3) for the current repo

this [issue](https://github.com/ubiquity/ubiquity-dollar/issues/578) worth 300 USD generated a [permit](https://github.com/ubiquity/ubiquity-dollar/issues/578#issuecomment-1607028347) worth 600 WXDAI (which is expected because of the 2x multiplier)

the current issue is worth 200 USD so the [permit](https://github.com/ubiquity/ubiquity-dollar/issues/692#issuecomment-1609438904) was expected to be 400 WXDAI instead of 200 WXDAI

am I right?

**Comment by 0x4007** [comment]
I'm pretty sure the generated permit is current because it was only seven minutes ago

**Comment by rndquu** [comment]
> I'm pretty sure the generated permit is current because it was only seven minutes ago

I don't get you mean by "current". This [permit](https://github.com/ubiquity/ubiquity-dollar/issues/692#issuecomment-1609438904) should be 400 WXDAI because of the [2x multiplier](https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/ubiquibot-config.yml#L3), right?

**Comment by molecula451** [comment]
Thank you guys you fixing it @pavlovcik ?

**Comment by molecula451** [comment]
upss @pavlovcik i think @rndquu is clearer than waters 😁

**Comment by molecula451** [comment]
re-issue 🙏🏻@pavlovcik

**Comment by 0x4007** [comment]
This pricing is accurate for this issue. 

The problem is only in the following scenario: 

1. Base-rate is 1000
2. Bounty is created (price label set to 100 USD)
3. Admin updates base-rate to 2000 
4. Price labels are not automatically updated yet (we have a feature in the works to handle this, but it's not on production as far as I'm aware)
5. Bounty hunter completes the bounty and the payment permit is 200 USD even though the price label is still left at 100 USD. 

---

This current issue was created after the base-rate was updated, so the price label is including the boosted base-rate and is accurate.

**Comment by rndquu** [comment]
> This pricing is accurate for this issue.
> 
> The problem is only in the following scenario:
> 
> 1. Base-rate is 1000
> 2. Bounty is created (price label set to 100 USD)
> 3. Admin updates base-rate to 2000
> 4. Price labels are not automatically updated yet (we have a feature in the works to handle this, but it's not on production as far as I'm aware)
> 5. Bounty hunter completes the bounty and the payment permit is 200 USD even though the price label is still left at 100 USD.
> 
> This current issue was created after the base-rate was updated, so the price label is including the boosted base-rate and is accurate.

Yes, you're right. Normally we have 100 USD for `<1 day` time labels but this issue is already set to 200 USD because of the multiplier. 

@molecula451 pls notice that the pricing is accurate
