### ISSUE TITLE
Update UI for diamond deploy

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#695]
We haven't been updating the [dapp](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/dapp) for a while + we've moved to a diamond proxy so there are a lot of errors in the [dapp:](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/dapp)
<img width="1512" alt="Screenshot 2023-06-21 at 15 59 51" src="https://github.com/ubiquity/ubiquity-dollar/assets/119500907/7d1fe32d-76de-45bf-879d-55cb328d5734">

How to deploy to a local anvil instance:
- Start anvil instance in the 1st terminal: `yarn start:anvil`
- Open the 2nd terminal instance and run `yarn deploy:development`

How to start the dapp:
- In the `dapp` folder run `yarn start`

What should be done:
1. Make the `dapp` to be able to work with diamond contracts (deployed locally)
2. Fix errors (the UI haven't been updated for a while + there was an upgrade from nextjs 12 to nextjs 13) 

So in the end we should get a UI without errors working with diamond contracts deployed on a local anvil instance

**Comment by rndquu** [comment]
@pavlovcik pls check the description

**Comment by 0x4007** [comment]
I think this should be broken down further. Perhaps per view per bounty. Also I think we can delete some views like bonds and vaults. 

I can put more thought into this later because I plan to actually work on the code here to move things forward faster.

**Comment by rndquu** [comment]
> I think this should be broken down further. Perhaps per view per bounty. Also I think we can delete some views like bonds and vaults.
> 
> I can put more thought into this later because I plan to actually work on the code here to move things forward faster.

This task is basically about fixing nextjs13 upgrade issues + moving to diamond proxy, we can add additional tasks per view when this task is ready

**Comment by 0x4007** [comment]
Do you think this is a two day task?

**Comment by rndquu** [comment]
> Do you think this is a two day task?

yes, 1 or 2 days should be enough, notice that I've updated the time label to `<1 day`

**Comment by rndquu** [comment]
There are 2 pending PRs ([one](https://github.com/ubiquity/ubiquity-dollar/pull/704) and [two](https://github.com/ubiquity/ubiquity-dollar/pull/702)) but they seem to be acceptable so I guess we can bypass the rules and assign manually

**Comment by molecula451** [comment]
working on this one, if have udpates will let you know

**Comment by 0x4007** [comment]
> working on this one, if have udpates will let you know

You need to open a draft pull request or it doesn't look like you're working on it.

**Comment by molecula451** [comment]
I think this task needs a bit more input, basically you guys planted to fix some issues with nextjs that's possbile right there, 

afterwards moving to a diamond proxy connection, in essence handling diamonds within the anvil local connection to mimick a front end playground fetching data from the local contracts & transactions, but at the same time rndquu posted a picture of the bonds view, on the other hand theres pavlocik saying bonds & vaults are gonna be purge

so in essence we are left with a plug-in anvil connection to the UI, to **_enable_** a setup for further views  rendering (other tasks)

**Comment by rndquu** [comment]
> but at the same time rndquu posted a picture of the bonds view

The purpose of the screenshot was to show that there are errors. Bonds view was simply the 1st one I opened.

> on the other hand theres pavlocik saying bonds & vaults are gonna be purge

Then you are free to delete bonds and vaults views and related code

> so in essence we are left with a plug-in anvil connection to the UI, to enable a setup for further views rendering (other tasks)

Yes, seems right

**Comment by molecula451** [comment]
`[■■■■■■■■■■ WORK IN PROGRESS ■■■   ] 25%`

**Comment by molecula451** [comment]
while rendering a solution, it looks like to me that for a good architecture we will require to re-integrate hardhat only limited to the plug-in to the anvil node, this shouldn't be at the cost of the foundry development, instead integrating it thoughts on this rndquu

**Comment by 0x4007** [comment]
We intentionally avoided hardhat early on during the foundry conversion and plan to keep doing so. I want to keep our tech stack as lean as we can (within reason) to make our codebase less complicated for new contributors.

**Comment by rndquu** [comment]
> re-integrate hardhat only limited to the plug-in to the anvil node

I don't get what "plug-in to the anvil node" means. Could you describe a particular case? Can't `ethers.js` or `web3.js` do the same job?

**Comment by molecula451** [comment]
> I don't get what "plug-in to the anvil node" means. Could you describe a particular case? Can't `ethers.js` or `web3.js` do the same job?

Yeah but we're essentially not rendering any views on this task, how you'd like to see the debugged? thru console?

to a well crafted architecture of this task we would need hardhat because of the JS playground, that way shall enable me to roll JS tests cases for the connection to the anvil & fully mimick transactions, and proxified diamond addresses all what the contracts can do, etc

**Comment by rndquu** [comment]
> > I don't get what "plug-in to the anvil node" means. Could you describe a particular case? Can't `ethers.js` or `web3.js` do the same job?
> 
> Yeah but we're essentially not rendering any views on this task, how you'd like to see the debugged? thru console?
> 
> to a well crafted architecture of this task we would need hardhat because of the JS playground, that way shall enable me to roll JS tests cases for the connection to the anvil & fully mimick transactions, and proxified diamond addresses all what the contracts can do, etc

Current setup:
- We have a foundry setup for the [contracts](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts)
- We import contracts ABIs from foundry build [here](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/utils/contracts.ts#L6)
- We have deployment addresses hardcoded [here](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/deployments.json)
- [Each contract](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/utils/contracts.ts#L68) is an `ethers.js` instance

What should be done:
1. Fix nextjs errors introduced with the update from `nextjs12` to `nextjs13`
2. Refactor dapp so that it could connect to a single diamond contract via `ethers.js` (as it was used before)
3. Make sure than the dapp works with the local anvil instance

At what point we need to transform the dapp package to a hardhat project and why? Perhaps we need to further break down this issue into smaller tasks?

**Comment by molecula451** [comment]
Upcoming updates, get ready for PR review and commenting

**Comment by molecula451** [comment]
Technically this PR #710   does it as per requirements(fetch one contract), there is room for subtasks here

`use-manager-managed.tsx` hook needs refactor (and a big one), (the refactor & testing might take time, plan accordingly) to really bring the contracts with that hook so that it does not return `undefined addresses`.

the scripted `deployments.json` can potentially be automated when the contracts are deployed and be fetched to the front end (needs lot of debugging and testing)

I'm concerned about the deployment that is live when each Pull Request it's opend and gets build, that frontend works with mainnet only, there's room for autoswitch detecting the network to anvil (if you'd like), (the networks that are gonna be use, and the local anvil (which is named hardhat in the MetaMask plugin Api))

**Comment by 0x4007** [comment]
> Technically this PR #710   does it as per requirements(fetch one contract), there is room for subtasks here
> 
> 
> 
> `use-manager-managed.tsx` hook needs refactor (and a big one), (the refactor & testing might take time, plan accordingly) to really bring the contracts with that hook so that it does not return `undefined addresses`.
> 
> 
> 
> the scripted `deployments.json` can potentially be automated when the contracts are deployed and be fetched to the front end (needs lot of debugging and testing)
> 
> 
> 
> I'm concerned about the deployment that is live when each Pull Request it's opend and gets build, that frontend works with mainnet only, there's room for autoswitch detecting the network to anvil (if you'd like), (the networks that are gonna be use, and the local anvil (which is named hardhat in the MetaMask plugin Api))
> 
> 
> 
> 

@rndquu if you agree that it's needed please turn these into bounties.
