### ISSUE TITLE
Minimal Proxy

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#699]
Seems that there's a lot of folks who do not like diamond. Instead, minimal proxies seem to be more favorable. 

We should measure the pros and cons of diamond vs minimal and see if there's any work that can be reused if we decide to convert. 

This is a research bounty and a report should be delivered. 

https://twitter.com/bantg/status/1671664719671746563?s=46&t=fLzoRySawhTzZHfr3g9x9A

**Comment by rndquu** [comment]
> Seems that there's a lot of folks who do not like diamond. Instead, minimal proxies seem to be more favorable.
> 
> We should measure the pros and cons of diamond vs minimal and see if there's any work that can be reused if we decide to convert.
> 
> This is a research bounty and a report should be delivered.
> 
> https://twitter.com/bantg/status/1671664719671746563?s=46&t=fLzoRySawhTzZHfr3g9x9A

Diamond storage and minimal proxies serve different purposes.

Diamond proxy makes your contract to be upgradable while [minimal proxy](https://eips.ethereum.org/EIPS/eip-1167) makes contract deployments cheaper. So minimal proxy is not about upgrading but about cheaper deployments of similar contracts.

**Comment by 0x4007** [comment]
You can mark as unplanned if you think this isn't applicable.

**Comment by malik672** [comment]
> > Seems that there's a lot of folks who do not like diamond. Instead, minimal proxies seem to be more favorable.
> > We should measure the pros and cons of diamond vs minimal and see if there's any work that can be reused if we decide to convert.
> > This is a research bounty and a report should be delivered.
> > https://twitter.com/bantg/status/1671664719671746563?s=46&t=fLzoRySawhTzZHfr3g9x9A
> 
> Diamond storage and minimal proxies serve different purposes.
> 
> Diamond proxy makes your contract to be upgradable while [minimal proxy](https://eips.ethereum.org/EIPS/eip-1167) makes contract deployments cheaper. So minimal proxy is not about upgrading but about cheaper deployments of similar contracts.

100%

**Comment by rndquu** [comment]
> You can mark as unplanned if you think this isn't applicable.

@malik672 closing this as "not planned" then

**Comment by malik672** [comment]
@pavlovcik are you trying to put upgradability in your contractrs
