### ISSUE TITLE
Refactor `LibCurveDollarIncentive.sol` `_getPercentDeviationFromUnderPeg(uint256 amount)`

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#707]
Unreachable code was removed. It should be re-added and it should pass coverage CI.

> The line was commented out because it was doing anything, and it's not doing anything as per original repo as this is **unreachable code** there
![code](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/ac4ec5f2-b889-4e08-9c7a-ef87a06da5d3)

> It's seem a simple solution the pavlovcik suggetion, but it gives the contributor (me) bad coverage, again a refactor might be need it

_Originally posted by @molecula451 in https://github.com/ubiquity/ubiquity-dollar/issues/704#issuecomment-1606284776_

**Comment by molecula451** [comment]
looks like purged after all https://github.com/ubiquity/ubiquity-dollar/commit/3966447d8b5d7eba7b5f43ec2473d23d8b84b650

**Comment by 0x4007** [comment]
TWAP update seems to be called every time this function runs so it is not necessary to update the TWAP inside the function it seems. @rndquu if you think this bounty isn't necessary you can close it as unplanned.

**Comment by molecula451** [comment]
I thought the same, twap it's called many times over the whole file
