### ISSUE TITLE
Watch for Foundry's commit hash releases

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#715]
relates #711

Foundry has a distinctive way of updating new releasing it looks like some commit hashes get lost when this happens.

We are relying on the commit hash for our actions CI, so we need to make sure everything's in harmony with the hash

**Comment by molecula451** [comment]
@rndquu keep this issue open until we spot the root cause of the hash changing on their builds

**Comment by rndquu** [comment]
@molecula451 Thank you for opening this one

So foundry workflow uses tags which are deleted quite often. Related [PR](https://github.com/ubiquity/ubiquity-dollar/pull/716). If we spot the issue again then we will switch to some older foundry tag.

Closing this for now

**Comment by molecula451** [comment]
re-opening, built just fails again, https://github.com/molecula451/ubiquity-dollar/actions/runs/5473720609/jobs/9967564275 , i knew, will dig into is, ignore the bot, this is not really for a bounty

**Comment by molecula451** [comment]
rndquu, they indeed deleted the hashes after releases

![hashes](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/6fff6685-7c6a-4fd7-bd4b-9c353fa0193c)

#721 should solve it with the monthly stable hash
