### ISSUE TITLE
Deploy Comment Styling

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#728]
This bounty refers to the GitHub comment the bot posts using [print-deployments-logs.js](https://github.com/ubiquity/.github/blob/main/utils/print-deployments-logs.js)

---

Right align is nice to appear close to the commit hashes.

```
<div align="right"> 
<p><a href="https://e1efb129.ubiquity-dollar-5vd.pages.dev"><code>96f4240</code></a></p>
</div>
```

Renders:

<div align="right"> 
<p><a href="https://e1efb129.ubiquity-dollar-5vd.pages.dev"><code>96f4240</code></a></p>
</div>

Refactor https://github.com/ubiquity/.github/blob/main/utils/print-deployments-logs.js accordingly
Provide a QA (i.e. PR example) where we can see that the alignment is applied (basically as you stated https://github.com/ubiquity/ubiquity-dollar/pull/767#issuecomment-1686588431)

Original Comment: https://github.com/ubiquity/ubiquity-dollar/pull/767#pullrequestreview-1587841465

**Comment by rndquu** [comment]
So commit hash URL should be aligned to the right like in the screenshot below?

<img width="1512" alt="Screenshot 2023-07-10 at 09 44 01" src="https://github.com/ubiquity/ubiquity-dollar/assets/119500907/3164b38a-2268-4aec-a577-41a9e8d67fd8">

**Comment by 0x4007** [comment]
Sorry for the unclear specification. I was referring to the comment the bot leaves on pull requests when a new deployment is made. 

https://github.com/ubiquity/ubiquity-dollar/pull/727#issuecomment-1627558339

**Comment by rndquu** [comment]
So deployment URL should aligned to the right line in the example below:
<img width="1512" alt="Screenshot 2023-07-10 at 10 03 21" src="https://github.com/ubiquity/ubiquity-dollar/assets/119500907/6f8a7cfc-2e15-497a-9afc-0dbc8af3761f">

**Comment by 0x4007** [comment]
Yes but my code doesn't include an unordered list! The idea is to keep the deploy hashes all in the same area - including the ones rendered by the GitHub UI.

**Comment by molecula451** [comment]
what happened @umershaikh123 ?

**Comment by umershaikh123** [comment]
@molecula451 my pc's motherboard had an issue last week , So waiting for it to get fix and return from warranty which takes about three to four weeks :(

**Comment by molecula451** [comment]
This issue description was updated to help deploy and achieve a reasonable implementation

**Comment by gitcoindev** [comment]
In this case implementation 10% effort, QA 90% effort. I had to test edge cases - not only adding but also merging and editing PR comments and checking commit comments, will clean up the changes and open a PR soon.

**Comment by molecula451** [comment]
QA same, on a PR to your repo (setup cloudflare beforehand etc...)

**Comment by gitcoindev** [comment]
@molecula451 yes, I set up Cloudflare and my org fork, will add links with a pull request.

**Comment by gitcoindev** [comment]
Opened PR: https://github.com/ubiquity/.github/pull/91
QA: https://github.com/korrrba/ubiquibot-logging/pull/1#issuecomment-1782886952

Example Cloudlfare deployments (I used ubiquibot-logging app on my org fork): https://fbf1b058.ubiquibot-logging-4wu.pages.dev/

Working GitHub action with logs: https://github.com/korrrba/ubiquibot-logging/actions/runs/6667701283/job/18121665399

**Comment by gitcoindev** [comment]
Raw edit comment body to show how it works under the hood:

```
<div align="right"><p><a href="https://fbf1b058.ubiquibot-logging-4wu.pages.dev"><code>49c8aec</code></a>
</p></div><div align="right"><p><a href="https://fc8dddb0.ubiquibot-logging-4wu.pages.dev"><code>4b163df</code></a>
</p></div><div align="right"><p><a href="https://9cca4060.ubiquibot-logging-4wu.pages.dev"><code>dcfc46b</code></a></p></div>
```

**Comment by gitcoindev** [comment]
PR ready for the review.

**Comment by molecula451** [comment]
looks a bit separate between lines. Can you style it like:
![separe](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/2719e6cc-f800-45d3-8b2f-3330e0701c6a)

**Comment by molecula451** [comment]
rndqnuu posted a good ref https://github.com/ubiquity/ubiquity-dollar/issues/728#issuecomment-1628362461 keep it same please

**Comment by molecula451** [comment]
it could potentially be done with js only otherwise try a node-markdown package perhaps

**Comment by gitcoindev** [comment]
> rndqnuu posted a good ref [#728 (comment)](https://github.com/ubiquity/ubiquity-dollar/issues/728#issuecomment-1628362461) keep it same please

Hi. @pavlovcik stated that his example does not use unordered list (see https://github.com/ubiquity/ubiquity-dollar/issues/728#issuecomment-1628379186), whereas @rndquu suggested to use the list. Which styling to use, one with or without the list ?

**Comment by gitcoindev** [comment]
I prepared a special demo with possible options to implement A, B or C

https://github.com/korrrba/ubiquibot-logging/pull/1#issuecomment-1782886952

Option A is currently implemented in the pull request that I opened, it matches spec by @pavlovcik . Option B is with`<p>` tags removed, which squeezes lines, advised by @molecula451 . Option C adds unordered list markers.

Please agree internally and I will implement according to your specification.

**Comment by pavlovcik** [comment]
B looks good

**Comment by molecula451** [comment]
nice i would have proposed this too, i am in favor with option B and C

**Comment by gitcoindev** [comment]
All right! I implemented option B and it looks good indeed.

QA with 5 deployments : https://github.com/korrrba/ubiquibot-logging/pull/2

**Comment by molecula451** [comment]
yes it does, open PR with B

**Comment by gitcoindev** [comment]
@molecula451 PR with option B open : https://github.com/ubiquity/.github/pull/91

**Comment by gitcoindev** [comment]
A message for the bot: pull request opened 5 days ago and has two approvals already, I am waiting for the merge.
