### ISSUE TITLE
Add UI diamond hook

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#731]
After implementing the diamond proxy in the [contracts package](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts) most of our contracts (i.e. [facets](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/facets)) have the same address (which basically equals to the deployed `Diamond` contract). The only exception (regarding the address) are the [core contracts](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/core) which should be deployed with the own upgrade mechanism because function names from the [core contracts](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/core) overlap with the ones in the [facets](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/facets) and Diamond proxy doesn't support function clashing.

So basically this code:
```typescript
const managerAddress = "0x4e037B9A8Ce977462DA4E10Fc164363C827abfc6";
const managerContract = await getUbiquityManagerContract(managerAddress, provider);
```
is the same as this one:
```typescript
const diamondAddress = '0xbe0efAbc83686a81903C1D4a2515f8111e53B5Cb';
const managerContract = await getUbiquityManagerContract(diamondAddress, provider);
```

There is the [react hook](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx) that returns all of the contract instances

We should take all of the [facets](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/facets) and make sure that this [hook](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx) returns all of the contract instances (i.e. facets) by a single diamond address

We can either refactor the [existing hook](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/lib/hooks/contracts/use-manager-managed.tsx) or create a new one

This "return contracts" hook will be referenced in the next github issues (regarding the `dapp` package) where we will make sure, one by one, that all of the pages work fine with the diamond proxy

**Comment by molecula451** [comment]
broken hook, unmaintainable, not really working with diamonds by defacto, a follow up from #710

**Comment by molecula451** [comment]
> Do you have any updates @molecula451? If you would like to release the bounty back to the DevPool, please comment `/unassign` Last activity time: Tue Jul 11 2023 11:23:13 GMT+0000 (Coordinated Universal Time)

#732

**Comment by molecula451** [comment]
the diamond itself bring us the deployed contract addresses

**Comment by rndquu** [comment]
Closing this as completed https://github.com/ubiquity/ubiquity-dollar/pull/771

**Comment by 0x4007** [comment]
> Closing this as completed https://github.com/ubiquity/ubiquity-dollar/pull/771

Perhaps we should close as not complete? There isn't a merged pull request associated with this issue.

**Comment by rndquu** [comment]
> There isn't a merged pull request associated with this issue

Now there is one
