### ISSUE TITLE
Rename `CreditNFT` to `CreditNft`

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#736]
There are some [places](https://github.com/ubiquity/ubiquity-dollar/blob/896b25113b36bc1e18e3dd5bf03be88c9c7bb7e3/packages/contracts/src/dollar/upgradeInitializers/DiamondInit.sol#L38) in the code where `CreditNFT` naming is used. We have a convention to use it as `CreditNft` instead of `CreditNFT`.

There are also some places in the [code](https://github.com/ubiquity/ubiquity-dollar/blob/2642a8c42041f9577a5041ed74d8d83c7097e852/packages/contracts/src/dollar/core/CreditClock.sol#L16) where `accessCtrl` contraction is used. This contraction is unnecessary.

What should be done:
1. Rename all `CreditNFT` instances in the code to `CreditNft`
2. Check that `cspell` command in the pre-commit hook catches all `CreditNFT` namings and throws an error in this case
3. Rename all `accessCtrl` instance in the code to `accessControl`

**Comment by 0x4007** [comment]
Perhaps these renames can all be consolidated into a single bounty? 

Example: 
- https://github.com/ubiquity/ubiquity-dollar/issues/737

**Comment by baibhavKumar1** [comment]
@rndquu Is it still open to work? Done with 1st and 3rd step, how to go for 2nd step?

**Comment by rndquu** [comment]
> @rndquu Is it still open to work? Done with 1st and 3rd step, how to go for 2nd step?

We use [cspell](https://www.npmjs.com/package/cspell) in the pre-commit hook so you should find a cspell setting which throws an error every time cspell sees `creditNFT` or `CreditNFT` in the code

**Comment by baibhavKumar1** [comment]
> > @rndquu Is it still open to work? Done with 1st and 3rd step, how to go for 2nd step?
> 
> We use [cspell](https://www.npmjs.com/package/cspell) in the pre-commit hook so you should find a cspell setting which throws an error every time cspell sees `creditNFT` or `CreditNFT` in the code

Hey @rndquu , as you mentioned creditNFT should throw error , and changes to be made were just for CreditNFT to renamed to CreditNft, should creditNFT also be renamed to creditNft?

**Comment by rndquu** [comment]
> > > @rndquu Is it still open to work? Done with 1st and 3rd step, how to go for 2nd step?
> > 
> > 
> > We use [cspell](https://www.npmjs.com/package/cspell) in the pre-commit hook so you should find a cspell setting which throws an error every time cspell sees `creditNFT` or `CreditNFT` in the code
> 
> Hey @rndquu , as you mentioned creditNFT should throw error , and changes to be made were just for CreditNFT to renamed to CreditNft, should creditNFT also be renamed to creditNft?

yes, `creditNFT` should be `creditNft`

Could you refactor? Sorry for the inaccurate spec

**Comment by baibhavKumar1** [comment]
/wallet 0xD76e43a789489D66Bb5CE56304fC8bb2A084F9F5  0x948d507c209ca559e3e673e273544416e56b8247b30ab7ce58f705e02899a5f97d1142d2f9d6a57e5d71b20a8033a4f47df3d85f17285c3671bedffcae1adc141b

**Comment by baibhavKumar1** [comment]
Sorry for the delay, I will raise a PR by today end.
