### ISSUE TITLE
Rename `accessCtrl` to `accessControl` 

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#737]
There are some places in the [code](https://github.com/ubiquity/ubiquity-dollar/blob/2642a8c42041f9577a5041ed74d8d83c7097e852/packages/contracts/src/dollar/core/CreditClock.sol#L16) where `accessCtrl` contraction is used. This contraction is unnecessary.

What should be done:
- rename all `accessCtrl` instance in the code to `accessControl`

**Comment by 0x4007** [comment]
Can we remove contractions on all of the variables? Shouldn't `cspell` pick these contractions up?

**Comment by rndquu** [comment]
> Can we remove contractions on all of the variables? 

I skimmed through the contracts again and haven't found out anything eye catching besides `accessCtrl` so let's keep it simple

> Shouldn't `cspell` pick these contractions up?

I'm not sure that `cspell` can distinguish a contracted word with a full one

**Comment by rndquu** [comment]
Consolidating this issue with https://github.com/ubiquity/ubiquity-dollar/issues/736
