### ISSUE TITLE
Autogenerate natspec docs

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#739]
There are [natspec docs](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/docs/src/SUMMARY.md) generated locally by this [command](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/package.json#L38). We should automate this flow via CI.

What should be done:
- Create a CI workflow (or add an additional step to the `Build and Test` workflow) which on every push to the `development` branch will regenerate natspec docs

**Comment by tungbq** [comment]
Hello team, I'm new with this DevPool. How can I create the new Wallet/WalletID?

**Comment by tungbq** [comment]
/wallet 0xaa13387810931252811186Ff05a467194E41341C 0x2b964b4f8d6e31700cf899aedf86eb9cb0e680c8ede707aa9969938380fafb36337e195f15c23a5d77e579984404e6c565c063603ceb70c6b1c1a1d713889e241b

**Comment by tungbq** [comment]
/wallet 0xaa13387810931252811186ff05a467194e41341c 0x2b964b4f8d6e31700cf899aedf86eb9cb0e680c8ede707aa9969938380fafb36337e195f15c23a5d77e579984404e6c565c063603ceb70c6b1c1a1d713889e241b

**Comment by tungbq** [comment]
/wallet 0xaa13387810931252811186Ff05a467194E41341C 0x2b964b4f8d6e31700cf899aedf86eb9cb0e680c8ede707aa9969938380fafb36337e195f15c23a5d77e579984404e6c565c063603ceb70c6b1c1a1d713889e241b

**Comment by tungbq** [comment]
I did provide the **SIGNATURE_HASH** but not sure why @ubiquity bot keeps asking to do so.

**Comment by tungbq** [comment]
/wallet 0xaa13387810931252811186Ff05a467194E41341C 0x288bd4dc82dc188119206e7e4661b96028da91e42527acbad207fb9277411f7379b7c1edb58a0b3e86a379db2cad49c3a8e29926543f05f66a76876660b2451c1b

**Comment by rndquu** [comment]
/wallet 0x16ce4d863eD687455137576da2A0cbaf4f1E8f76 0x0830f316c982a7fd4ff050c8fdc1212a8fd92f6bb42b2337b839f2b4e156f05a359ef8f4acd0b57cdedec7874a865ee07076ab2c81dc9f9de28ced55228587f81c

**Comment by rndquu** [comment]
/wallet 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 0xa4e87319ae9cd367bff300f92305f9e36c1a42ce260abd9f6f7c27d7c3a252506ce5f43f64590302155f0e5c5b0ed0f157be6d6189720b2123a834b46762b7fa1c

**Comment by rndquu** [comment]
/wallet 0x336C033842FA316d470e820c81b742e62A0765DC 0x6278f129535199f0b529f1da7f4465d8c41fc5343ed3a3f8cbcd0f15b91f714c67f537cbd4ace86ab9e2ef26da4921b04da9b2ebba2d42dacac290f575d711cf1c

**Comment by rndquu** [comment]
@tungbq wallet registration seems to be working, pls try again

**Comment by tungbq** [comment]
/wallet 0xaa13387810931252811186Ff05a467194E41341C 0x288bd4dc82dc188119206e7e4661b96028da91e42527acbad207fb9277411f7379b7c1edb58a0b3e86a379db2cad49c3a8e29926543f05f66a76876660b2451c1b

**Comment by tungbq** [comment]
/wallet 0xaa13387810931252811186Ff05a467194E41341C 0xee969283ecb26e31e64b6ad2bced84ea5c7cd79fbf38406989197c12302102a63e50d3a9042616e7e9ef8874d33e54d03ae8762379e4701e00d2b55a048cd3a01c

**Comment by tungbq** [comment]
Yes, it's working fine now. Thanks @rndquu!

**Comment by rndquu** [comment]
> Yes, it's working fine now. Thanks @rndquu!

What was wrong?

**Comment by tungbq** [comment]
> > Yes, it's working fine now. Thanks @rndquu!
> 
> What was wrong?

I don't know the exact reason. I just did a sign again: https://etherscan.io/verifiedSignatures. Then retry

**Comment by 0x4007** [comment]
> > > Yes, it's working fine now. Thanks @rndquu!
> 
> > 
> 
> > What was wrong?
> 
> 
> 
> I don't know the exact reason. I just did a sign again: https://etherscan.io/verifiedSignatures. Then retry

It looks like your hashes are different so you must have hashed the wrong string before. 

I'm concerned that this flow will be too hostile to new users. Let's continue observing wallet registration attempts.
