### ISSUE TITLE
Broken script, not matching folders (open to discussion)

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#756]
`diamond-in-all.ts`

https://github.com/ubiquity/ubiquity-dollar/blob/36fbda357a4fd18f95a0d386c9e37b20ce52f356/packages/contracts/scripts/deploy/manager/diamond-in-all.ts#L124

```
  const diamondCutFacetContract = "src/diamond/facets/DiamondCutFacet.sol:DiamondCutFacet";
  const diamondContract = "src/diamond/Diamond.sol:Diamond";
  const diamondInitContract = "src/diamond/upgradeInitializers/DiamondInit.sol:DiamondInit";
  const diamondLoupeFacetContract = "src/diamond/facets/DiamondLoupeFacet.sol:DiamondLoupeFacet";
  const ownershipFacetContract = "src/diamond/facets/OwnershipFacet.sol:OwnershipFacet";
  const managerFacetContract = "src/diamond/facets/ManagerFacet.sol:ManagerFacet";
  const twapOracleDollar3poolFacetContract = "src/diamond/facets/TWAPOracleDollar3poolFacet.sol:TWAPOracleDollar3poolFacet";
```

`/src/diamond` it's not our folder, our folder it's `/src/dollar/`

and the whole script might be broken as well in how it interact with newer updates, etc

this part of the script it's broken, open here for the for the discussion in what we want to do with this script

**Comment by 0x4007** [comment]
@wannacfuture do you know how to let molecula451 set labels like solidity

**Comment by rndquu** [comment]
I think this script was an initial attempt to create a deploy for the diamond related contracts.

But later we created a new [one](https://github.com/ubiquity/ubiquity-dollar/blob/eea6c7f73acac4e0961cf6b8d439884e33986e35/packages/contracts/package.json#L31) that works (almost) fine.

So right now we have 2 deployment scripts:
1. [TS script](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/scripts/deploy/dollar/development-deploy.ts) which calls solidity script which deploys all of the facets (which works fine)
2. [Obsolete TS script](https://github.com/ubiquity/ubiquity-dollar/blob/36fbda357a4fd18f95a0d386c9e37b20ce52f356/packages/contracts/scripts/deploy/manager/diamond-in-all.ts) with TS errors which deploys only a small part of available facets

I would simple delete this [one](https://github.com/ubiquity/ubiquity-dollar/blob/36fbda357a4fd18f95a0d386c9e37b20ce52f356/packages/contracts/scripts/deploy/manager/diamond-in-all.ts) and the related code

**Comment by molecula451** [comment]
Yeah lets deprecate this script PRing

**Comment by molecula451** [comment]
@wannacfuture what's up?

**Comment by wannacfuture** [comment]
> @wannacfuture do you know how to let molecula451 set labels like solidity

hmm... not so sure but is it related to the permission?

**Comment by molecula451** [comment]
> > @wannacfuture do you know how to let molecula451 set labels like solidity
> 
> hmm... not so sure but is it related to the permission?

to the access control command probably
