### ISSUE TITLE
Move `DirectGovernanceFarmer` to diamond facets

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#773]
We've migrated most of our contracts to the diamond proxy implementation. But not all of them.

What should be done:
- refactor [DirectGovernanceFarmer](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/DirectGovernanceFarmer.sol) to be part of the diamond [facets](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/facets) 
- add `DirectGovernanceFarmer` to the [deployment script](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/scripts/deploy/dollar/solidityScripting)
- refactor `DirectGovernanceFarmer` [tests](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/test/dollar/DirectGovernanceFarmer.t.sol) accordingly

**Comment by rndquu** [comment]
@molecula451 try with the `/start` command

**Comment by molecula451** [comment]
![Screenshot from 2023-10-27 00-41-26](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/d7541498-7905-44dd-8915-9495ccef73db)

👀

**Comment by molecula451** [comment]
i'm finishing things here, this is one of our biggest contracts by far

**Comment by molecula451** [comment]
timelabel less than 4 hours 🤣

**Comment by rndquu** [comment]
> timelabel less than 4 hours 🤣

For somebody with the knowledge of the ubiquity contracts architecture and diamond proxy pattern this copy-paste issue should take from 2 to 8 hours

**Comment by molecula451** [comment]
not not really, maybe the diamond cuts section, but not the debugging, anyway just for fun 😄

**Comment by molecula451** [comment]
> timelabel less than 4 hours 🤣

not not really, maybe the diamond cuts section, but not the debugging, anyway just for fun 😄

**Comment by 0x4007** [comment]
Perhaps https://cursor.sh can help you save time. 

This with gpt4 + copilot is really powerful.

**Comment by TouchstoneTheDev** [comment]
> Perhaps https://cursor.sh can help you save time.
> 
> This with openai's gpt4 + cursor's copilot is really powerful.*

not github copilot rt ? huh dat really got some isssues

**Comment by molecula451** [comment]
in your copilot dreams you are still the driver  🤣 

> This with gpt4 + copilot is really powerful.

+1 for this setup!

**Comment by molecula451** [comment]
> Perhaps https://cursor.sh can help you save time.
> 
> This with gpt4 + copilot is really powerful.

I understand the value of having this setup, very powerful indeed, and you add some hacks and voila!! you a got a super IDE.. but the slow debugging process mostly came from this magical tool

Look when it shows  "Compiling..."

@pavlovcik 


https://github.com/ubiquity/ubiquity-dollar/assets/41552663/b4958107-3ca8-4aa8-83c4-16024d0a8dd3

yep, in recompiling times, theres a lot, phew

**P.S: this is just for fun and off-topic**

**Comment by gitcoindev** [comment]
>  yarn.mp4 
> yep, in recompiling times, theres a lot, phew
> 
> **P.S: this is just for fun and off-topic**

Build executed as root user, Chuck Norris style -)

![chuck](https://github.com/ubiquity/ubiquity-dollar/assets/88761781/9fd00541-641a-4d58-9672-cb939995d075)
