### ISSUE TITLE
Add UUPS for core contracts

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#774]
Original [discussion](https://github.com/ubiquity/ubiquity-dollar/discussions/730)

Right now we use the diamond proxy pattern for most of our contracts (implemented as diamond [facets](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/facets)).

We also have the [core](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/core) contracts that can't be used with the diamond proxy because of function clashing. Hence the different upgradability pattern should be used.

What should be done:
1. Apply UUPS to the core contracts:
- https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/CreditNft.sol
- https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/ERC1155Ubiquity.sol
- https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/ERC20Ubiquity.sol
- https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/StakingShare.sol
- https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/UbiquityCreditToken.sol
- https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/UbiquityDollarToken.sol
- https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/UbiquityGovernanceToken.sol
2. Update [deployment script](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/scripts/deploy/dollar/solidityScripting) accordingly
3. Refactor [tests](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/test/dollar/core) for core contracts accordingly

P.S. Although [CreditClock](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/CreditClock.sol) exists in the "core" folder it is not a "core" contract. We have [plans](https://github.com/ubiquity/ubiquity-dollar/issues/772) for moving it to diamond facets.

**Comment by Keyrxng** [comment]
chill my friend

**Comment by rndquu** [comment]
@Keyrxng I don't know why the bot refuses to assign you to the issue, pls try with the `/start` command

**Comment by Steveantor** [comment]
> Do you have any updates @Keyrxng? If you would like to release the bounty back to the DevPool, please comment `/stop` Last activity time: Fri Aug 25 2023 23:15:34 GMT+0000 (Coordinated Universal Time)

There's a linked PR, why the bot isn't picking up?

**Comment by rndquu** [comment]
> > Do you have any updates @Keyrxng? If you would like to release the bounty back to the DevPool, please comment `/stop` Last activity time: Fri Aug 25 2023 23:15:34 GMT+0000 (Coordinated Universal Time)
> 
> There's a linked PR, why the bot isn't picking up?

Hard to say, https://github.com/ubiquity/ubiquibot/issues/729

**Comment by molecula451** [comment]
the bot is a rebel

**Comment by molecula451** [comment]
it looks like keyring it's gonna have this one, albeit it still need more work, let's see

**Comment by Keyrxng** [comment]
New review requested

**Comment by 0x4007** [comment]
@molecula451 did not receive comment incentives here. Does anybody know why? Hard to tell from my phone perhaps the config is disabled?

@0xcodercrane can you check the logs in Supabase?

@ubiquity/software-development  RFC

**Comment by 0x4007** [comment]
https://gnosisscan.io/tx/0xf7a1413dd82a60715a1f8bcb38b9e7e920e68d9ab5f27a093fd16b4a6a82398e

@molecula451
