### ISSUE TITLE
Add workflow to check that core contracts storage is not corrupted

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#775]
Depends on https://github.com/ubiquity/ubiquity-dollar/issues/774

Original [idea](https://github.com/ubiquity/ubiquity-dollar/issues/636#issuecomment-1687588218)

When we add UUPS support to the [core](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/core) contracts we should check that storage is not corrupted on each PR. There is a handy [action](https://github.com/Rubilmax/foundry-storage-check) for it.

What should be done
- Add a new workflow that uses the [rubilmax/foundry-storage-check](https://github.com/Rubilmax/foundry-storage-check) action on each PR and push to the `development` branch when `*.sol` files have been updated

**Comment by gitcoindev** [comment]
Adding a comment for the bot: waiting for PR approval and merge.

**Comment by gitcoindev** [comment]
Hi @rndquu thank you for self-assigning the review. I hope we can have both PRs review and merged soon as I would like to pick up a new task and I am currently blocked.

**Comment by molecula451** [comment]
the bot didn't generate rewards for assignee here either @pavlovcik

**Comment by 0x4007** [comment]
I assume that it is most likely to time out when it calculates the assignee rewards for some reason

**Comment by gitcoindev** [comment]
Hi @pavlovcik @rndquu @molecula451  thank you for approving and merging! I see this ticket was not the only one affected, likely a regression from one of the recent bot pull requests. Is there any chance to manually trigger the bot to regenerate the assignee reward ?

**Comment by 0x4007** [comment]
@0xcodercrane either you can push a hot fix or I'll need to manually send payment. 

I only ask cause you messaged me today saying you're working on the hot fix.

**Comment by gitcoindev** [comment]
Hi @pavlovcik is the hotfix available?

**Comment by 0x4007** [comment]
@rndquu is working on it. We just need to open and close the issues again to generate the outstanding payments.

**Comment by molecula451** [comment]
most likely the bot already `savePermit()` the permit to DB, this happened at https://github.com/ubiquity/ubiquibot/pull/797

**Comment by gitcoindev** [comment]
I hope the bot did not save the penalty as well :laughing: , it seems to go pretty rogue recently.

**Comment by molecula451** [comment]
no, it does not, but it shows the penalty because it most likely already saved the permit

**Comment by gitcoindev** [comment]
Ok, so when it saved the permit before it assumed all done and did not re-generate the assignee reward, just the conversation rewards, interesting...

**Comment by molecula451** [comment]
No. It did not regenerate because it's already saved to the DB so thats why it Pops the penalty if it's reopen because the bot it's fetching the permit data what it did not was comment that permit here

**Comment by molecula451** [comment]
Also The bot is referencing a penalty amount based on the creator tasks award of first mention about the rewards not based on the task label i see this is happening in all others too You may see the task is 50 but the bot is saying a penalty of 40.5 referencing to creator awards in this case but not limited to

**Comment by 0x4007** [comment]
https://gnosisscan.io/tx/0x3bb0987c3fbe936a8204a90d1b9051bee9264cec9a32a042dec08421fa861a42

**Comment by gitcoindev** [comment]
@pavlovcik thank you
