### ISSUE TITLE
Reloading Error in README.md

### ISSUE THREAD

**Issue by 0xScratch** [pavlovcik/uad-ui#776]
These two pics aren't reloading properly
![Screenshot (19)](https://github.com/ubiquity/ubiquity-dollar/assets/88618913/5ab2256a-3115-4621-859d-4ba905966dab)

**Comment by molecula451** [comment]
Check your internet connection, browser, try incognito, and re-check, this is rendering fine & not reproducible

![read](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/8a084730-dc13-495e-8ac0-f869d9adcc78)

**Comment by 0xScratch** [comment]
Probably yes
