### ISSUE TITLE
Update to same Solidity Version in all facets

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#780]
Some facets are using floating pragma and 1 or 2 are using lower Solidity versions. Let's keep it conventional and use same solidity version in all facets and avoid floating pragma

**Comment by molecula451** [comment]
@rndquu im trying to regenerate

**Task Creator Reward** that never worked, mind setting a label to see if the bot follow up re-generating it. We could disable the an assigned permit if gets rounded again

**Comment by molecula451** [comment]
maybe removing the permit from DB?

**Comment by rndquu** [comment]
> maybe removing the permit from DB?

It doesn't check the DB on permit regenaration

This seems to be a bug. Could you file a new issue similar to "Issue creator rewards are not regenerated" with a link to the current issue?

**Comment by molecula451** [comment]
> It doesn't check the DB on permit regenaration

https://github.com/ubiquity/ubiquibot/issues/823
