### ISSUE TITLE
UI: apply diamond architecture

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#783]
We migrated to the diamond proxy pattern some time ago and right now the UI is broken. 

All protocol contracts are divided in 2 parts:
1. [Core](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/core) contracts (deployed as standalone contracts)
2. [Contracts](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/contracts/src/dollar/facets) that are part of the diamond (deployed as diamond proxy facets)

We should fix the UI to be working on a local anvil instance. Then we will setup [development environments](https://github.com/ubiquity/ubiquity-dollar/issues/683) for different networks (local anvil, testnet sepolia, production mainnet)

Use this [file](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/lib/hooks/contracts/use-protocol-contracts.ts) to get a list of all available contracts (feel free to add new ones).

Subtasks:
- [x] #784
- [x] #785
- [x] #786
- [x] #807

**Comment by gitcoindev** [comment]
Ok, so the task is split into three subtasks which makes sense. The first one will likely take 70% of time due to initial setup. I will spend 1-2 days experimenting on the setup and see if I could pick it up.

**Comment by molecula451** [comment]
if you're going to work on it. You will encounter components that needs refactors and that are useless in its current stage, that's why the task has splitted

**Comment by gitcoindev** [comment]
Ok, thanks. I see #784 reactivated after a long time. I would not like to open already opened door. Perhaps I will leave the bounty hunter until end of the weekend to see if he manages to complete the first task and will start working on this or an another one from Monday onward.
