### ISSUE TITLE
UI: apply diamond to home and markets pages

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#784]
Original [issue](https://github.com/ubiquity/ubiquity-dollar/issues/783)

What should be done:
- take this [file](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/lib/hooks/contracts/use-protocol-contracts.ts) and refactor [home](https://uad.ubq.fi/) and [markets](https://uad.ubq.fi/markets) pages to use contracts from the new diamond architecture

**Comment by bojan07** [comment]
Hey guys, I have checked the issue description and project repo shortly and I'm interested in solving this issue, but the 4 hours seems too short to me
Anyways, the issue description is enough for me to start to work on?

**Comment by rndquu** [comment]
Hey @bojan07 

> but the 4 hours seems too short to me

Increased to 1 day to be on par with other UI related issues (https://github.com/ubiquity/ubiquity-dollar/issues/786, https://github.com/ubiquity/ubiquity-dollar/issues/785)

> Anyways, the issue description is enough for me to start to work on?

Yes, type the `/start` command and you're free to solve the issue

**Comment by bojan07** [comment]
no blockers for this issue now? @rndquu

**Comment by 0x4007** [comment]
@rndquu as we near the end of the year, I would like for you to start ramping up the priority levels on the ubiquity dollar tasks. I would like the new deployment to be complete with a stable UI by end of year. 

This will give us a few months of testing and integrations (like with UbiquiBot and UbiquiCard) before beginning fundraising in March 2024.

**Comment by bojan07** [comment]
Hi @rndquu Is this [deployed contracts](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/deployments.json) newly deployed ones? or old ones?
Current frontend is using the deployed addresses in that file

**Comment by bojan07** [comment]
Hmm, seems I found it. the contract addresses in that file are old ones.. but there is no newly deployed addresses including facets addresses?

**Comment by rndquu** [comment]
@bojan07 

> no blockers for this issue now?

There are no blockers

> Hi @rndquu Is this [deployed contracts](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/deployments.json) newly deployed ones? or old ones?
Current frontend is using the deployed addresses in that file

Refactor to make it work in a local anvil instance

> Hmm, seems I found it. the contract addresses in that file are old ones.. but there is no newly deployed addresses including facets addresses?

Diamond and facets are not deployed yet

**Comment by rndquu** [comment]
> @rndquu as we near the end of the year, I would like for you to start ramping up the priority levels on the ubiquity dollar tasks. I would like the new deployment to be complete with a stable UI by end of year.
> 
> This will give us a few months of testing and integrations (like with UbiquiBot and UbiquiCard) before beginning fundraising in March 2024.

Ok, I will make it my top priority. The bot's repo really distracts all the time from the Dollar project.

**Comment by bojan07** [comment]
Sadly, I don't have enough time to solve this bounty right now

**Comment by gitcoindev** [comment]
Hi @bojan07  I see that you opened a PR and closed it. Could you please provide a QA ticket in your fork with the proof / testing that the changes work correctly and home and markets pages use diamond facets?

**Comment by bojan07** [comment]
@rndquu I just noticed that other dev is trying to solve an issue(issue#784) related to this issue.. I think all 3 issues related to this issue should be solved by one dev.. please sort this out

**Comment by bojan07** [comment]
> Hi @bojan07 I see that you opened a PR and closed it. Could you please provide a QA ticket in your fork with the proof / testing that the changes work correctly and home and markets pages use diamond facets?

@gitcoindev I'm on progress. I needed a deep research on the project and special functionalities such as diamond implementation.. and jumped on the active development. Hope you to select another bounties available

**Comment by gitcoindev** [comment]
@bojan07 all right . I did start only because the issue was idle for a long time and suddenly reactivated when I asked about it.

@rndquu @pavlovcik I will stop working on this and give @bojan07 a green light here.

I will need to find something else to pick up then..

**Comment by bojan07** [comment]
@rndquu [this pr](https://github.com/ubiquity/ubiquity-dollar/pull/800) is ready for a review. Now I'm working on staking page and requires much work compared to home and market pages

**Comment by bojan07** [comment]
Oh.. why ubiquibot is closing the pr?

**Comment by rndquu** [comment]
> Oh.. why ubiquibot is closing the pr?

@0xcodercrane

**Comment by cuddle-dev** [comment]
I can see the [main PR](https://github.com/ubiquity/ubiquity-dollar/pull/797) was closed before the [new PR](https://github.com/ubiquity/ubiquity-dollar/pull/800) was attached.

**Comment by molecula451** [comment]
the bot acting fast... lately

**Comment by molecula451** [comment]
> Refactor to make it work in a local anvil instance

Provide visual context

**Comment by molecula451** [comment]
It locally fetch diamond deployed addresses

QA:
![debug](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/0a26281d-39ce-4265-9137-2ffdf26532ee)

**Comment by bojan07** [comment]
Thanks for rewards, but should I claim the rewards manually? Sadly, registered address is not metamask address, one CEX address. I can't claim

**Comment by bojan07** [comment]
> Thanks for rewards, but should I claim the rewards manually? Sadly, registered address is not metamask address, one CEX address. I can't claim

Could the team cancel it and send rewards directly?

**Comment by bojan07** [comment]
I didn't notice that I should register metamask address as a payment wallet address because I'm new to ubiquity project 😢

**Comment by 0x4007** [comment]
Invalidated assignee reward

https://gnosisscan.io/tx/0x1a6d115c5b92ff132d2881e5713c14e63838726d5651605e04d23b1557e0afad

**Comment by bojan07** [comment]
> Invalidated assignee reward
> 
> https://gnosisscan.io/tx/0x1a6d115c5b92ff132d2881e5713c14e63838726d5651605e04d23b1557e0afad

What's this transaction? @pavlovcik  I haven't received it

**Comment by bojan07** [comment]
Please send to this address(ERC-20)
0x301242a369b997e63b24158a90ce23409ba5c6cf

**Comment by molecula451** [comment]
> /wallet 0x301242a369b997e63b24158a90ce23409ba5c6cf

you set a wallet 5 days ago, what do you mean?

**Comment by bojan07** [comment]
> > /wallet 0x301242a369b997e63b24158a90ce23409ba5c6cf
> 
> you set a wallet 5 days ago, what do you mean?

Yeah, but it's not metamask address. I don't have to claim on my side? And the rewards will be sent to my wallet automatically? I thought that I should claim the rewards by using metamask by signing

**Comment by bojan07** [comment]
Seems I'm a bit confused with reward system here.. If I don't have to claim it by using my metamask address, please send the rewards to the registered address. Thanks

**Comment by molecula451** [comment]
if you did not claim the generated permit, you should wait now

**Comment by bojan07** [comment]
> if you did not claim the generated permit, you should wait now

Yeah, got it.

**Comment by bojan07** [comment]
> if you did not claim the generated permit, you should wait now

When the reward payment is settled? @molecula451

**Comment by bojan07** [comment]
> > if you did not claim the generated permit, you should wait now
> 
> When the reward payment is settled? @molecula451

Who is managing this in the team? @pavlovcik @molecula451 @rndquu

**Comment by rndquu** [comment]
@bojan07 0x301242a369b997e63b24158a90ce23409ba5c6cf is the CEX address, right? If so then pls update your wallet address to the one with a known private key (for example from metamask).

Generally you should claim rewards but the bot is on some kind of a maintenance mode so we temporary have to transfer rewards manually.

**Comment by bojan07** [comment]
> @bojan07 0x301242a369b997e63b24158a90ce23409ba5c6cf is the CEX address, right? If so then pls update your wallet address to the one with a known private key (for example from metamask).
> 
> Generally you should claim rewards but the bot is on some kind of a maintenance mode so we temporary have to transfer rewards manually.

Yeah, got it. thanks

**Comment by bojan07** [comment]
So shall I update the wallet address on next bounty? @rndquu if transfer rewards manually, hope you to send to the already registered address

**Comment by rndquu** [comment]
> So shall I update the wallet address on next bounty?

Update the wallet now, I will try to regenerate the reward URL (which can be claimed only from address with a known private key)

**Comment by bojan07** [comment]
But when I claim, I should have native token like eth in my wallet, shouldn't I?

**Comment by rndquu** [comment]
> But when I claim, I should have native token like eth in my wallet, shouldn't I?

Yes, in particular XDAI because rewards are in ERC20 WXDAI for gnosis chain

There is a [facet](https://www.gnosisfaucet.com/) (not sure if it works though, never tried it) for XDAI which should be enough for you to claim

**Comment by bojan07** [comment]
> > But when I claim, I should have native token like eth in my wallet, shouldn't I?
> 
> Yes, in particular XDAI because rewards are in ERC20 WXDAI for gnosis chain
> 
> There is a [facet](https://www.gnosisfaucet.com/) (not sure if it works though, never tried it) for XDAI which should be enough for you to claim

Yeah, thanks. Let me check the link

**Comment by bojan07** [comment]
> There is a [facet](https://www.gnosisfaucet.com/) (not sure if it works though, never tried it) for XDAI which should be enough for you to claim

Seems this is just faucet(test token)..

**Comment by bojan07** [comment]
> > There is a [facet](https://www.gnosisfaucet.com/) (not sure if it works though, never tried it) for XDAI which should be enough for you to claim
> 
> Seems this is just faucet(test token)..

No,, real token.. thanks

**Comment by rndquu** [comment]
@bojan07 Generally issue assignees are not eligible for conversation rewards, but since the reward URL is missing you could claim [conversation rewards](https://github.com/ubiquity/ubiquity-dollar/issues/784#issuecomment-1746641541) + we owe you 91.8 WXDAI (@pavlovcik )

Sorry for the mess with the rewards, there was a huge bot's update which we had to revert and now everything is falling apart

**Comment by bojan07** [comment]
> @bojan07 Generally issue assignees are not eligible for conversation rewards, but since the reward URL is missing you could claim [conversation rewards](https://github.com/ubiquity/ubiquity-dollar/issues/784#issuecomment-1746641541) + we owe you 91.8 WXDAI (@pavlovcik )
> 
> Sorry for the mess with the rewards, there was a huge bot's update which we had to revert and now everything is falling apart

Got it, don't be sorry, thanks

**Comment by bojan07** [comment]
@pavlovcik please send the remainder to this ERC-20 address. 0x301242a369b997e63b24158a90ce23409ba5c6cf
I have lost 105 because I didn't confirm the gnosis network.. 😢

**Comment by 0x4007** [comment]
It will be sent to `0xc6fa133f3290e14Ad91C7449f8D8101A6f894E25` because you successfully claimed there

**Comment by 0x4007** [comment]
https://gnosisscan.io/tx/0x0f99a654ced7b700daab05ac649255c0a69402a8f900f5d9a1e68047a40cc575
