### ISSUE TITLE
UI: apply diamond to staking page

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#785]
Original [issue](https://github.com/ubiquity/ubiquity-dollar/issues/783)

What should be done:
- take this [file](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/lib/hooks/contracts/use-protocol-contracts.ts) and refactor the [staking](https://uad.ubq.fi/staking) page to use contracts from the new diamond architecture

**Comment by bojan07** [comment]
I have one question
 **DebtCouponManager** has changed into **creditNftManager**, right? @rndquu 
 And these names in the current ui codebase should be changed into **creditNftManager**  too?

**Comment by rndquu** [comment]
> DebtCouponManager has changed into creditNftManager, right?

`DebtCouponManager` was renamed to [CreditNftManagerFacet](https://github.com/ubiquity/ubiquity-dollar/blob/dfe0e3f5da6200eb3058a22c3ef9d8d286ceb456/packages/contracts/src/dollar/facets/CreditNftManagerFacet.sol)

> And these names in the current ui codebase should be changed into creditNftManager too?

Yes, I think `creditNftManagerFacet` is even more appropriate than `creditNftManager`

**Comment by bojan07** [comment]
@rndquu `dollar3poolMarket` and `_3crvToken` can also be added to protocol contract?
![image](https://github.com/ubiquity/ubiquity-dollar/assets/121951004/284ae723-753e-4554-bcba-d6ecea182df5)

**Comment by rndquu** [comment]
> @rndquu `dollar3poolMarket` and `_3crvToken` can also be added to protocol contract? 

Yes, can't think of a better place for them right now

**Comment by bojan07** [comment]
@rndquu @molecula451 [this pr](https://github.com/ubiquity/ubiquity-dollar/pull/804) is ready for a review

**Comment by bojan07** [comment]
I'm ready to push commits for credit page issue.. hope the review can be done asap, so that I can avoid any conflicts 💪

**Comment by bojan07** [comment]
When can the review be done? I hope the review of at least one of these two([pr804](https://github.com/ubiquity/ubiquity-dollar/pull/804), [pr809](https://github.com/ubiquity/ubiquity-dollar/pull/809)) can be done today, so that I can move on next issue. Due to limitation of assigning, I can't move on
