### ISSUE TITLE
Fix deprecation notice by github on Action Warning

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#793]
```Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/```

CI run with the warning: https://github.com/ubiquity/ubiquity-dollar/actions/runs/6294477481

**Comment by molecula451** [comment]
@gitcoindev you might want to figure out a fix to this one

**Comment by gitcoindev** [comment]
@molecula451 , I had a look. Currently the GitHub action uses `set-output` command and it will be replaced in the future by shared ` $GITHUB_OUTPUT` variable. More details are here.

 https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I can add this to my queue, of course if anyone feels to pick this up before me, feel free to do so.

**Comment by molecula451** [comment]
/ask what do you think about this warning: Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
