### ISSUE TITLE
UI: apply diamond architecture to the remained or missed components

### ISSUE THREAD

**Issue by bojan07** [pavlovcik/uad-ui#807]
The diamond architecture has been applied to each pages of ui, but still some components(including monitor page) are untouched. and the ui codebase needs to be checked at the point of whole implementation of new architecture

**list of components**
- [inventory.tsx](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/layout/inventory.tsx)
- [metapool-monitor.tsx](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/monitor/metapool-monitor.tsx)
- [price-monitor.tsx](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/monitor/price-monitor.tsx)
- [token-monitor.tsx](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/monitor/token-monitor.tsx)
- [debt-coupon-deposit.tsx](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/redeem/debt-coupon-deposit.tsx)
- [ucr-nft-redeem.tsx](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/redeem/ucr-nft-redeem.tsx)
- [ucr-redeem.tsx](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/redeem/ucr-redeem.tsx)

Also the old names used in ui still not well compatible with new architecture.

We have a convention of using full names for tokens (ex: `uad => Dollar, ucr => Credit, ubq => Governance`). This issue implies refactoring naming as well.

**Comment by molecula451** [comment]
let's focus first at #783 as rndqnuu crafted a well established, need-to achieve goals/tasks

**Comment by bojan07** [comment]
> let's focus first at #783 as rndqnuu crafted a well established, need-to achieve goals/tasks

Okay, np

**Comment by rndquu** [comment]
@bojan07 Could you provide an exact list of components that should also be upgraded? The issue description is ambiguous right now.

**Comment by bojan07** [comment]
> @bojan07 Could you provide an exact list of components that should also be upgraded? The issue description is ambiguous right now.

Yeah, I can. Just a sec. Let me update the issue description soon

**Comment by bojan07** [comment]
@rndquu I'm going to solve this issue while you are checking. Is this necessary to implement diamond architecture to the repo, or not?

**Comment by rndquu** [comment]
@bojan07 

> Is this necessary to implement diamond architecture to the repo, or not?

yes

Notice that there's a new abstract in the issue's description regarding full contract/token names.

**Comment by bojan07** [comment]
> @bojan07
> 
> > Is this necessary to implement diamond architecture to the repo, or not?
> 
> yes
> 
> Notice that there's a new abstract in the issue's description regarding full contract/token names.

Yeah, got it. let me start to solve this issue

**Comment by bojan07** [comment]
We should replace crv too? like this..`crv` -> `curveToken` or `curveDaoToken` or `curve3CrvToken`

I have replaced `crv` with `curve3CrvToken`

**Comment by bojan07** [comment]
> We should replace crv too? like this..`crv` -> `curveToken` or `curveDaoToken` or `curve3CrvToken`

**Comment by rndquu** [comment]
> We should replace crv too? like this..`crv` -> `curveToken` or `curveDaoToken` or `curve3CrvToken`

yes

> I have replaced `crv` with `curve3CrvToken`

I would call it smth like `curveTriPoolLpToken` but `curve3CrvToken` is also fine

**Comment by bojan07** [comment]
What's alternative of `uAR`?

**Comment by 0x4007** [comment]
I'm debating on if we should remove support for our debt primitives, which we rebranded to as "credits" for our immediate goals. 

There are two: 

1. the original design, an nft version. uCR-NFT (Ubiquity Credit NFT)
2. A fungible token. uCR (Ubiquity Credit)


That is what we are renaming from "Ubiquity Auto Redeem" uAR and "Ubiquity Debt" uDEBT

Fun trivia: uDEBT allowed us to raise our preseed round pretty easily.

**Comment by bojan07** [comment]
> I'm debating on if we should remove support for our debt primitives, which we rebranded to as "credits" for our immediate goals.
> 
> There are two:
> 
> 1. the original design, an nft version. uCR-NFT (Ubiquity Credit NFT)
> 2. A fungible token. uCR (Ubiquity Credit)
> 
> That is what we are renaming from "Ubiquity Auto Redeem" uAR and "Ubiquity Debt" uDEBT
> 
> Fun trivia: uDEBT allowed us to raise our preseed round pretty easily.

sweet info. could you check [this](https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/debt-coupon.tsx#L22C17-L22C17)?
```
type Coupon = {
  amount: number;
  expiration: number;
  swap: { amount: number; unit: string };
};

type Coupons = {
  // cspell: disable-next-line
  uDEBT: Coupon[];
  // cspell: disable-next-line
  stakingShare: number;
  // cspell: disable-next-line
  uAR: number;
};
```
Above part replaced with the following codebase
```
type Nft = {
  amount: number;
  expiration: number;
  swap: { amount: number; unit: string };
};

type Nfts = {
  // cspell: disable-next-line
  credit: Nft[];
  // cspell: disable-next-line
  stakingShare: number;
  // cspell: disable-next-line
  uAR: number;
};
```
I didn't touch `uAR`. Is it still okay or should it be replaced with something?

**Comment by rndquu** [comment]
@bojan07 

> What's alternative of uAR?

`Credit`

> sweet info. could you check [this](https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/debt-coupon.tsx#L22C17-L22C17)?

I think `Coupon` should be refactored to `CreditNft`

> I didn't touch uAR. Is it still okay or should it be replaced with something?

For this case we could use smth like `creditAmount`:
```
type Nfts = {
  // cspell: disable-next-line
  credit: Nft[];
  // cspell: disable-next-line
  stakingShare: number;
  // cspell: disable-next-line
  creditAmount: number;
};
```

**Comment by molecula451** [comment]
> Fun trivia: uDEBT allowed us to raise our preseed round pretty easily.

😄 we need more of this trivia

**Comment by bojan07** [comment]
https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/debt-coupon.tsx#L340
Please check this link
How can I change this function name? `uarToUDebtFormula` ?

**Comment by bojan07** [comment]
https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/debt-coupon.tsx#L64
https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/redeem/debt-coupon.tsx#L66
And pls check these 2 lines
I'm confused how to change these 2 const variable names: `uarDeprecationRate` and `uDebtDeprecationRate`
I'm replacing `uDebt` with `credit`, and I'm informed that `uar` should be replaced with `credit`.. then will be same variable..

**Comment by 0x4007** [comment]
Economically they serve basically the same purpose (credit.) 

Technically one is a fungible token, the other is not. 

Credit
Credit NFT

---

`uDebtDeprecationRate` can be creditNft Depreciation Rate

But in reality the "credit clock" means that credits can appreciate or depreciate so that's not implemented correctly in the UI it seems. 

@rndquu I'm still debating on if we should just remove the credit related features for our upcoming deadline because they aren't essential. If there's a lot of code related to credits perhaps we should drop them. If we are almost done handling all the code then we can keep making adjustments. What do you think?

**Comment by rndquu** [comment]
@bojan07 

`uAR` is `Credit` and `uDebt` is `CreditNft`

So the renamings are:
```
uarToUDebtFormula => creditToCreditNftFormula
uarDeprecationRate => creditDeprecationRate
uDebtDeprecationRate => creditNftDeprecationRate
```

**Comment by rndquu** [comment]
> Economically they serve basically the same purpose (credit.)
> 
> Technically one is a fungible token, the other is not.
> 
> Credit Credit NFT
> 
> `uDebtDeprecationRate` can be creditNft Depreciation Rate
> 
> But in reality the "credit clock" means that credits can appreciate or depreciate so that's not implemented correctly in the UI it seems.
> 
> @rndquu I'm still debating on if we should just remove the credit related features for our upcoming deadline because they aren't essential. If there's a lot of code related to credits perhaps we should drop them. If we are almost done handling all the code then we can keep making adjustments. What do you think?

How can we drop the "credits feature" if it helps supporting the peg? So if Dollar < 1$ then users should burn Dollars in exchange for Credits or CreditNfts. This mechanism seems to be essential.

**Comment by molecula451** [comment]
> But in reality the "credit clock" means that credits can appreciate or depreciate so that's not implemented correctly in the UI it seems.
> 
> @rndquu I'm still debating on if we should just remove the credit related features for our upcoming deadline because they aren't essential. If there's a lot of code related to credits perhaps we should drop them. If we are almost done handling all the code then we can keep making adjustments. What do you think?

this popping up, Can we have consensus with this one? Otherwise what's up with #772

**Comment by bojan07** [comment]
Thanks @rndquu @molecula451
