### ISSUE TITLE
Broken yarn start &

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#814]
https://github.com/ubiquity/ubiquity-dollar/blob/17e79d31bca7a9c573990c6fec107f0ec1384ede/README.md?plain=1#L26

Usage Error: Couldn't find a script named "start".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...

**Comment by rndquu** [comment]
If you open `packages/dapp` and run `yarn start` then the dapp is opened without any errors. What should be fixed as a part of the current issue?

**Comment by molecula451** [comment]
this is to update the `&` which seems misleading

**Comment by rndquu** [comment]
> this is to update the `&` which seems misleading

Raising an issue seems to be an overkill for `yarn start &` => `yarn start` docs update.

I agree that readme could be improved. The [dev setup part](https://github.com/ubiquity/ubiquity-dollar#development-setup) could be updated to smth like:
```
# How to run locally
## start anvil
yarn workspace @ubiquity/contracts start:anvil
## run development deploy
yarn workspace @ubiquity/contracts deploy:development
## start frontend app
yarn workspace @ubiquity/dapp start
```

Perhaps you could improve the readme as a part of the current issue?

**Comment by molecula451** [comment]
of course

**Comment by molecula451** [comment]
part of the readme i think we should also get rid of these private keys https://github.com/ubiquity/ubiquity-dollar#metamask-development-wallet-setup

the contribution to this it's 0% (i think) i've never used them, and a dev should be very aware which key use, also the defactos are from anvil, more than cosmetical i think they do not really add value
