### ISSUE TITLE
`dApp`: UI fixes

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#815]
What should be done:
1. Fix "network error" when [credits page](https://uad.ubq.fi/credits) is opened ([context](https://github.com/ubiquity/ubiquity-dollar/pull/804#issuecomment-1760367675))
2. There is the uniswap widget in the [credits page](https://uad.ubq.fi/credits). Not sure if it is used somehow. If it is used then we should make it responsive else we're free to remove it.
3. Check the [frontend app](https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/dapp) for unused components which should be removed
4. Fix errors on network switches. There should not be any errors when user switches between mainnet, testnet or anvil.
5. Fix wallet connect errors. When you authorize via wallet connect (ex: metamask) there are errors in the console like `Error: missing revert data in call exception; Transaction reverted without a reason string` or [invalid key](https://github.com/ubiquity/ubiquity-dollar/issues/815#issuecomment-1772509602). We should fix all auth errors.
6. Update Prettier

**Comment by rndquu** [comment]
Could you elaborate on which UI packages should be updated and why?

**Comment by molecula451** [comment]
smart-order-router uniswap for e.g, to fix the Network Error issue

**Comment by molecula451** [comment]
but if we're going to purge the widget we will probably not need it

**Comment by molecula451** [comment]
@rndquu wallet connect should be fixed why do we keep getting error key on production deployment dapp? The secret k
Is not being readen?

**Comment by rndquu** [comment]
> @rndquu wallet connect should be fixed why do we keep getting error key on production deployment dapp? The secret k Is not being readen?

Updated description

**Comment by molecula451** [comment]
> > @rndquu wallet connect should be fixed why do we keep getting error key on production deployment dapp? The secret k Is not being readen?
> 
> Updated description

nice but im referring to the error that you pass a key from walletconnect.org at .env

https://github.com/molecula451/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/.env.example#L3

![wallet](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/eb5ce667-92d4-4fa4-8092-f0354c258864)

**Comment by molecula451** [comment]
> > > @rndquu wallet connect should be fixed why do we keep getting error key on production deployment dapp? The secret k Is not being readen?
> > 
> > 
> > Updated description
> 
> nice but im referring to the error that you need to pass a key from walletconnect.org at .env
> 
> https://github.com/molecula451/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/.env.example#L3
> 
> ![wallet](https://user-images.githubusercontent.com/41552663/276905957-eb5ce667-92d4-4fa4-8092-f0354c258864.png)

**Comment by molecula451** [comment]
if we are purging uniswap widget what's the point of refactoring the `credit-redeem.tsx` it's connected to it, are we therefore getting rigged of this credit redeem? @rndquu

**Comment by molecula451** [comment]
the router seem it was used to swap back the credits to dollar and dollar to credits, and along with the tokens at https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/lib/utils.ts#L153

**Comment by molecula451** [comment]
if we remove the router its one way of getting rid of `Network Error` issue that is for sure


https://github.com/ubiquity/ubiquity-dollar/assets/41552663/654f85fd-7506-40c9-9a96-a84f6b59fb1d

**Comment by molecula451** [comment]
also we should not be refactoring [ucr-redeem.tsx](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/redeem/ucr-redeem.tsx) at #824 if the router it's going to be purge as the main use seem to be the router there

**Comment by rndquu** [comment]
> the router seem it was used to swap back the credits to dollar and dollar to credits, and along with the tokens at
> 
> https://github.com/ubiquity/ubiquity-dollar/blob/97989f176ebcbf0e726d3d5aa5029e85fc1f15d0/packages/dapp/components/lib/utils.ts#L153

Then we're not purging the uniswap widget

**Comment by molecula451** [comment]
widget relevant data https://github.com/ubiquity/ubiquity-dollar/issues/280#issuecomment-1280491634

**Comment by rndquu** [comment]
Closing in favor of https://github.com/ubiquity/uusd.ubq.fi/issues/1
