### ISSUE TITLE
Responsive Uniswap Widget

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#816]

**Comment by rndquu** [comment]
Isn't it responsive by default?

I haven't investigated in depth, but as far as I remember we can remove the uniswap widget because we don't use it.

**Comment by molecula451** [comment]
Good to know, no, it's not responsive if you open in wide screen it will not look accordingly

**Comment by rndquu** [comment]
Closing this in favour of https://github.com/ubiquity/ubiquity-dollar/issues/815
