### ISSUE TITLE
Remove/refactor/purge unused UI components

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#817]

**Comment by rndquu** [comment]
What exact components should be removed?

**Comment by molecula451** [comment]
smart-order-router uniswap for e.g, to fix the Network Error issue

**Comment by molecula451** [comment]
we have 2 architectures, the one we recently build to bring the contracts useProtocolContracts

and the old one useManagedManaged, we are purging the last one

**Comment by rndquu** [comment]
Closing this in favour of https://github.com/ubiquity/ubiquity-dollar/issues/815
