### ISSUE TITLE
Prettier: Update non-breaking space rule

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#821]

**Comment by rndquu** [comment]
Which way we should update this rule (add/remove) and why it is an issue?

**Comment by molecula451** [comment]
one rule would be if we really want to have `""` instead or `''` or viceversa, but there could be more

**Comment by rndquu** [comment]
> one rule would be if we really want to have `""` instead or `''` or viceversa, but there could be more

Pls update the issue description because it is hard to understand what exactly we should change, `nbsp`, quotes or smth else

**Comment by molecula451** [comment]
closing part of #815 too
