### ISSUE TITLE
Incorrect coverage values in the `Compare Test Coverage` workflow 

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#826]
[Context](https://github.com/ubiquity/ubiquity-dollar/pull/825#issuecomment-1777205152)

Check [this](https://github.com/ubiquity/ubiquity-dollar/actions/runs/6627359435/job/18002118554#logs) CI run which calculates the following coverage values and fails afterwards because the coverage has been decreased:
```
Development branch coverage: 69.1
PR branch coverage: 10.1
```

The PR branch coverage couldn't fail so drastically. We should find the root cause of the bug and fix it.

**Comment by gitcoindev** [comment]
It is quite interesting to know not only **how** to fix this but **why** does it happen.

The root cause of the error is, that the Diamond Test setUp loads compiled facet JSON ABIs to interact with facet contracts, and foundry internally uses a special `ephemeral_no_artifacts_project` option during coverage build, which does not write ABIs output to files. I had to dig into foundry internals to find this out, the details are available at:

https://github.com/foundry-rs/foundry/blob/251ef74e04c6ad11eb02787c4b6190858d4ec1d7/crates/forge/bin/cmd/coverage.rs#L103

https://github.com/foundry-rs/foundry/blob/master/crates/config/src/lib.rs#L618

I experimented a bit already when I found out that out folder was missing for coverage build. I will try to provide a fix, test on my fork and submit a PR today.

**Comment by gitcoindev** [comment]
Update: I was able to reproduce the error on CI on my fork and on my local build and create a bug fix. I will do 2-3 more runs and open a pull request soon.

**Comment by gitcoindev** [comment]
Pull request opened:  https://github.com/ubiquity/ubiquity-dollar/pull/828
QA: https://github.com/ubiquity/ubiquity-dollar/actions/runs/6640128671/job/18039922554?pr=828
Generated coverage report: https://coveralls.io/jobs/130669501

**Comment by molecula451** [comment]
the thing it's this coverage all test compare it's a bit unpredictable, i've seen it failing without really a justified reason, how do you think it won't fail for other edge cases, can you maybe provide QA of other test edge cases?

**Comment by gitcoindev** [comment]
Hi @molecula451 I have been testing it for a few hours now, tweaking the yaml on my fork. Could you please provide any example of an edge case that failed for you?

**Comment by molecula451** [comment]
there can be anything to the code to be honest, from the `package/dapp` to `package/contracts`, when you modify tests in Facet tests `Contracts.t.sol` for e.g but to give you a broader angle you can try to look and runner actions older logs and you may find PR's that worked well and that has this coverage decrease and provide another edges from there

**Comment by gitcoindev** [comment]
@molecula451 this is also why I separated the folders - development branch is now fetched to development/ folder and pull request branch is fetched to pr/ folder. Both are built and tested from scratch. Takes a bit longer but there should not be clashes anymore. This coverage workflow compares pr and development branch for `packages/contracts` only and it does not execute dapp tests. I tested multiple times and numbers always seem to be correct.

I had a look at https://github.com/coverallsapp/github-action and interestingly, this github action seems to support pull requests comparisons out of the box. So perhaps the workflow could be simplified as well and execute on each push to development once and then compare against pull requests. This would speed up the job, as currently it always executes `forge coverage` twice.

And finally, a nice badge could be added to the repository to show the current coverage, like in https://github.com/nickmerwin/node-coveralls

I will check tomorrow and experiment on this, but the original issue (incorrect coverage values) seems to be solved.

**Comment by gitcoindev** [comment]
PR ready for the review.

**Comment by gitcoindev** [comment]
Thank you, closed another one! Btw. hiccup price label 112.5 WXDAI vs 75 WXDAI permit, hopefully all this will be sorted out after the big refactoring.. fyi @pavlovcik

**Comment by rndquu** [comment]
> Thank you, closed another one! Btw. hiccup price label 112.5 WXDAI vs 75 WXDAI permit, hopefully all this will be sorted out after the big refactoring.. fyi @pavlovcik

As far as I understand the [reward](https://github.com/ubiquity/ubiquity-dollar/issues/826#issuecomment-1787433975) amount is correct. The `Time:<2 Hours` and `Priority: 1` labels give 25 USD reward which is multiplied by the [multiplier config param](https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/ubiquibot-config.yml#L1) which gives 75 WXDAI. Not sure why the label states the `112.5 WXDAI` reward.

**Comment by 0x4007** [comment]
> Thank you, closed another one! Btw. hiccup price label 112.5 WXDAI vs 75 WXDAI permit, hopefully all this will be sorted out after the big refactoring.. fyi @pavlovcik

Yes the assignee reward is taken exactly from the label in the refactored version.
