### ISSUE TITLE
Create `testnet` and `mainnet` deploy scripts

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#827]
Right now we have only the [development deploy script](https://github.com/ubiquity/ubiquity-dollar/tree/df84ee4fb91de780c46ae231ed68a7cd644215d6/packages/contracts/scripts/deploy/dollar/solidityScripting) (`yarn deploy:development`) which deploys contracts to a local anvil instance.

What should be done:
1. Add deployment script for sepolia testnet
2. Add deployment script for mainnet

**Comment by molecula451** [comment]
Mainnet: 1
Sepolia: 11155111
