### ISSUE TITLE
Collateral TWAP price miscalculation

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#830]
We have the [UbiquityPoolFacet](https://github.com/ubiquity/ubiquity-dollar/blob/7a70182d49a0b9dc947c9925a5d28edc49c28b0d/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol) contract (which uses [LibUbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/7a70182d49a0b9dc947c9925a5d28edc49c28b0d/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol) library under the hood) which is responsible for minting/redeeming Dollar tokens for collateral.

Example:
1. User calls [mintDollar()](https://github.com/ubiquity/ubiquity-dollar/blob/7a70182d49a0b9dc947c9925a5d28edc49c28b0d/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L20) and sends 100 LUSD as collateral
2. User gets 100 Dollars

Now check this [test](https://github.com/rndquu/ubiquity-dollar/blob/5b6bcd03837b2f8cc704593534e9742f6cc5af75/packages/contracts/test/diamond/facets/UbiquityPoolFacet.t.sol#L345). It basically simulates the [calcMintDollarAmount()](https://github.com/ubiquity/ubiquity-dollar/blob/7a70182d49a0b9dc947c9925a5d28edc49c28b0d/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L382) method responsible for calculating how much Dollars should be minted/redeemed in exchange for collateral tokens.

The calculation seems to be wrong because when we try to get the collateral price in USD here https://github.com/ubiquity/ubiquity-dollar/blob/7a70182d49a0b9dc947c9925a5d28edc49c28b0d/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L438 we use cumulative price which seems to be wrong. As a result user gets much more Dollars in exchange for collateral. Example:
1. User calls [mintDollar()](https://github.com/ubiquity/ubiquity-dollar/blob/7a70182d49a0b9dc947c9925a5d28edc49c28b0d/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L20) and sends 100 LUSD as collateral
2. User gets `~239561778028138198.47` Dollars which is way too high

As a part of the current issue we should add a new method to the [oracle faucet](https://github.com/ubiquity/ubiquity-dollar/blob/7a70182d49a0b9dc947c9925a5d28edc49c28b0d/packages/contracts/src/dollar/facets/TWAPOracleDollar3poolFacet.sol) which will be responsible for fetching collateral token prices in USD.

Possible options:
1. Curve TWAP (we already use it for the Dollar token)
2. Chainlink oracles

**Comment by AlooDon** [comment]
is this open for attempting @rndquu

**Comment by rndquu** [comment]
> is this open for attempting @rndquu

Hey, yes

**Comment by gitcoindev** [comment]
No progress was made, I will try to find the root cause and hopefully fix this.

**Comment by gitcoindev** [comment]
I think I found a way to implement this correctly.

```
Running 1 test for test/diamond/facets/UbiquityPoolFacet.t.sol:UbiquityPoolFacetTest
[PASS] testCollateralTwap() (gas: 133837)
Logs:
  LUSD Curve MetaPool tokens
  0 (LUSD): 0x5f98805A4E8be255a32880FDeC7F6728C6568bA0
  1 (3CRV): 0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490
  get_price_cumulative_last()[0] (LUSD) : 2576835979968650582055295336346502
  get_price_cumulative_last()[1] (3CRV) : 4894835369996648397661910717659729
  block_timestamp_last: 1700776559
  dy last: 967501938862099827
  dollarsOut: 90388445519065770216

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 4.64s
Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)
```
...

```
Running 1 test for test/diamond/facets/UbiquityPoolFacet.t.sol:UbiquityPoolFacetTest
[PASS] testCollateralTwap() (gas: 133837)
Logs:
  LUSD Curve MetaPool tokens
  0 (LUSD): 0x5f98805A4E8be255a32880FDeC7F6728C6568bA0
  1 (3CRV): 0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490
  get_price_cumulative_last()[0] (LUSD) : 2576865692445777709373565553899126
  get_price_cumulative_last()[1] (3CRV) : 4894843303717373371511942034905809
  block_timestamp_last: 1700778623
  dy last: 967448572577455653
  dollarsOut: 90383459797261648426

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 5.51s
Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

Last available price gives for 100 LUSD collateral about 90.388 3CRV tokens which seems correct when fee is included. I need to think over how to implement a test. likely I will create LUSD Curve MetaPool mock with values, so that forking will not be needed in forge. From balances and time delta we will get VWAP price using two pairs of get_price_cumulative_last and elapsed time. I will describe the calculations in a detail and open a PR tomorrow morning.

**Comment by gitcoindev** [comment]
I will try to finish by tomorrow EOD, just wrapping up an another PR.

**Comment by gitcoindev** [comment]
In the end I am going to implement also chainlink oracle support for any collateral in scope of this ticket which is half baked already on my local set up.

**Comment by rndquu** [comment]
> In the end I am going to implement also chainlink oracle support for any collateral in scope of this ticket which is half baked already on my local set up.

Yes, there is no need to overengineer the solution, chainlink is fine.

As a part of the current issue we were expecting:
1. Implement chainlink oracles for collateral token prices
2. Check that our current [Dollar oracle](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/libraries/LibTWAPOracle.sol) works as expected (and can't be easily manipulated, but it depends on the curve metapool liquidity, as far as I understand)

**Comment by gitcoindev** [comment]
I will try to finalize this tomorrow till EOD.

**Comment by rndquu** [comment]
@gitcoindev You could delegate some of the tasks to me (collateral price via chainlink feature or fixing Dollar curve price). We must have this issue done till 31 December.

**Comment by gitcoindev** [comment]
> @gitcoindev You could delegate some of the tasks to me (collateral price via chainlink feature or fixing Dollar curve price). We must have this issue done till 31 December.

Thanks @rndquu I was diving into other tasks and should have given this one the priority and give an update. I got to a point where I implemented the ChainLink price feed update and a mocked ChainLink interface. This all seems to work correctly on a mocked test case and the test case passes. 

```
contracts/src$ forge test -vvv --match-test testCollateralPriceFeed
[⠘] Compiling...
[⠔] Compiling 1 files with 0.8.19
[⠑] Solc 0.8.19 finished in 10.62s
Compiler run successful!

Running 1 test for test/diamond/facets/UbiquityPoolFacet.t.sol:UbiquityPoolFacetTest
[PASS] testCollateralPriceFeed() (gas: 188375)
Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 1.10s
Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

I would like to experiment also on a ChainLink test feed on Anvil using e.g. https://docs.chain.link/quickstarts/foundry-chainlink-toolkit before we deploy on testnet. 

I will sit on this still today and also finish the twap part, if I do not make it by tomorrow would be happy if you helped on this onward.

**Comment by gitcoindev** [comment]
Yesterday I had a look at the local test ChainLink RPCs. I am doing last tests for Knip CI and pushed out other tasks off my plate.  In  about 1 hour I will start working on ChainLink testing and TWAP and we should be able to hopefully finally close the issue today. In the meantime @rndquu you may check the open PR, it is still a draft, the twap and twap test needs to be completely reworked after I update the library but other parts give an overview of changes for ChainLink price feed.

**Comment by rndquu** [comment]
@pavlovcik Permit was not generated, not sure if this is expected. As far as I understand we owe 300 USD to @gitcoindev

**Comment by 0x4007** [comment]
When I get a chance to, I need to add compute.yml to our ubiquibot-config repo. If you "edit" the uncaught error bot message you can read the error metadata. 

![image](https://github.com/ubiquity/ubiquity-dollar/assets/4975670/6fbeaa8e-0be1-4099-9fb0-11b6779126ec)

**Comment by 0x4007** [comment]
Let's see if this works...

**Comment by 0x4007** [comment]
I'll debug it here.

**Comment by 0x4007** [comment]
There's something wrong with the Netlify environment variables then.

**Comment by 0x4007** [comment]
lol also a bug regarding qualitative analysis: 

```
    message: "This model's maximum context length is 4097 tokens. However, your messages resulted in 4299 tokens. Please reduce the length of the messages.",
```

https://github.com/ubiquibot/comment-incentives/actions/runs/7309635303/job/19917431369

I'll work on the open ai issue and the env var issue.

**Comment by 0x4007** [comment]
Cool, I just need to push a fix regarding the Open AI token limit

**Comment by 0x4007** [comment]
Just set context length to 128k...

**Comment by 0x4007** [comment]
Can't get OpenAI to cooperate anymore.

**Comment by 0x4007** [comment]
I coerced the OpenAI relevance sampler to work, but, @rndquu perhaps you can help me implement a fix for: 

```
Error: Error: incorrect key pair for the given ciphertext
```
Source https://github.com/ubiquibot/comment-incentives/actions/runs/7316071529/job/19930337990#step:5:631

### Context

- The bot can directly read the invoking organization's UbiquiBot Config (both the org's and repo's)
- You can see in the logs that the bot reads `evmPrivateEncrypted: 'OwWrEtDWl7mq79FM-mb4hbrU9uBtffvX3MPuEjcXenWocH-JS4SVYXFr0rm-wYuWHnwrzLYvatKGywShwMVCEZw6f-g2XyDIPdrEzAHCZ8WH_v76kJsVEOGEe8qRvy4z6ai0YGFpzV4iFB8NfZEg5kb9k88',` just fine. 
- I understand that the decryption failed due to a mismatched `X25519_PRIVATE_KEY`?

### Questions

- In order to just make this work, perhaps you can help me regenerate the proper `X25519_PRIVATE_KEY` so that we can continue to use the existing `evmPrivateEncrypted`? Or you can help me set up a new key pair that will work?
   - I just checked the [source code](https://github.com/pavlovcik/pay.ubq.fi/blob/b259f9736212ca40dac241eb40b2b961bb3d6f39/static/scripts/onboarding/onboarding.ts#L32) (we obviously need a more secure replacement for this onboarding UI.) and used the identical `X25519_PRIVATE_KEY` but the run [still failed](https://github.com/ubiquibot/comment-incentives/actions/runs/7316183062/job/19930563324#step:5:665). 
- Is this approach okay, where the bot can read the `evmPrivateEncrypted` of every partner, and we simply store a single `X25519_PRIVATE_KEY` in the bot secrets?
- If any partner can encrypt their EVM private key, doesn't that mean they necessarily have access to our source `X25519_PRIVATE_KEY`?
- Are there any improvements you can suggest?

### Remarks

Something seems off: 
1. I regenerated a new pair and [updated the encrypted private key](https://github.com/ubiquity/ubiquibot-config/commit/568440dea0155a7e9fc839d6e8436aabb71ac1e3). 
2. It [sort of ran once](https://github.com/ubiquibot/comment-incentives/actions/runs/7316295068/job/19930779580#step:5:730) right after that fix.
3. I updated the `X25519_PRIVATE_KEY` in the ubiquibot org (the one hosting the comment incentives plugin) to the correct value, and now I'm having the same key related issues.

Given all these new insights, I'm starting to think that the only way forward is for plugins to request a transaction on partner gnosis safes. If anybody can make a plugin and freely maintain/update them, then it seems a bit risky for them to have access to the shared X25519 key which allows them to access any private keys encrypted with the same X25519 key.

**Comment by molecula451** [comment]
@pavlovcik i thoght we'd nailed the private key bug?

**Comment by 0x4007** [comment]
I'm not sure. To be honest I never felt mastery around the X25519 key related feature so it's possible that I'm making a mistake in the configuration.

**Comment by rndquu** [comment]
@pavlovcik 

> You can see in the logs that the bot reads evmPrivateEncrypted: 'OwWrEtDWl7mq79FM-mb4hbrU9uBtffvX3MPuEjcXenWocH-JS4SVYXFr0rm-wYuWHnwrzLYvatKGywShwMVCEZw6f-g2XyDIPdrEzAHCZ8WH_v76kJsVEOGEe8qRvy4z6ai0YGFpzV4iFB8NfZEg5kb9k88', just fine.


I've just successfully decrypted this private key for the `0xf87ca4583c792212e52720d127e7e0a38b818ad1` address. I will DM you `x25519_private_key` and `x25519_public_key` for you to double check.

> I understand that the decryption failed due to a mismatched X25519_PRIVATE_KEY?

Yes

> I just checked the [source code](https://github.com/pavlovcik/pay.ubq.fi/blob/b259f9736212ca40dac241eb40b2b961bb3d6f39/static/scripts/onboarding/onboarding.ts#L32) (we obviously need a more secure replacement for this onboarding UI.) and used the identical X25519_PRIVATE_KEY but the run [still failed](https://github.com/ubiquibot/comment-incentives/actions/runs/7316183062/job/19930563324#step:5:665).

This is public key, not private, so it is safe to share it. Naming could've been better.

> Is this approach okay, where the bot can read the evmPrivateEncrypted of every partner, and we simply store a single X25519_PRIVATE_KEY in the bot secrets?

Yes. The only risk is that if `X25519_PRIVATE_KEY` is leaked (on our side) then a malicious actor will be able to decrypt partners' private keys (if there are in public repos, not private).

> If any partner can encrypt their EVM private key, doesn't that mean they necessarily have access to our source X25519_PRIVATE_KEY?

No. Partners encrypt with `X25519_PUBLIC_KEY` (which is available in [public](https://github.com/pavlovcik/pay.ubq.fi/blob/b259f9736212ca40dac241eb40b2b961bb3d6f39/static/scripts/onboarding/onboarding.ts#L32)) while for decrypting `X25519_PRIVATE_KEY` is necessary which is stored only on the bot's side (i.e. backend).

 > Are there any improvements you can suggest?
 
 You've already proposed that we need critical env variables rotation mechanism and `X25519_PRIVATE_KEY` is the 1st candidate for such rotation.

**Comment by 0x4007** [comment]
Sorry for clouding the conversation on this with debugging the bot! 

@rndquu @gitcoindev @molecula451 I have concerns around using Chainlink and censorship resistance. Chainlink is a centralized point of failure for the protocol. Why not use the on chain TWAPs instead? Perhaps we can have a planned upgrade sometime in late 2024 to change the oracle(s)?

**Comment by molecula451** [comment]
Indeed a well thought chainlink it's a heavily centrilized organization which the only good thing they provide it's infrastructure as a service and well known set of poketing of smart contracts, and use cases in with heavily demanded protocols that are using it, but that's it

**Comment by gitcoindev** [comment]
ChainLink is an industry standard but yes, this should not be a single point of failure. 

When I started working on TWAP I realized the security implications of using just TWAP, and expected some findings from the audit as well. We should think this through. Since the contracts were partially based on Frax I had a look at latest oracles there and their implementation is very good in this matter.

https://docs.frax.finance/frax-oracle/frax-oracle-overview
https://docs.frax.finance/frax-oracle/how-it-works
https://docs.frax.finance/frax-oracle/advanced-concepts

The executive summary is as follows: to retrieve frxEth / ETH price they use dual oracles that combine ChainLink and Uniswap V3  TWAP feeds into one feed, provided lowest and highest prices from those two. 

In their case for frxEth price is bounded to be 0.7 at the lowest (0.7 frxEth = 1 ETH) and 1 at the highest (1 frxEth = 1 ETH).

On top of that they have implemented a Frax Oracle contract that uses feeds from above dual oracles for different pairs and different networks.

If one of the price providers in dual oracle fails / is stalled or censored, the second price will be used. Perhaps some blogs or articles explain this in more detail.

The oracles implementation repository was created around 4 months ago https://github.com/FraxFinance/frax-oracles

I think it also might be beneficial to dig into Sherlock past contests to see if they already audited those oracles or some other projects that use them and the findings they had. If no such audits are available we could as well try to find other approaches for oracles from past security audits and try to create an overview of the available most secure solutions. Then pick one and upgrade the current solution.

**Comment by rndquu** [comment]
> Sorry for clouding the conversation on this with debugging the bot!
> 
> @rndquu @gitcoindev @molecula451 I have concerns around using Chainlink and censorship resistance. Chainlink is a centralized point of failure for the protocol. Why not use the on chain TWAPs instead? Perhaps we can have a planned upgrade sometime in late 2024 to change the oracle(s)?

We'll gradually move to smth like "take the median price from chainlink, curve, uniswap, other oracle provider". Right now chainlink is the fastest to implement, safest and most reliable solution.

**Comment by 0x4007** [comment]
Hey guys, as a workaround I salvaged these permits from the GitHub Actions logs. Sadly its cut off and I couldn't figure out how to see more from the run (sorry @rndquu):


  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiI4NjAwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjI4NDcxMzc4NTU2MTA3Nzk5MjQ4ODA1NDkxNDQ5ODUyMTU3ODk1MzI4MDc4MjE3NDg0OTcxMjU4NDU0NzE0MDIwMzg1NTA5NjI3NjQ3IiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHg0MDA3Q0UyMDgzYzdGM0UxODA5N2FlQjNBMzliYjhlQzE0OWEzNDFkIiwicmVxdWVzdGVkQW1vdW50IjoiODYwMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweDQ0Q2ExNURiMTAxZkQxYzE5NDQ2N0RiNkFGMGM2N0M2QmJGNEFCNTEiLCJzaWduYXR1cmUiOiIweGNiMjViMmNmMTA1YmEzNzRjMjk2ZDJlOTcxZjYzYTA4MjdlMDQ5ZWYxY2Q4ZDBjNDVmNDcyNzExN2ViNjE0OGYxZTc2OWYxNzM3YjE4NDhiZThiMTEwYzk0NjgwOTExNDViZDlkNTcyMGE3ODdhOTVkMTlmNzI4NmFkYTY5YmQxMWMiLCJuZXR3b3JrSWQiOjEwMH1d"
          >
            [ 86 WXDAI ]</a
          >
        </h3>
        <h6>@pavlovcik</h6></b
      >
    </summary>
    <h6>Contributions Overview</h6>
<table><thead>
<tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th>
</thead><tbody>
<tr><td>Issue</td><td>Comment</td><td>11</td><td>84.3</td></tr>
<tr><td>Review</td><td>Comment</td><td>1</td><td>1.7</td></tr>
</tbody></table>
    <h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1868191897">When I get a chance to, I need to add compute.yml to our ubiquib...</a></h6></td><td>3.1</td><td>-</td><td>3.1</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1868335592">Let\'s see if this works......</a></h6></td><td>0.6</td><td>-</td><td>0.6</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1868338715">I\'ll debug it here....</a></h6></td><td>0.5</td><td>-</td><td>0.5</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1868338886">There\'s something wrong with the Netlify environment variables t...</a></h6></td><td>1</td><td>-</td><td>1</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1868339255">lol also a bug regarding qualitative analysis: 


    mess...</a></h6></td><td><details><summary>6.5</summary>
<pre>code:
  count: 1
  score: "1"
  words: 0
</pre>
</details></td><td>-</td><td>6.5</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1868340541">Cool, I just need to push a fix regarding the Open AI token limi...</a></h6></td><td>1.4</td><td>-</td><td>1.4</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1868354933">Just set context length to 128k......</a></h6></td><td>0.6</td><td>-</td><td>0.6</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1868358075">Can\'t get OpenAI to cooperate anymore....</a></h6></td><td>0.7</td><td>-</td><td>0.7</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1868569480">I coerced the OpenAI relevance sampler to work, but, @rndquu per...</a></h6></td><td><details><summary>61.2</summary>
<pre>h3:
  count: 3
  score: "3"
  words: 3
a:
  count: 4
  score: "4"
  words: 13
li:
  count: 11
  score: "11"
  words: 253
code:
  count: 10
  score: "10"
  words: 14
</pre>
</details></td><td>-</td><td>61.2</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1868630406">I\'m not sure. To be honest I never felt mastery around the X2551...</a></h6></td><td>3</td><td>-</td><td>3</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1913848421">Sorry for clouding the conversation on this with debugging the b...</a></h6></td><td>5.7</td><td>-</td><td>5.7</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/844#issuecomment-1864773423">Curve metapool seems to make the most sense to me. Can also cons...</a></h6></td><td>1.7</td><td>-</td><td>1.7</td></tr></tbody></table>
  </details>
  

  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIxNjgwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjY0MDEyMjQxMDM0NzQ3ODAyNDc3MjM3NDQ5ODI2NTQ3ODg3NjUzNTk5Mzc0MTY0Njc4OTkxNjk0NzM2Njg0NjEzMzM3Mzk3ODkxMjEiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweDE5Mjc1RTlmRDcyMTkwNkYyNzE1RDRiNzg2ODFiNDlkYTUwODgxMTciLCJyZXF1ZXN0ZWRBbW91bnQiOiIxNjgwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4NDRDYTE1RGIxMDFmRDFjMTk0NDY3RGI2QUYwYzY3QzZCYkY0QUI1MSIsInNpZ25hdHVyZSI6IjB4ZGFkYzUxZDhkNGEzNjQ4MzRiOGE0YjVmZjk4NjBmYjk3ZmM2NjM2MGZiM2U5YzI5ZGIzNzUxNzM3YjI4ZjI5YTNiYmU1NmU0MzI0ZTYwOTA5ZGEwYzQ3M2VkMDFiZmVmNzVhNjYzNTQzYjBiYTc0ZGE3NGY2ZjIwNzU1YWI3MDIxYyIsIm5ldHdvcmtJZCI6MTAwfV0%3D"
          >
            [ 16.8 WXDAI ]</a
          >
        </h3>
        <h6>@molecula451</h6></b
      >
    </summary>
    <h6>Contributions Overview</h6>
<table><thead>
<tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th>
</thead><tbody>
<tr><td>Issue</td><td>Comment</td><td>2</td><td>5.9</td></tr>
<tr><td>Review</td><td>Comment</td><td>5</td><td>10.9</td></tr>
</tbody></table>
    <h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1868609196">@pavlovcik i thoght we\'d nailed the private key bug?...</a></h6></td><td>1</td><td>-</td><td>1</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1913980425">Indeed a well thought chainlink it\'s a heavily centrilized organ...</a></h6></td><td>4.9</td><td>-</td><td>4.9</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/844#issuecomment-1834276526">> I am finally back to this issue, in the background I spent qui...</a></h6></td><td>0.7</td><td>-</td><td>0.7</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/844#issuecomment-1864869986">@rndquu are you sure? i\'m seeing a deployed chainlink LUSD/USD o...</a></h6></td><td>2.2</td><td>-</td><td>2.2</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/844#issuecomment-1865137915">> > @rndquu are you sure? i\'m seeing a deployed chainlink LUSD/U...</a></h6></td><td>3</td><td>-</td><td>3</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/844#issuecomment-1865168654">https://github.com/aave/gho-aip/blob/90ddf49b65007da9ba6dbf9f80c...</a></h6></td><td>1.4</td><td>-</td><td>1.4</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/844#issuecomment-1865177308">> Yeah, I see that\'s a live `LUSD/USD` oracle but I can\'t unders...</a></h6></td><td><details><summary>3.6</summary>
<pre>code:
  count: 1
  score: "1"
  words: 2
</pre>
</details></td><td>-</td><td>3.6</td></tr></tbody></table>
  </details>
  

  <details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiI1NTQxMDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiI0NzU3NjczNjExNTA0MDI2NTE3Njk5MDU3MDcyMTcxNzY3MDMxMDYwMDA3NDg0MzAwNDQ4NDE3MDM0Mzc3NDc4NTU2OTk5MTc2OTc1NCIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4N2U5MjQ3NkQ2OUZmMTM3N2E4YjQ1MTc2YjE4MjlDNEE1NTY2NjUzYSIsInJlcXVlc3RlZEFtb3VudCI6IjU1NDEwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4NDRDYTE1RGIxMDFmRDFjMTk0NDY3RGI2QUYwYzY3QzZCYkY0QUI1MSIsInNpZ25hdHVyZSI6IjB4Y2Q3NWRlMjZhNDhiMWI0M2ExY2IyMmM2Nzg1YTlkMDEwNzQxMjdhM2UyZGVhNzU2ZmVmOWJjNzIzNDE2ZThhYzY5MTMxODQ3ZjRjZWJhNGQ0NDM3OWRjZjEyNDFlZTFiOTc2OWU5YTkyM2FiMDRkMzE3ZjBkNDYwYWI1NThkMmIxYiIsIm5ldHdvcmtJZCI6MTAwfV0%3D"
          >
            [ 554.1 WXDAI ]</a
          >
        </h3>
        <h6>@gitcoindev</h6></b
      >
    </summary>
    <h6>Contributions Overview</h6>
<table><thead>
<tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th>
</thead><tbody>
<tr><td>Issue</td><td>Task</td><td>1.00</td><td>300</td></tr>
<tr><td>Issue</td><td>Comment</td><td>8</td><td>0</td></tr>
<tr><td>Issue</td><td>Comment</td><td>8</td><td>90.5</td></tr>
<tr><td>Review</td><td>Comment</td><td>15</td><td>81.8</td></tr>
<tr><td>Review</td><td>Comment</td><td>15</td><td>81.8</td></tr>
</tbody></table>
    <h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1824207692">No progress was made, I will try to find the root cause and hope...</a></h6></td><td>-</td><td>-</td><td>-</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/830#issuecomment-1824972585">I think I found a way to implement this correctly.


Runni...</a></h6></td><td><details><summary>-</summary>
<pre>code:
  count: 2
  score: "0"
  words: 0
</pre>
</details></td><td>-</td><td>-</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/8
