### ISSUE TITLE
`dApp`: create UI for `UbiquityPool`

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#833]
Depends on https://github.com/ubiquity/ubiquity-dollar/pull/832

There is the new [UbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol) contract (facet) where users can mint and redeem `Dollar` tokens for collateral tokens.

Minting example:
1. User calls [mintDollar()](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L77) and sends 100 `LUSD` as collateral
2. User gets 100 `Dollar` tokens

Redeeming example:
1. User calls [redeemDollar()](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L93) and sends 100 `Dollar` tokens
2. User waits for 2 blocks to be mined
3. User calls [collectRedemption()](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol#L107) and gets 100 `LUSD` collateral back

We should create a new UI page for the [UbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol) contract and make sure that it works with the local [anvil deploy script](https://github.com/ubiquity/ubiquity-dollar/blob/7a70182d49a0b9dc947c9925a5d28edc49c28b0d/packages/contracts/package.json#L31).

Since the [UbiquityPool](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/facets/UbiquityPoolFacet.sol) contract is forked from the [FraxPoolV3](https://github.com/FraxFinance/frax-solidity/blob/967002fc7f2c5ee9e175cabc763a776a8ed03e01/src/hardhat/contracts/Frax/Pools/FraxPoolV3.sol) contract we can take the Frax UI as an example:
- mint page: https://old.app.frax.finance/mint
- redeem page: https://old.app.frax.finance/redeem

Notice: the [getDollarPriceUsd()](https://github.com/ubiquity/ubiquity-dollar/blob/286c0cdf0841655e46b91b55d9ee56899a281508/packages/contracts/src/dollar/libraries/LibUbiquityPool.sol#L286) method may revert (because TWAP is not part of the deployment script, will be fixed in https://github.com/ubiquity/ubiquity-dollar/issues/827) so you will have to mock it 

P.S. All protocol contracts used in the UI can be found [here](https://github.com/ubiquity/ubiquity-dollar/blob/7a70182d49a0b9dc947c9925a5d28edc49c28b0d/packages/dapp/components/lib/hooks/contracts/use-protocol-contracts.ts)

Mint:
<img width="1512" alt="Screenshot 2023-11-15 at 16 18 53" src="https://github.com/ubiquity/ubiquity-dollar/assets/119500907/eb232f6d-b233-4e4c-84dc-8f2c55185f95">

Redeem:
<img width="1512" alt="Screenshot 2023-11-15 at 16 19 00" src="https://github.com/ubiquity/ubiquity-dollar/assets/119500907/f1859213-b416-4914-9d1b-5caf4c0361f8">

**Comment by Vayras** [comment]
Hi, I would like to contribute towards this issue

**Comment by rndquu** [comment]
> Hi, I would like to contribute towards this issue

Hey, you're free to start with the `/start` command

**Comment by yeshealer** [comment]
@rndquu I have a question, Should I create UI separately with this project or create new project for this faucet?

**Comment by rndquu** [comment]
> @rndquu I have a question, Should I create UI separately with this project or create new project for this faucet?

We should add a new web page here https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/dapp

**Comment by yeshealer** [comment]
thanks, one more question. Your project running environment is Ubuntu not windows?

**Comment by rndquu** [comment]
> thanks, one more question. Your project running environment is Ubuntu not windows?

Yes, the project definitely works on macos/linux, not sure about windows though

**Comment by yeshealer** [comment]
> > thanks, one more question. Your project running environment is Ubuntu not windows?
> 
> Yes, the project definitely works on macos/linux, not sure about windows though

I see thanks

**Comment by molecula451** [comment]
> thanks, one more question. Your project running environment is Ubuntu not windows?

the project basically is a node package + solidity smart contracts, so it's multi-platform,  and you should have no issues running on Windows, or any other OS, as the project is not OS dependent, just check your nodejs enviroment

**Comment by rndquu** [comment]
@yeshealer Hey, how is it going?

**Comment by yeshealer** [comment]
doing now. gonna show the result on next monday!!!

**Comment by molecula451** [comment]
not working anymore? @yeshealer

**Comment by molecula451** [comment]
@rndquu you think theres a forkable version of this UI?

**Comment by rndquu** [comment]
> @rndquu you think theres a forkable version of this UI?

Perhaps, I haven't checked yet

**Comment by PhantomCracker** [comment]
Hei @rndquu I will take this on my side, is ok ?

**Comment by rndquu** [comment]
> Hei @rndquu I will take this on my side, is ok ?

Sorry, I'm already working on it https://github.com/ubiquity/ubiquity-dollar/pull/860

**Comment by PhantomCracker** [comment]
Hei @rndquu, if you need help on this, please let me know.

**Comment by rndquu** [comment]
I think we simply need to take https://nextjs.org/ and rebuild the frontend for https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/dapp in a separate repository

**Comment by 0x4007** [comment]
That's fine. The repo needs to be initialized and then a task can be created

Repo name `uusd.ubq.fi`

**Comment by rndquu** [comment]
Closing this in favor of https://github.com/ubiquity/uusd.ubq.fi/issues/1
