### ISSUE TITLE
Road to production 2024

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#835]
- [x] https://github.com/ubiquity/ubiquity-dollar/pull/832
- [x] https://github.com/ubiquity/ubiquity-dollar/issues/833
- [x] https://github.com/ubiquity/ubiquity-dollar/issues/830
- [x] https://github.com/ubiquity/ubiquity-dollar/issues/827

**Comment by molecula451** [comment]
i have deployed the whole protocol to sepolia on clean account, this is how much is looking:

https://sepolia.etherscan.io/address/0x1c1F164aeb2d1e79A8d0b1968F0a7C9E8fb5dcbb
Diamond: https://sepolia.etherscan.io/address/0xb495d07a144196fa7dd04a7cbb69d4d601023ca1

**Comment by molecula451** [comment]
afaik we are in prod, i guess the contracts are deployed? we can move out from this issue? @rndquu

**Comment by rndquu** [comment]
> afaik we are in prod, i guess the contracts are deployed? we can move out from this issue? @rndquu

I haven't yet finished https://github.com/ubiquity/ubiquity-dollar/issues/833, I need more time to check out PRs/issues, finish the "permit Dollar fees" feature, and only then I'll get back to https://github.com/ubiquity/ubiquity-dollar/issues/833
