### ISSUE TITLE
Increase facet contracts forge / unit tests coverage

### ISSUE THREAD

**Issue by gitcoindev** [pavlovcik/uad-ui#838]
The goal is to facilitate AI and see if we can increase unit test coverage to 100% for all facets.

**Comment by 0x4007** [comment]
Surely using AI is not mandatory but I think it makes achieving this less daunting.

**Comment by gitcoindev** [comment]
I will push this forward next week (CW50) and close until Friday EOD.

**Comment by gitcoindev** [comment]
I am finishing other tasks and going back to this one. Let's see how much we can improve in this area.
