### ISSUE TITLE
Enforce same line bracket opens in Solidity

### ISSUE THREAD

**Issue by 0x4007** [pavlovcik/uad-ui#839]
A custom `lint-staged` script would need to run to enforce this bracket style on commits. I was unable to find a tool out-of-the-box for this but it is possible that they exist. 

> > @rndquu we are having styling issues, we should decide whether to allow
> > ```solidity
> > function setRndnuu() private {
> >     // code
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or
> > ```solidity
> > function setRndnuu() private
> > {
> > 
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this can be seen here as well as many other parts of the code
> 
> I guess the linter [decides](https://github.com/ubiquity/ubiquity-dollar/blob/10739ec9952bac4f588bde7bc4ca191d941f1dc7/package.json#L55) how to format code

I looked into this and we would have to make a custom tool to enforce this with lint-staged I believe.

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/832#issuecomment-1818047062_

**Comment by rndquu** [comment]
Let's start with utilizing our existing linter. Perhaps there is a rule which enforces line brackets to a particular format. If there is no such rule (or some other linter with such rule) then we could increase time estimate to `< 1 Day` to create our own custom solution.

**Comment by gitcoindev** [comment]
> Let's start with utilizing our existing linter. Perhaps there is a rule which enforces line brackets to a particular format. If there is no such rule (or some other linter with such rule) then we could increase time estimate to `< 1 Day` to create our own custom solution.

Good point. I started looking into this as well, the existing linter should be able to enforce this. I will check and should have a solution today.

**Comment by gitcoindev** [comment]
I already found the root cause, we should use prettier-plugin-solidity in lint-staged settings. I will test and submit a pr soon.

**Comment by gitcoindev** [comment]
I added the 'yarn format' to `packages/contracts` , made sure prettier-plugin-solidity is explicitly used and all in all the current formatting of `development` branch contracts matches `Prettier` way of formatting.

The full explanation is available at https://github.com/prettier-solidity/prettier-plugin-solidity/blob/main/STYLEGUIDE.md#function-declaration

I will add a mention to the style guide in contracts README.md , pasting here below the content for full clarity.

## Function Declaration

- [x] For short function declarations, it is recommended for the opening brace of the function body to be kept on the same line as the function declaration.

  The closing brace should be at the same indentation level as the function declaration.

  The opening brace should be preceded by a single space.

```Solidity
function increment(uint x) public pure returns (uint) {
    return x + 1;
}

function increment(uint x) public pure onlyowner returns (uint) {
    return x + 1;
}
```

- [x] The visibility modifier for a function should come before any custom modifiers.

```Solidity
function kill() public onlyowner {
    selfdestruct(owner);
}
```

- [x] For long function declarations, it is recommended to drop each argument onto it's own line at the same indentation level as the function body. The closing parenthesis and opening bracket should be placed on their own line as well at the same indentation level as the function declaration.

```Solidity
function thisFunctionHasLotsOfArguments(
    address a,
    address b,
    address c,
    address d,
    address e,
    address f
)
    public
{
    doSomething();
}
```

- [x] If a long function declaration has modifiers, then each modifier should be dropped to its own line.

```Solidity
function thisFunctionNameIsReallyLong(address x, address y, address z)
    public
    onlyowner
    priced
    returns (address)
{
    doSomething();
}

function thisFunctionNameIsReallyLong(
    address x,
    address y,
    address z,
)
    public
    onlyowner
    priced
    returns (address)
{
    doSomething();
}
```

- [x] Multiline output parameters and return statements should follow the same style recommended for wrapping long lines found in the [Maximum Line Length](#maximum_line_length) section.

```Solidity
function thisFunctionNameIsReallyLong(
    address a,
    address b,
    address c
)
    public
    returns (
        address someAddressName,
        uint256 LongArgument,
        uint256 Argument
    )
{
    doSomething()

    return (
        veryLongReturnArg1,
        veryLongReturnArg2,
        veryLongReturnArg3
    );
}
```

- [ ] For constructor functions on inherited contracts whose bases require arguments, it is recommended to drop the base constructors onto new lines in the same manner as modifiers if the function declaration is long or hard to read.

```Solidity
pragma solidity >=0.4.0 <0.7.0;

// Base contracts just to make this compile
contract B {
    constructor(uint) public {
    }
}


contract C {
    constructor(uint, uint) public {
    }
}


contract D {
    constructor(uint) public {
    }
}


contract A is B, C, D {
    uint x;

    constructor(uint param1, uint param2, uint param3, uint param4, uint param5)
        B(param1)
        C(param2, param3)
        D(param4)
        public
    {
        // do something with param5
        x = param5;
    }
}
```

These guidelines for function declarations are intended to improve readability. Authors should use their best judgement as this guide does not try to cover all possible permutations for function declarations.

Therefore, there are certain cases where the opening brace of a solidity function is formatted in the same line and some on the new line, depending on the rules above.

**Comment by gitcoindev** [comment]
Pull request opened https://github.com/ubiquity/ubiquity-dollar/pull/840

**Comment by molecula451** [comment]
the idea (my idea) is to enforce the tool to have the same pattern, this is a per best solidity practices, what do you think are the nuances on this due to long range functions with params? @gitcoindev

unless rndqnuu has different in how he wants to format.

best practice for solidity is

```solidity
function getPavlovcik() private {

}

struct PavlovcikInfo {
   address info;
}

struct OpenPavlovick {
   mapping(address => PavlovcikInfo) data; 
}

**Comment by rndquu** [comment]
I guess we can use any approach towards the brackets formatting unless it is consistent across the whole project

**Comment by gitcoindev** [comment]
> I guess we can use any approach towards the brackets formatting unless it is consistent across the whole project

I checked a few big projects

* OpenZeppelin uses prettier
* Uniswap uses prettier

They are also fine with mixed brackets formatting, see example here: https://github.com/Uniswap/v4-core/blob/main/src/test/MockHooks.sol vs https://github.com/Uniswap/v4-core/blob/main/src/test/MockContract.sol

I would stick then to whatever prettier output formats, too.

**Comment by gitcoindev** [comment]
@molecula451 another point to use prettier output without changes is: https://prettier.io/docs/en/why-prettier

And from the main website https://prettier.io/

Why?

* Your code is formatted on save
* No need to discuss style in code review
* Saves you time and energy

And Ubiquity would use the same formatting tool as big code-bases, which makes it easier to onboard new partners / projects.

**Comment by 0x4007** [comment]
> ```solidity
> getPavlovcik()
> ```

"Hello, World!"
