### ISSUE TITLE
Enforce linting check on contracts naming convention

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#849]
https://github.com/ubiquity/ubiquity-dollar/pull/848#issuecomment-1852582043

**Comment by gitcoindev** [comment]
Perhaps solhint or https://github.com/solhint-community/solhint-community fork could be integrated after all rules are agreed:

Example settings:

https://github.com/PaulRBerg/foundry-template/blob/main/.solhint.json


There are differences in so called 'best practices' rules, it would be good to fully review and decide on which subset or superset of rules to use.

https://github.com/protofire/solhint/blob/develop/docs/rules.md#best-practise-rules

vs

https://github.com/solhint-community/solhint-community/blob/master/docs/rules.md#best-practise-rules

**Comment by molecula451** [comment]
> Perhaps solhint or https://github.com/solhint-community/solhint-community fork could be integrated after all rules are agreed:
> 
> Example settings:
> 
> https://github.com/PaulRBerg/foundry-template/blob/main/.solhint.json
> 
> There are differences in so called 'best practices' rules, it would be good to fully review and decide on which subset or superset of rules to use.
> 
> https://github.com/protofire/solhint/blob/develop/docs/rules.md#best-practise-rules
> 
> vs
> 
> https://github.com/solhint-community/solhint-community/blob/master/docs/rules.md#best-practise-rules

#851

**Comment by 0x4007** [comment]
> There are differences in so called 'best practices' rules, it would be good to fully review and decide on which subset or superset of rules to use.

lol thats unfortunate. 

I just [asked ChatGPT](https://chat.openai.com/share/abb2a965-d0c0-4d69-af0c-05bdc300e6f2) and it says that the following rules are 

### Not under debate (we should probably enable):

```
avoid-call-value
avoid-low-level-calls
avoid-sha3
avoid-suicide
avoid-throw
avoid-tx-origin
check-send-result
compiler-version
func-visibility
multiple-sends
no-complex-fallback
no-inline-assembly
not-rely-on-block-hash
reentrancy
state-visibility
```

### Recommended in community only:

```
max-states-count
no-console
no-empty-blocks
no-global-import
no-unused-import
no-unused-vars
payable-fallback
reason-string
quotes
const-name-snakecase
contract-name-camelcase
event-name-camelcase
func-name-mixedcase
use-forbidden-name
var-name-mixedcase
imports-on-top
visibility-modifier-order
```

### Recommended in original only:

```
mark-callable-contracts (recommended in "community.md" as deprecated)
not-rely-on-time (not recommended in "community.md")
```

## My Recommendation

I will need to research the rules at a later time but upon first pass:

###### Community

| Enabled | Rule | Comment |
|---|---|---|
| ❌ | max-states-count | not sure what this is
| ❌ | no-console |
| ✅ | no-empty-blocks |
| ✅ | no-global-import | not sure what this is but globals are bad in javascript so I assume it's bad here too
| ✅ | no-unused-import | 
| ✅ | no-unused-vars |
| ✅ | payable-fallback | i think this means something about the contract being able to handle eth? 
| ❌ | reason-string |
| ❌ | quotes |
| ❌ | const-name-snakecase |
| ❌ | contract-name-camelcase | shouldn't these normally be pascal case?
| ❌ | event-name-camelcase |
| ❌ | func-name-mixedcase |
| ❌ | use-forbidden-name |
| ❌ | var-name-mixedcase |
| ✅ | imports-on-top |
| ❌ | visibility-modifier-order |


###### Original


| Enabled | Rule | Comment |
|---|---|---|
| ❌ | mark-callable-contracts (recommended in "community.md" as deprecated) | no idea what this is
| ❌ | not-rely-on-time (not recommended in "community.md") | no idea what this is

**Comment by molecula451** [comment]
It's nice the recopilation, but we should follow the convention by 50% or own judment, the reason?

an e.g
> no-inline-assembly

We have inline assembly in diamond, and there is no issue with that, as much as it shows as recommended, it can be turned off.. This is one of many others

The idea (my idea) it's to stylize the code more and enforce the rules, but still many of these can be turned off

sha3? no body uses sha3 (in solidity) anymore, i don't see any good judment on solidity code writing sha3.. for e.g

**Comment by 0x4007** [comment]
> ```diff
> ! action returned an unexpected value
> ```

Currently trying to debug this but I'm only seeing it in this repo so I'm debugging in production now. Sorry for the incoming notifications.


```
{
	    log: 'action has an uncaught error',
	    level: 'error',
	    metadata: {
	      logReturn: TypeError: Cannot read properties of undefined (reading 'created_at')
	          at checkTaskToUnassign (/var/task/.netlify/functions/webhooks/webhooks.js:192291:60)
	          at processTicksAndRejections (node:internal/process/task_queues:95:5)
	          at async Promise.all (index 0)
	          at checkTasksToUnassign (/var/task/.netlify/functions/webhooks/webhooks.js:192241:27)
	          at logAnyReturnFromHandlers (/var/task/.netlify/functions/webhooks/webhooks.js:192652:24)
	          at bindEvents (/var/task/.netlify/functions/webhooks/webhooks.js:192645:5)
	          at async Promise.all (index 0)
	          at Runtime.handler (/var/task/.netlify/functions/webhooks/webhooks.js:192748:5) {
	        [stack]: "TypeError: Cannot read properties of undefined (reading 'created_at')\n    at checkTaskToUnassign (/var/task/.netlify/functions/webhooks/webhooks.js:192291:60)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 0)\n    at checkTasksToUnassign (/var/task/.netlify/functions/webhooks/webhooks.js:192241:27)\n    at logAnyReturnFromHandlers (/var/task/.netlify/functions/webhooks/webhooks.js:192652:24)\n    at bindEvents (/var/task/.netlify/functions/webhooks/webhooks.js:192645:5)\n    at async Promise.all (index 0)\n    at Runtime.handler (/var/task/.netlify/functions/webhooks/webhooks.js:192748:5)",
	        [message]: "Cannot read properties of undefined (reading 'created_at')"
	      },
	      handlerType: { type: 'wildcard', actions: [ [AsyncFunction: checkTasksToUnassign] { [length]: 1, [name]: 'checkTasksToUnassign', [Symbol(Symbol.toStringTag)]: 'AsyncFunction' }, [length]: 1 ] },
	      activeHandler: 'checkTasksToUnassign',
	      error: { name: 'TypeError', message: "Cannot read properties of undefined (reading 'created_at')", stack: "TypeError: Cannot read properties of undefined (reading 'created_at')\n    at checkTaskToUnassign (/var/task/.netlify/functions/webhooks/webhooks.js:192291:60)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 0)\n    at checkTasksToUnassign (/var/task/.netlify/functions/webhooks/webhooks.js:192241:27)\n    at logAnyReturnFromHandlers (/var/task/.netlify/functions/webhooks/webhooks.js:192652:24)\n    at bindEvents (/var/task/.netlify/functions/webhooks/webhooks.js:192645:5)\n    at async Promise.all (index 0)\n    at Runtime.handler (/var/task/.netlify/functions/webhooks/webhooks.js:192748:5)" },
	      caller: 'renderCatchAll',
	      revision: '05a143c'
	    }
	  }
```

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
Netlify logs just stopped outputting any of my logs suddenly...

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by gitcoindev** [comment]
> ```diff
> @@ No latest assign event found. @@
> ```

that might be it - > nobody was assigned yet
in this case reduce returns nothing and it may fail at (just guessing by looking at code)

`const latestAssignEventTime = new Date(latestAssignEvent.created_at).getTime();`

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by molecula451** [comment]
@pavlovcik be honest, you did it to showcast the new table command data, looking amazing 😄  🔥 🔥 !!

**Comment by 0x4007** [comment]
> @pavlovcik be honest, you did it to showcast the new table command data, looking amazing 😄 🔥 🔥 !!

lol really its cause I couldn't reproduce the assign event error but I think its because its from other issues that the wildcard automatic unassign finds. Also I added a lot more logs so that's why we were able to diagnose the issue better. 

Thanks for the compliment!

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
test

**Comment by 0x4007** [comment]
testing netlify logs

**Comment by molecula451** [comment]
test

**Comment by molecula451** [comment]
test

**Comment by molecula451** [comment]
> testing netlify logs

looks like still outputting logs after a few hours

**Comment by rndquu** [comment]
We already [use](https://github.com/ubiquity/ubiquity-dollar/blob/6c25a2deb401a2cec8f2cc2a63b52618882c6a4a/package.json#L56) `prettier` for `*.sol` files so this issue, as far as I understand, may be closed.
