### ISSUE TITLE
Update or deprecate empty code block functions on core contracts

### ISSUE THREAD

**Issue by molecula451** [pavlovcik/uad-ui#850]
Empty code blocks:

https://github.com/ubiquity/ubiquity-dollar/blob/b1f5a0a86ae58791d03d1c4d4f7924a460043dd2/packages/contracts/src/dollar/core/UbiquityDollarToken.sol#L191

https://github.com/ubiquity/ubiquity-dollar/blob/b1f5a0a86ae58791d03d1c4d4f7924a460043dd2/packages/contracts/src/dollar/core/UbiquityGovernanceToken.sol#L74

**Comment by rndquu** [comment]
`_authorizeUpgrade` is responsible for checking permissions on contract upgrade ([docs](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/1369b17b1ebadfbcee764aa9eddbf9f4104753ff/contracts/proxy/utils/UUPSUpgradeable.sol#L123)). There is the `onlyAdmin` modifier that checks that only admin is able to perform upgrades. If we remove `_autorizeUpgrade` (with empty code block) then anyone will be able to upgrade contracts.

**Comment by rndquu** [comment]
Closing this as "not planned" because we do need the `_authorizeUpgrade` empty block code because of the `onlyAdmin` modifier which checks permissions on who can upgrade a contract.

**Comment by molecula451** [comment]
i'm good to in closing by now, but there must be a better way to handle, code seems a bit outdated (thats why i opened initially), so ill be probably reopening soon
