### ISSUE TITLE
Fix `yarn coverage`

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#862]
There is the https://github.com/ubiquity/ubiquity-dollar/blob/f99f7e7995a83657b54d7a4b61fe1722e70d1971/packages/contracts/coverage.sh script which produces the following output:
<img width="604" alt="Screenshot 2024-01-02 at 14 32 25" src="https://github.com/ubiquity/ubiquity-dollar/assets/119500907/ee8b70e5-2a82-436c-baf3-bfab9dde2c58">

That output is not accurate because coverage for some of the contracts is not accurate.

If you run coverage with `forge coverage` you will see that `LibUbiquityPool` has 100% line coverage while https://github.com/ubiquity/ubiquity-dollar/blob/f99f7e7995a83657b54d7a4b61fe1722e70d1971/packages/contracts/coverage.sh outputs 16.8%.

What should be done:
1. Either fix the [`yarn coverage`](https://github.com/ubiquity/ubiquity-dollar/blob/f99f7e7995a83657b54d7a4b61fe1722e70d1971/packages/contracts/coverage.sh) script either delete it if it's not used anywhere.
2. Make sure that `yarn coverage` outputs "real" coverage values (you can simply call `forge coverage` under the hood)

**Comment by rndquu** [comment]
The bot is live 🎉

**Comment by molecula451** [comment]
as far as I concern the coverage.sh scripts its used by coveralls when projecting the coverage

**Comment by rndquu** [comment]
> as far as I concern the coverage.sh scripts its used by coveralls when projecting the coverage

You mean [this](https://github.com/ubiquity/ubiquity-dollar/blob/2d1cfeb7178481138e820a8f22405ddaff6e4975/.github/workflows/coverage-check.yml) workflow? Can't see any mentions of `coverage.sh`

**Comment by molecula451** [comment]
if you want we can remove it as it looks like [this workflow]( https://github.com/ubiquity/ubiquity-dollar/blob/2d1cfeb7178481138e820a8f22405ddaff6e4975/.github/workflows/coverage-check.yml) does the same without the need for the  shell script, but i can't reproduce what you saying on the issue as it's outputing close to what we can results

[Screencast from 03-01-24 19:28:33.webm](https://github.com/ubiquity/ubiquity-dollar/assets/41552663/cea6b8d8-f630-4479-ac8d-483e4234e26f)

**Comment by rndquu** [comment]
> if you want we can remove it as it looks like [this workflow](https://github.com/ubiquity/ubiquity-dollar/blob/2d1cfeb7178481138e820a8f22405ddaff6e4975/.github/workflows/coverage-check.yml) does the same without the need for the shell script, but i can't reproduce what you saying on the issue as it's outputing close to what we can results

Yeah, I guess we can simply remove the `coverage.sh` script

**Comment by molecula451** [comment]
i think we should leave it, looks like a useful tool to have when making changes offline, and look for some coverage, but i will need to check why it's giving those results to you

**Comment by gitcoindev** [comment]
Just not to forget permit for 37.5 DAI for @molecula451 should be generated here.

**Comment by molecula451** [comment]
it is what it is and strive pushing forward Dollar (UBQ)

**Comment by molecula451** [comment]
its a matter of time for Dollar V1 to be live
