### ISSUE TITLE
closed issue

### ISSUE THREAD

**Issue by gitcoindev** [pavlovcik/uad-ui#869]

**Comment by gitcoindev** [comment]
Let me tackle this one first.

**Comment by molecula451** [comment]
but only submit the PR that will be reference to the issue on the audit judging repo

**Comment by 0x4007** [comment]
I thought we agreed to resolve the ones on the judging repository, as I understand that we are still deciding which ones are valid etc. Why are we making copies here? It can make things out of sync if issues are still being decided on.

I think we should only mirror the issues once they are closed as completed for archival purposes. 

Related https://github.com/ubiquity/ubiquity-dollar/issues/874#issuecomment-1899710855
