### ISSUE TITLE
Incorrect access control or stale Natspec/docs on `UbiquityDollarToken.setIncentiveContract()`

### ISSUE THREAD

**Issue by 0xRizwan** [pavlovcik/uad-ui#898]
## Title
Incorrect access control or stale Natspec/docs on `UbiquityDollarToken.setIncentiveContract()`

## Vulnerability details

[UbiquityDollarToken.setIncentiveContract()](https://github.com/ubiquity/ubiquity-dollar/blob/38c3656539ae19fe9be162f566b36ec62a3e6e41/packages/contracts/src/dollar/core/UbiquityDollarToken.sol#L68) is used to set incentive contracts for accounts.

```solidity

    function setIncentiveContract(address account, address incentive) external {
        require(
            accessControl.hasRole(GOVERNANCE_TOKEN_MANAGER_ROLE, _msgSender()),
            "Dollar: must have admin role"
        );

        incentiveContract[account] = incentive;
        emit IncentiveContractUpdate(account, incentive);
    }
```

The issue here is with access control given to the above function. The revert message states `"Dollar: must have admin role"`, it means the function is expected to have `Admin role` as only address who can access the `UbiquityDollarToken.setIncentiveContract()` function, However, the `GOVERNANCE_TOKEN_MANAGER_ROLE` is set which seems to be incorrect. On further study on this issue, the readme docs of incentive further confirms that the acces control should be given to Admin role.

Per [interface.IIncentive.md](https://github.com/ubiquity/ubiquity-dollar/blob/38c3656539ae19fe9be162f566b36ec62a3e6e41/packages/contracts/docs/src/src/dollar/interfaces/IIncentive.sol/interface.IIncentive.md?plain=1#L7),

> Dollar admin can set an incentive contract . . . 

Per [IIncentive.sol](https://github.com/ubiquity/ubiquity-dollar/blob/38c3656539ae19fe9be162f566b36ec62a3e6e41/packages/contracts/src/dollar/interfaces/IIncentive.sol#L7)

> Dollar admin can set an incentive contract . . . 

It can be said that the issue either relies with stale or incorrect readme documentation or Natspec or Incorrect function access implementation.

## Recommendation

If the `UbiquityDollarToken.setIncentiveContract()` function is expected to be called by admin then do the following change,

```diff

    function setIncentiveContract(address account, address incentive) external {
-        require(
-            accessControl.hasRole(GOVERNANCE_TOKEN_MANAGER_ROLE, _msgSender()),
-            "Dollar: must have admin role"
-        );
+        require(
+            accessControl.hasRole(DEFAULT_ADMIN_ROLE, _msgSender()),
+            "Dollar: must have admin role"
+        );

        incentiveContract[account] = incentive;
        emit IncentiveContractUpdate(account, incentive);
    }
```

OR . . .

If function implementation is correct then correct the stale docs/Natspec mentioning tokenManager instead of Admin to avoid confusion to code readers.

cc- @pavlovcik @molecula451

**Comment by molecula451** [comment]
This was purged as a part of the fix-review branch https://github.com/ubiquity/ubiquity-dollar/commit/bb6543eb61e8f328a9b12d20735d4785e9570c2b
