### ISSUE TITLE
[LOW] - Collateral ratio should be capped

### ISSUE THREAD

**Issue by 0xadrii** [pavlovcik/uad-ui#929]
[LOW] - Collateral ratio should be capped

As seen in [Frax's code](https://github.com/FraxFinance/frax-solidity/blob/967002fc7f2c5ee9e175cabc763a776a8ed03e01/src/hardhat/contracts/Frax/Frax.sol#L212), collateral ratio will always be capped at 100%. For Ubiquity, if a higher value is wrongly set and the dynamic CR is implemented, then it could cause some issues. It is recommended to add a maximum value for `newCollateralRatio` of 1_000_000.

_Originally posted by @0xadrii in https://github.com/ubiquity/ubiquity-dollar/pull/922#discussion_r1572505552_

**Comment by gitcoindev** [comment]
Seems straightforward to implement, I will pick it up.
