### ISSUE TITLE
CI: fix storage collision workflows

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#942]
Right now the following storage collision related workflows are failing with the same error `Error reading JToken from JsonReader. Path '', line 0, ...`:
- https://github.com/ubiquity/ubiquity-dollar/actions/runs/9641086348/workflow
- https://github.com/ubiquity/ubiquity-dollar/actions/runs/9641086347/workflow

What should be done:
- fix CI errors for both of the workflows

**Comment by rndquu** [comment]
@gitcoindev FYI

**Comment by gitcoindev** [comment]
I am on it, will try to find the root cause and solve it by tomorrow.

**Comment by gitcoindev** [comment]
Root cause found and fixed. Pull request opened: https://github.com/ubiquity/ubiquity-dollar/pull/948
