### ISSUE TITLE
Find optimal number of `runs` for fuzz/invariant tests

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#943]
Depends on https://github.com/ubiquity/ubiquity-dollar/issues/563

What should be done:
- when https://github.com/ubiquity/ubiquity-dollar/issues/563 is ready find out a number of [runs](https://book.getfoundry.sh/reference/config/testing#runs-1) so that github CI could run for up to 6 hours (github CI max limit)
- for already implemented fuzzing tests also find out a number of [runs](https://github.com/ubiquity/ubiquity-dollar/blob/64ab8b9e378abe7cc019924bd43e7891d6d9d884/packages/contracts/foundry.toml#L44) so that github CI could run for up to 6 hours

**Comment by zugdev** [comment]
Are the workflows properly setup? It doesn't feel like it is.

**Comment by 0x4007** [comment]
> /start
> 
> 

@gentlementlegen i thought line breaks are handled already

**Comment by gentlementlegen** [comment]
@0x4007 yes we had a fix for that, kernel and plug-in side.

**Comment by zugdev** [comment]
I meant fuzz and invariant workflows though, it seems at least that `foundry.toml` profiles are wrong. I will check that tomorrow.

**Comment by rndquu** [comment]
> I meant fuzz and invariant workflows though, it seems at least that `foundry.toml` profiles are wrong. I will check that tomorrow.

What exactly is wrong?

**Comment by zugdev** [comment]
It's not wrong, forget about that.
