### ISSUE TITLE
CI: add security rules from `semgrep`

### ISSUE THREAD

**Issue by rndquu** [pavlovcik/uad-ui#949]
Check [this](https://github.com/Decurity/semgrep-smart-contracts) repository which introduces a workflow for scanning security issues from https://semgrep.dev/p/smart-contracts.

What should be done:
- add a new workflow to scan for security issues via `semgrep`

**Comment by molecula451** [comment]
do we want this to be run each time a PR is opened no?

**Comment by rndquu** [comment]
> do we want this to be run each time a PR is opened no?

Yes

**Comment by molecula451** [comment]
![Screenshot from 2024-07-29 17-22-00](https://github.com/user-attachments/assets/fb032f2c-d9f0-47b0-b247-09fa9824622a)

**Comment by obeys** [comment]
waiting on code review.

**Comment by rndquu** [comment]
@gentlementlegen Why was the `permitGeneration` setting [commented out](https://github.com/ubiquity/ubiquibot-config/commit/99416721a9fba84e1eeb24b8a71f6b0e2413102b) in the bot's config? Typo?

**Comment by gentlementlegen** [comment]
@rndquu I was testing a fix earlier and commented it out to avoid generating permits, forgot to revert it, my bad.
